### ISSUE TITLE
[Bug]: Unable to add new user

### ISSUE THREAD

**Issue by wesleymeier** [apisec-inc/Support#100]
### Severity

Blocker

### What happened?

When attempting to add a new user (as an Admin), UI only presents Add Guest User (New User and New Users Bulk is ghosted out).  Using Add Guest User to setup another user fails with error code 'Invalid Request"

**Comment by muqeetkhan20** [comment]
@wesleymeier I am able to perform this operation.

Adding the New User:
![image](https://user-images.githubusercontent.com/68276700/178904566-50c49df2-0a15-4274-9168-eb223cfa3470.png)

Successfully added the new user:
![image](https://user-images.githubusercontent.com/68276700/178904691-9df24890-017e-4741-817b-c737d04e741b.png)

**Comment by Mohammed-Luqman-Shareef** [comment]
Closing this ticket, since no issues found.
