### ISSUE TITLE
[Bug]: Error on WebMethods Scanner list

### ISSUE THREAD

**Issue by SuddenDevelopment** [apisec-inc/Support#101]
### Severity

Medium

### What happened?

Error on WebMethods Scanner list

I don't know there is functionality behind this that is missing or it's just an unfriendly way of saying there are no scanners.

![Screen Shot 2022-07-18 at 5 02 01 PM](https://user-images.githubusercontent.com/138704/179616842-dfbd45ed-b4a4-435f-97ee-c7222f898f74.png)

**Comment by muqeetkhan20** [comment]
@MuqeedA we need to improve messaging for the given invalid credentials, it's throwing some weird or technical errors. Let's apply the messaging for all the gateways. I am able to reproduce for Azure and Web methods.

Acceptance message: "Invalid credentials"

![image](https://user-images.githubusercontent.com/68276700/180933377-690cbfc1-cf14-4b64-80e4-f0e4210ba274.png)
![image](https://user-images.githubusercontent.com/68276700/180933432-ef7f4800-0ba7-475c-8d24-671c83b0f59b.png)

**Comment by Mohammed-Luqman-Shareef** [comment]
@Abedeen1 Pls make changes for the all the Gateways to handle the errors and send a generic error msg to CP to return to UI.

**Comment by Abedeen1** [comment]
@muqeetkhan20 , Could you please provide Azure API Gateway creds.

Regards,
Abedeen.

**Comment by Abedeen1** [comment]
No Response, leaving ticket.

**Comment by muqeetkhan20** [comment]
@Abedeen1 not sure if i missed to see your request.
@MaimoonaFatima could you please provide azure creds to abedeen.

**Comment by MaimoonaFatima** [comment]
I don't have azure credentials.

**Comment by mohdrashid1** [comment]
@Abedeen1 bhai you already have Azure Portal Access see SS
![image](https://user-images.githubusercontent.com/59992299/185922126-ffa32fcc-e81d-4186-8c7b-3edcddeceaf4.png)

**Comment by Abedeen1** [comment]
@mohdrashid1 ,
azure is asking credit card. for me to aceess api gateway.

![image](https://user-images.githubusercontent.com/87793504/185923891-4fcfa89c-be44-435c-82ec-5a7ed65e053a.png)

**Comment by mohdrashid1** [comment]
![image](https://user-images.githubusercontent.com/59992299/185935197-65b2b42d-bfb8-4ff0-9cda-8092d85812ff.png)

Got all details to register in Azure API Gateway

**Comment by Abedeen1** [comment]
> ![image](https://user-images.githubusercontent.com/59992299/185935197-65b2b42d-bfb8-4ff0-9cda-8092d85812ff.png)
> 
> Got all details to register in Azure API Gateway

Thanks! Got the info.

**Comment by MaimoonaFatima** [comment]
- [ ]  If we are giving invalid credentials, getting the below errors for software AG webmethods.io and WSO2 Gateways.
![image](https://user-images.githubusercontent.com/72252407/186644147-949d2dc7-3f16-4fef-b5b1-4d4816f7cfe3.png)
![image](https://user-images.githubusercontent.com/72252407/186644338-4c9fa229-da7a-4874-b6fe-b836423c752c.png)

- [ ] WSO2
![image](https://user-images.githubusercontent.com/72252407/186645203-50a9ff09-edf6-4d77-81bd-06d7b39b14fb.png)

**Comment by MaimoonaFatima** [comment]
As we have few more message improvements, removing QA tag

**Comment by asifadn9** [comment]
verified in Prod, working fine.
