### ISSUE TITLE
[Bug]: Documentation site is not redeploying reliably

### ISSUE THREAD

**Issue by SuddenDevelopment** [apisec-inc/Support#103]
### Severity

Blocker

### What happened?

when I updated documentation files it kicks off Github Actions ot rebuild and redeploy. the job goes very quickly in under 1 minute, but the site wasn't accessible for about 1 hour.

Today we have a similar issue it's been 20 minutes since the data was updated and Atef and I verified we cannot reach the site. I tried re-running the github action and it succeeded quickly again but didnt bring up the site.

Worth noting that this appears to have occurred at the same time a new URL / subdomain was used for dopcumentation.

**Comment by muqeetkhan20** [comment]
@SuddenDevelopment 2 things over here:
We should not push bunch of commits at a time, we have to give some breath after each commit.
and you can give a  try in incognito mode for the changes to reflect immediately, few times due to cache enabled it gives hard time to reflect the changes.

**Comment by SuddenDevelopment** [comment]
@muqeetkhan20  ok I figured that was the cause. How do we correct it when it happens?

**Comment by muqeetkhan20** [comment]
try to clear cookies and cache in your browser.
