### ISSUE TITLE
[Bug]: After the site session timeout, clicking on the OK popup, it redirects to login page with the AWS saved key-secret as username & password.

### ISSUE THREAD

**Issue by atef-aa** [apisec-inc/Support#105]
### Severity

Medium

### What happened?

When the APIsec site session times out, a popup message appears with a message and OK button.  After clicking on that it routes to login page.  On the login page, if the user saved the Access-key and Secret-key to the browser, then those credentials are appearing.  

**This can expose the secret-key if someone else other than the account holder clicks on the eye to view the password.**

However, this is **not** happening when I browse to the login page by clicking on the Login button from the homepage.  It's also **not** happening when I click on Logout and get redirect back to login page.

Attached a screenshot for reference.

<img width="999" alt="Screen Shot 2022-07-20 at 5 11 01 PM" src="https://user-images.githubusercontent.com/109250250/180095355-db814369-f601-46ab-829e-8f1708673e5f.png">

**Comment by muqeetkhan20** [comment]
@atef-aa I believe these are saved in your browser cookies, so it will be visible only to you. Thanks

**Comment by Mohammed-Luqman-Shareef** [comment]
@muqeetkhan20 If it is a browser/cookies issue, you can close this ticket.

**Comment by muqeetkhan20** [comment]
@muqeetkhan20 it seems like a browser issue, but still @atef-aa wants to reproduce it again.
@atef-aa we will close the ticket for now, we can discuss on the call if you are able to reproduce this issue again.
