### ISSUE TITLE
[Bug]: The Configuration and Reports tabs under the project are not highlighted when selected.

### ISSUE THREAD

**Issue by atef-aa** [apisec-inc/Support#106]
### Severity

Medium

### What happened?

When a user selects a project and lands on the project page, then navigates to Configurations or Reports, though they are selected, the tabs are not bolded.  

However, it does highlight with blue line under the selected item (which is fine).

**Steps to reproduce**
Under All Projects > Select a project >  Once you land on the main page > Select Configurations or Report

Attached a screenshot for reference:

<img width="894" alt="Screen Shot 2022-07-20 at 5 51 47 PM" src="https://user-images.githubusercontent.com/109250250/180096933-64ce8338-79d1-44d8-af31-4aea24751a92.png">

**Comment by muqeetkhan20** [comment]
@atef-aa this is an intended design, we just wanted to highlight the project name tab, other tabs are muted text.

**Comment by Mohammed-Luqman-Shareef** [comment]
@muqeetkhan20 Since this is not a bug, pls close the ticket.
