### ISSUE TITLE
[Bug]: Integrations->Notifications->Inactive is wrong status

### ISSUE THREAD

**Issue by SuddenDevelopment** [apisec-inc/Support#107]
### Severity

Medium

### What happened?

The slack notification status toggle is reversed.

Active should be toggle on and green
Inactive should be grey and toggled left

![Screen Shot 2022-07-21 at 4 15 20 PM](https://user-images.githubusercontent.com/138704/180307862-ac4661e0-779c-4c6d-b866-9ab2ef5777b1.png)

![Screen Shot 2022-07-21 at 4 17 56 PM](https://user-images.githubusercontent.com/138704/180307557-ccc34c2b-837a-4a5c-804c-4477f4be6f9a.png)
.

**Comment by muqeetkhan20** [comment]
@SuddenDevelopment we have already logged this bug in our engineering board, we can close this ticket.
https://github.com/apisec-inc/Engineering/issues/263

**Comment by ImranShaik065** [comment]
![image](https://user-images.githubusercontent.com/87167248/180385208-10862fb5-8e35-409c-903d-76ae17889087.png)
Fixed.

**Comment by SuddenDevelopment** [comment]
ok thanks, was unaware of the other place to check.
