### ISSUE TITLE
[Bug]: Wrong Error for Free account on "Collaborators"

### ISSUE THREAD

**Issue by SuddenDevelopment** [apisec-inc/Support#108]
### Severity

Medium

### What happened?

When using a free account and clicking on Configurations->Details->Collaborators get the wron Error Message, everywhere else it says to upgrade to pro[
![Screen Shot 2022-07-21 at 4 36 48 PM](https://user-images.githubusercontent.com/138704/180311305-bea8e3c9-8293-42f0-a1d7-cc359b4bb13c.png)
](url)

**Comment by muqeetkhan20** [comment]
@SuddenDevelopment free user have limitations, he is not allowed to collob the resources. though we can improve the messaging.

**Comment by MuqeedA** [comment]
Code changes pushed.
<img width="914" alt="image" src="https://user-images.githubusercontent.com/87184027/180949842-01424dec-f725-4919-9d76-18971fbd5f18.png">

**Comment by amer-apisec** [comment]
Working fine, should be available in next prod refresh.
