### ISSUE TITLE
[Bug]:  Error clicking next when it should be disabled?

### ISSUE THREAD

**Issue by SuddenDevelopment** [apisec-inc/Support#109]
### Severity

Medium

### What happened?

from a free account I ran a scan, looking at the results there are navigation buttons in the top right I'm guessing to go to next scan result? when I clicked on the right arrow I got the following error.

I'm guessing the arrow should be disabled if there is no next scan

![Screen Shot 2022-07-21 at 5 05 17 PM](https://user-images.githubusercontent.com/138704/180315410-55f5af3a-5bd2-44cd-b0ad-7b8f4a6d595f.png)

**Comment by muqeetkhan20** [comment]
@SuddenDevelopment this bug is already raised on 15th july and it's fixed, it will be available in next prod refresh.
https://github.com/apisec-inc/Engineering/issues/234
