### ISSUE TITLE
[Feature]: Update login prompt

### ISSUE THREAD

**Issue by danapisec** [apisec-inc/Support#11]
### Please describe your problem?

Currently when a user's login expires they are presented with an alarming message "Something went wrong." Would be friendlier to say something like "Please login."

### How important is this feature?

Nice to Have

### Describe the solution you'd like?

Change the popup to a friendly message - or just present the login fields.

**Comment by MuqeedA** [comment]
Changes completed as below

![image](https://user-images.githubusercontent.com/87184027/157595993-82095697-41e1-4d77-8674-ff41b08c2ee5.png)

**Comment by muqeetkhan20** [comment]
@intesar & @MuqeedA  I think this message looks pretty clear for the end user
![image](https://user-images.githubusercontent.com/68276700/157727224-6230aa5e-3e25-4619-8d6a-c223484e61c8.png)

**Comment by intesar** [comment]
> @intesar & @MuqeedA I think this message looks pretty clear for the end user ![image](https://user-images.githubusercontent.com/68276700/157727224-6230aa5e-3e25-4619-8d6a-c223484e61c8.png)

Looks good. Please proceed with this design.

**Comment by MuqeedA** [comment]
As per the discussion , changes completed as below.
![image](https://user-images.githubusercontent.com/87184027/157809040-d5eea05e-aaae-4c24-ac33-1681d7cba750.png)

**Comment by MuqeedA** [comment]
Made few more changes as per the request  from QA team
![image](https://user-images.githubusercontent.com/87184027/158106722-bcf5c57e-c3e5-4099-b8c9-75d9ed37e4b2.png)

**Comment by muqeetkhan20** [comment]
@MuqeedA as discussed on the call, let's improve the look and feel by applying the color (preferably blue)

**Comment by muqeetkhan20** [comment]
@MuqeedA Thanks for the improvements, this looks great...
![image](https://user-images.githubusercontent.com/68276700/159208667-c36b0577-0582-4030-af00-c6be83128ec6.png)

**Comment by muqeetkhan20** [comment]
@MuqeedA you can move it to Done, we will review in prod and close the ticket.

**Comment by MuqeedA** [comment]
Changes completed as requested , hence closing the ticket.
