### ISSUE TITLE
[Bug]: My email report never showed up 24 hours later

### ISSUE THREAD

**Issue by SuddenDevelopment** [apisec-inc/Support#110]
### Severity

Medium

### What happened?

From the scan summary page I opened a menu and selected "Summary Report" it said it woked. It was supposed to go to anthony@apisec.ai 

this was on a free account. if it's not allowed on a free account it should say so.

![Screen Shot 2022-07-22 at 3 26 38 PM](https://user-images.githubusercontent.com/138704/180513634-b6e8d145-e2ad-4b7b-a824-24eb504579b6.png)
.

**Comment by muqeetkhan20** [comment]
@SuddenDevelopment Yes, free account has restrictions to generate the reports. We will have to improve the messaging. 
@MuqeedA please take care of this.

**Comment by MuqeedA** [comment]
UI changes pushed.
<img width="905" alt="image" src="https://user-images.githubusercontent.com/87184027/180929598-827621e9-49a3-47db-8a19-b3238a143f49.png">

**Comment by amer-apisec** [comment]
Verified in dev, working fine.
It would be available after the prod refresh.
