### ISSUE TITLE
[Bug]: document header header definition

### ISSUE THREAD

**Issue by SuddenDevelopment** [apisec-inc/Support#113]
### Severity

Blocker

### What happened?

I was trying to add custom headers such as :
`Get:[x-trigger:CORS]`

and it did not copy over to playbooks.
need to be able to define custom headers like this for all endpoints, to define security categories from the UI

**Comment by intesar** [comment]
I tested these, and it didn't work either:
*:*[Origin: https://possibly.vulnerable.com]
Get:*[Origin: https://possibly.vulnerable.com]
Put:*[Origin: https://possibly.vulnerable.com]
Post:*[Origin: https://possibly.vulnerable.com]
Delete:*[Origin: https://possibly.vulnerable.com]
Get[Origin: https://possibly.vulnerable.com]
*/*[Origin: https://possibly.vulnerable.com]

This syntax worked.
Get:/api/v1/products[Origin: https://possibly.vulnerable.com]

We need to support this syntax and add it to the UI pages across "Security Categories" tile and project/categories
*:*[Origin: https://possibly.vulnerable.com]

**Comment by SuddenDevelopment** [comment]
what about wildcard in path like:
Get:/api/v1/*[Origin: https://possibly.vulnerable.com]

can we also support that while working on this?

**Comment by atef-aa** [comment]
@Mohammed-Luqman-Shareef, @abdul-hai-apisec - please let me know if these issues are updated?

**Comment by Mohammed-Luqman-Shareef** [comment]
@MuqeedA 

Pls add this below help text for the 'Customized Header' text fields on all pages

 Get:/api/users[Accept: application/json,Content-Type: application/json]
 
 *:/api/users[Key: Value] - Applied to all the methods on this endpoint
 :/api/users[Key: Value] - Applied to all the methods on this endpoint
 
 Post:/**[Key: Value] - Applied to Post method on all endpoints
 Post:[Key: Value] - Applied to Post method of on endpoints
 
 *:/**[Key: Value] - Applied to All methods on all endpoints

**Comment by SuddenDevelopment** [comment]
confirmed to work in prod :)

**Comment by Rahman-1234** [comment]
Verified in prod
