### ISSUE TITLE
[Bug]: Support UUID based ID's in Unsecured categories

### ISSUE THREAD

**Issue by intesar** [apisec-inc/Support#114]
### Severity

Medium

### What happened?

Checkout this call...
06:24:41 [D] [VSDIPAInvalid] : Endpoint [https://api-przedszkola.backendowo.com/v1/subscriptions/decline/12345]
06:24:41 [D] [VSDIPAInvalid] : Method ["POST"]
06:24:41 [D] [VSDIPAInvalid] : Authorization []
06:24:41 [D] [VSDIPAInvalid] : Request headers [[Accept:"application/json", Content-Type:"application/json"]]
06:24:41 [D] [VSDIPAInvalid] : Request []
06:24:41 [D] [VSDIPAInvalid] : Status code [400]
06:24:41 [D] [VSDIPAInvalid] : Response headers [[Date:"Fri, 12 Aug 2022 06:24:41 GMT", Content-Type:"application/json;charset=utf-8", Content-Length:"115", Connection:"keep-alive", Server:"Jetty(10.0.2)"]]
06:24:41 [D] [VSDIPAInvalid] : Response [{
  "error" : {
    "type" : "error/bad-request",
    "msg" : "error_bad-request",
    "schema" : {
      "id" : [ "should be string contains UUID" ]
    }
  }
}]
06:24:41 [D] [VSDIPAInvalid] : Response time [123]
06:24:41 [D] [VSDIPAInvalid] : Response size [115]
06:24:41 [E] [VSDIPAInvalid] : Assertion [@StatusCode == 401 OR @StatusCode == 403] resolved-to [400 == 401 OR 400 == 403] result [Failed]

--- checkout the endpoint definition in oas file ---
"/v1/subscriptions/decline/{id}" : {
      "post" : {
        "responses" : {
          "200" : {
            "schema" : {
              "type" : "object",
              "properties" : {
                "id" : {
                  "type" : "string",
                  "pattern" : "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
                },
                "created_at" : {
                  "type" : "integer",
                  "format" : "int64"
                },

**Comment by atef-aa** [comment]
@Mohammed-Luqman-Shareef - please have a developer check on this.

**Comment by Mohammed-Luqman-Shareef** [comment]
https://api-przedszkola.backendowo.com/v1/subscriptions/decline/12345
In this url the value 12345 was evaluated from the Variable.   I guess the endpoint in the playbook was /v1/subscriptions/decline/{{@Var.id}}
This is by design to replace the path params with @Var in the playbooks generated, so that the user can set the value from the UI page once and that gets reflected in all playbook executions.  And the variable would have a dummy value as 12345 by default initially when it got created.

If we have to pick / generate the values and put it in the playbooks instead of variables, then this functionality of @var would be lost.

**Comment by intesar** [comment]
@Mohammed-Luqman-Shareef add a sample UUID in the variable value if that is what is expected.

**Comment by Mohammed-Luqman-Shareef** [comment]
A random UUID is set to id params.

**Comment by muqeetkhan20** [comment]
@Mohammed-Luqman-Shareef looks good in dev.
**suggestion:** can we increase the column length; we have enough space in the table.
![image](https://user-images.githubusercontent.com/68276700/195527667-60db66f1-483c-43c4-8237-d153e1f41d80.png)

**Comment by atef-aa** [comment]
This ticket will be closed after evaluating functionality in prod. The UI changes will be moved to a separate ticket in by QA.

**Comment by muqeetkhan20** [comment]
@atef-aa UI changes moved; thanks
