### ISSUE TITLE
[Bug]: Why is this result marked as FP by the AI?

### ISSUE THREAD

**Issue by intesar** [apisec-inc/Support#115]
### Severity

Medium

### What happened?

05:40:45 [D] [AGAInvalid] : Endpoint [https://api.taxbit.com/staging/assets]
05:40:45 [D] [AGAInvalid] : Method ["GET"]
05:40:45 [D] [AGAInvalid] : Authorization []
05:40:45 [D] [AGAInvalid] : Request headers [[Accept:"application/json", Content-Type:"application/json"]]
05:40:45 [D] [AGAInvalid] : Request []
05:40:45 [D] [AGAInvalid] : Status code [200]
05:40:45 [D] [AGAInvalid] : Response headers [[Content-Type:"application/json", Content-Length:"1157", Connection:"keep-alive", Date:"Thu, 11 Aug 2022 17:40:45 GMT", x-amzn-RequestId:"7f0f090d-80c4-4850-be8e-c2a663bfeb12", Access-Control-Allow-Origin:"*", x-amz-apigw-id:"WtbMgF2koAMFcsQ=", X-Amzn-Trace-Id:"Root=1-62f53f1c-7e2cbe963e3f55bd16a9150f", X-Cache:"Miss from cloudfront", Via:"1.1 9c3701a40f5e4766165113d719972734.cloudfront.net (CloudFront)", X-Amz-Cf-Pop:"ARN1-C1", X-Amz-Cf-Id:"5_Qyo2tQ-hPER6wMf2Kq-4lk-zJaXTIqi344OXfl1Mvxa8tjNEq6Lg=="]]
05:40:45 [D] [AGAInvalid] : Response [[ {
  "uuid" : "e2a4ad9a-92c6-11e9-a5ee-0a290192900c",
  "code" : "BTC",
  "symbol" : "â¿",
  "name" : "Bitcoin",
  "type" : "Crypto",
  "decimal_places" : 8
}, {
  "uuid" : "e2a4af02-92c6-11e9-a5ee-0a290192900c",
  "code" : "ETH",
  "symbol" : "Î",
  "name" : "Ether",
  "type" : "Crypto",
  "decimal_places" : 18
}, {
  "uuid" : "e2a4adea-92c6-11e9-a5ee-0a290192900c",
  "code" : "LTC",
  "symbol" : "Å",
  "name" : "Litecoin",
  "type" : "Crypto",
  "decimal_places" : 8
}, {
  "uuid" : "e2a4ab9c-92c6-11e9-a5ee-0a290192900c",
  "code" : "XRP",
  "name" : "Ripple",
  "type" : "Crypto"
}, {
  "uuid" : "96bdd4aa-e605-11e9-a5ee-0a290192900c",
  "code" : "USDT",
  "name" : "Tether",
  "type" : "Crypto"
}, {
  "uuid" : "e2a4af5c-92c6-11e9-a5ee-0a290192900c",
  "code" : "BCH",
  "name" : "Bitcoin Cash",
  "type" : "Crypto",
  "decimal_places" : 8
}, {
  "uuid" : "92cc9fca-e605-11e9-a5ee-0a290192900c",
  "code" : "XTZ",
  "name" : "Tezos",
  "type" : "Crypto"
}, {
  "uuid" : "8de1d836-e605-11e9-a5ee-0a290192900c",
  "code" : "XLM",
  "name" : "Stellar",
  "type" : "Crypto"
}, {
  "uuid" : "89af4e9c-e605-11e9-a5ee-0a290192900c",
  "code" : "BNB",
  "name" : "Binance Coin",
  "type" : "Crypto"
}, {
  "uuid" : "872a145e-e605-11e9-a5ee-0a290192900c",
  "code" : "TRX",
  "name" : "TRON",
  "type" : "Crypto"
}, {
  "uuid" : "cee2471f-7679-49e2-b6a4-5be64da878a5",
  "code" : "TRX",
  "name" : "Tronix",
  "type" : "Crypto"
} ]]
05:40:45 [D] [AGAInvalid] : Response time [1182]
05:40:45 [D] [AGAInvalid] : Response size [1164]
05:40:45 [E] [AGAInvalid] : Assertion [@StatusCode == 401 OR @StatusCode == 403] resolved-to [200 == 401 OR 200 == 403] result [Failed]

**Comment by habeebvulla** [comment]
updated
