### ISSUE TITLE
[Bug]: Path variable from base URL not expanded

### ISSUE THREAD

**Issue by intesar** [apisec-inc/Support#117]
### Severity

Medium

### What happened?

06:32:24 [D] [DRGAInvalid] : Endpoint [https://sandbox-api.va.gov/services/veteran_verification/{version}/disability_rating]
06:32:24 [D] [DRGAInvalid] : Method ["GET"]
06:32:24 [D] [DRGAInvalid] : Authorization []
06:32:24 [D] [DRGAInvalid] : Request headers [[Accept:"application/json", Content-Type:"application/json"]]
06:32:24 [D] [DRGAInvalid] : Request []
06:32:24 [D] [DRGAInvalid] : Status code [500]
06:32:24 [D] [DRGAInvalid] : Response headers [[]]
06:32:24 [D] [DRGAInvalid] : Response [Not enough variable values available to expand 'version']
06:32:24 [D] [DRGAInvalid] : Response time [2]
06:32:24 [D] [DRGAInvalid] : Response size [56]
06:32:24 [E] [DRGAInvalid] : Assertion [@StatusCode == 401 OR @StatusCode == 403] resolved-to [500 == 401 OR 500 == 403] result [Failed]

3 other endpoints had the same issue....

06:32:24 [D] [DRGAInvalid] : Endpoint [https://sandbox-api.va.gov/services/veteran_verification/{version}/disability_rating]

06:32:24 [D] [SGAInvalid] : Endpoint [https://sandbox-api.va.gov/services/veteran_verification/{version}/status]

06:32:24 [D] [SHGAInvalid] : Endpoint [https://sandbox-api.va.gov/services/veteran_verification/{version}/service_history]

06:32:24 [D] [KGAInvalid] : Endpoint [https://sandbox-api.va.gov/services/veteran_verification/{version}/keys]

It seems the {version} is part of the base URL:
"servers" : [ {
    "url" : "https://sandbox-api.va.gov/services/veteran_verification/{version}",
    "description" : "Sandbox",
    "variables" : {
      "version" : {
        "default" : "v1"
      }
    }
  }, {
    "url" : "https://api.va.gov/services/veteran_verification/{version}",
    "description" : "Production",
    "variables" : {
      "version" : {
        "default" : "v1"
      }
    }
  } ],

Can we handle it?

**Comment by Mohammed-Luqman-Shareef** [comment]
@intesar Can you pls share the Spec.

**Comment by Mohammed-Luqman-Shareef** [comment]
Fixed. This variable will be replaced by {{@Random}}, since this path variable is not in the spec, there is no info on the type of the data and default value.

**Comment by muqeetkhan20** [comment]
@Mohammed-Luqman-Shareef can you provide us the spec to test? or should we close the ticket? unable to reproduce in NB.
