### ISSUE TITLE
[Bug]: Why is this marked FP by AI?

### ISSUE THREAD

**Issue by intesar** [apisec-inc/Support#118]
### Severity

Medium

### What happened?

03:27:04 [D] [AVTMUDAInvalid] : Endpoint [https://id.lexacom.com/api/v2/team/member/7617b912-ad13-45be-ad9e-70185677806a]
03:27:04 [D] [AVTMUDAInvalid] : Method ["DELETE"]
03:27:04 [D] [AVTMUDAInvalid] : Authorization []
03:27:04 [D] [AVTMUDAInvalid] : Request headers [[Accept:"application/json", Content-Type:"application/json"]]
03:27:04 [D] [AVTMUDAInvalid] : Request []
03:27:04 [D] [AVTMUDAInvalid] : Status code [500]
03:27:04 [D] [AVTMUDAInvalid] : Response headers [[Content-Type:"application/json", Date:"Mon, 08 Aug 2022 15:27:04 GMT", Server:"Microsoft-IIS/10.0", Cache-Control:"no-cache,no-store", Expires:"-1", Pragma:"no-cache", Set-Cookie:"ARRAffinity=3935d26f58841e3917f2e00f0df6da5c8b0d6cb2f1f0c9e9c490026921b7ee2e;Path=/;HttpOnly;Secure;Domain=id.lexacom.com", "ARRAffinitySameSite=3935d26f58841e3917f2e00f0df6da5c8b0d6cb2f1f0c9e9c490026921b7ee2e;Path=/;HttpOnly;SameSite=None;Secure;Domain=id.lexacom.com", Transfer-Encoding:"chunked", X-Powered-By:"ASP.NET"]]
03:27:04 [D] [AVTMUDAInvalid] : Response [{
  "ExceptionId" : "c7adb6b5-9674-4959-aba3-ff1299fbe5c0"
}]
03:27:04 [D] [AVTMUDAInvalid] : Response time [247]
03:27:04 [D] [AVTMUDAInvalid] : Response size [54]
03:27:04 [E] [AVTMUDAInvalid] : Assertion [@StatusCode == 401 OR @StatusCode == 403] resolved-to [500 == 401 OR 500 == 403] result [Failed]

---------------- 2nd one -------------
03:27:08 [D] [AVTMUAPAInvalid] : Endpoint [https://id.lexacom.com/api/v2/team/member/12345/12345]
03:27:08 [D] [AVTMUAPAInvalid] : Method ["PUT"]
03:27:08 [D] [AVTMUAPAInvalid] : Authorization []
03:27:08 [D] [AVTMUAPAInvalid] : Request headers [[Accept:"application/json", Content-Type:"application/json"]]
03:27:08 [D] [AVTMUAPAInvalid] : Request []
03:27:08 [D] [AVTMUAPAInvalid] : Status code [500]
03:27:08 [D] [AVTMUAPAInvalid] : Response headers [[Content-Type:"application/json", Date:"Mon, 08 Aug 2022 15:27:07 GMT", Server:"Microsoft-IIS/10.0", Cache-Control:"no-cache,no-store", Expires:"-1", Pragma:"no-cache", Set-Cookie:"ARRAffinity=3935d26f58841e3917f2e00f0df6da5c8b0d6cb2f1f0c9e9c490026921b7ee2e;Path=/;HttpOnly;Secure;Domain=id.lexacom.com", "ARRAffinitySameSite=3935d26f58841e3917f2e00f0df6da5c8b0d6cb2f1f0c9e9c490026921b7ee2e;Path=/;HttpOnly;SameSite=None;Secure;Domain=id.lexacom.com", Transfer-Encoding:"chunked", X-Powered-By:"ASP.NET"]]
03:27:08 [D] [AVTMUAPAInvalid] : Response [{
  "ExceptionId" : "2cb20d88-c151-4e37-a405-84943385dd3d"
}]
03:27:08 [D] [AVTMUAPAInvalid] : Response time [1221]
03:27:08 [D] [AVTMUAPAInvalid] : Response size [54]
03:27:08 [E] [AVTMUAPAInvalid] : Assertion [@StatusCode == 401 OR @StatusCode == 403] resolved-to [500 == 401 OR 500 == 403] result [Failed]

**Comment by habeebvulla** [comment]
similar status code 500
