### ISSUE TITLE
[Bug]: Home page, pagination 50/100 not working - just remove 50/100 the options

### ISSUE THREAD

**Issue by intesar** [apisec-inc/Support#119]
### Severity

Medium

### What happened?

It's just spinning. I guess it's a lot of data to show. It's better we just remove the 50/100 page size options from it.

**Comment by muqeetkhan20** [comment]
@intesar we have already raised this bug on @apisec-inc/engineering board.
https://github.com/apisec-inc/Engineering/issues/281

@MuqeedA please duplicate any one ticket.

**Comment by amer-apisec** [comment]
verified in prod, Working
