### ISSUE TITLE
[Bug]: Images missing in new Release Notes

### ISSUE THREAD

**Issue by intesar** [apisec-inc/Support#12]
### Severity

Non-Blocker

### What happened?

@muqeetkhan20

The new release notes are missing product images. Please migrate the old product images to the new site with an elegant look. Also, all new features in release notes should have product images.

Old release notes: https://apisec-inc.github.io/releases/
New release notes: https://apisec-inc.github.io/releases/

**Comment by intesar** [comment]
@muqeetkhan20 can you assign someone to work on this?

**Comment by muqeetkhan20** [comment]
@intesar screenshots uploaded for 2022 new features by @Rahman-1234 
Hence, closing this ticket
