### ISSUE TITLE
[Bug]: Scan details page sort by failed

### ISSUE THREAD

**Issue by intesar** [apisec-inc/Support#120]
### Severity

Medium

### What happened?

Order: failed, FP, and passed

**Comment by shamiulla-apisec** [comment]
Fixed the bug and checked in the code to repo. 
@muqeetkhan20 Please check and let us know if you find any issues with it.

**Comment by MaimoonaFatima** [comment]
@shamiulla-apisec We have found issues, let's discuss on the call.

**Comment by shamiulla-apisec** [comment]
> @shamiulla-apisec We have found issues, let's discuss on the call.

Sure
