### ISSUE TITLE
[Bug]: Handle invalid base URLs

### ISSUE THREAD

**Issue by intesar** [apisec-inc/Support#121]
### Severity

Medium

### What happened?

Can we validate base URLs? Detect invalid hosts, localhost, 127.0.0.1.

Here is a failed tests

02:18:44 [D] [IPGAInvalid] : Endpoint [http://host/invoices/12345]
02:18:44 [D] [IPGAInvalid] : Method ["GET"]
02:18:44 [D] [IPGAInvalid] : Authorization []
02:18:44 [D] [IPGAInvalid] : Request headers [[Accept:"application/json", Content-Type:"application/json"]]
02:18:44 [D] [IPGAInvalid] : Request []
02:18:44 [D] [IPGAInvalid] : Status code [500]
02:18:44 [D] [IPGAInvalid] : Response headers [[]]
02:18:44 [D] [IPGAInvalid] : Response [I/O error on GET request for "http://host/invoices/12345": host; nested exception is java.net.UnknownHostException: host]
02:18:44 [D] [IPGAInvalid] : Response time [1]
02:18:44 [D] [IPGAInvalid] : Response size [120]
02:18:44 [E] [IPGAInvalid] : Assertion [@StatusCode == 401 OR @StatusCode == 403] resolved-to [500 == 401 OR 500 == 403] result [Failed]

**Comment by MuqeedA** [comment]
URL validation added  on Env edit, project dashboard, and Playbook pages (on UI).
The same logic has to be implemented in backend code as well for the scheduled profiles.

**Comment by Rahman-1234** [comment]
@MuqeedA  did we implement the backend code?

**Comment by MuqeedA** [comment]
> @MuqeedA did we implement the backend code?

Not yet.

**Comment by Rahman-1234** [comment]
@Mohammed-Luqman-Shareef b 
removing QA tag since backend implementation is pending

**Comment by Abedeen1** [comment]
> @Mohammed-Luqman-Shareef b removing QA tag since backend implementation is pending

@Rahman-1234 , Could you please validate backend.

**Comment by Rahman-1234** [comment]
@Abedeen1 b,
base url validation is not working on creating new environment
though is working fine when we update existing environment

**Comment by Abedeen1** [comment]
@Rahman-1234 bhai,

Could you please validate now.

**Comment by Rahman-1234** [comment]
@intesar @Abedeen1 
It is working fine in dev environment 
will close the ticket once it is available in the prod

**Comment by Rahman-1234** [comment]
verified working in prod
