### ISSUE TITLE
[Bug]: Why is AI marking it FP

### ISSUE THREAD

**Issue by intesar** [apisec-inc/Support#122]
### Severity

Medium

### What happened?

11:10:12 [D] [ABVLCSGAInvalid] : Endpoint [https://www.olx.in/api/bxp/v3/listing-configurations/search?platform=12345&categoryId=12345&features=12345&lang=12345]
11:10:12 [D] [ABVLCSGAInvalid] : Method ["GET"]
11:10:12 [D] [ABVLCSGAInvalid] : Authorization []
11:10:12 [D] [ABVLCSGAInvalid] : Request headers [[Accept:"application/json", Content-Type:"application/json"]]
11:10:12 [D] [ABVLCSGAInvalid] : Request []
11:10:12 [D] [ABVLCSGAInvalid] : Status code [500]
11:10:12 [D] [ABVLCSGAInvalid] : Response headers [[]]
11:10:12 [D] [ABVLCSGAInvalid] : Response [I/O error on GET request for "https://www.olx.in/api/bxp/v3/listing-configurations/search": Read timed out; nested exception is java.net.SocketTimeoutException: Read timed out]
11:10:12 [D] [ABVLCSGAInvalid] : Response time [15050]
11:10:12 [D] [ABVLCSGAInvalid] : Response size [175]
11:10:12 [E] [ABVLCSGAInvalid] : Assertion [@StatusCode == 401 OR @StatusCode == 403] resolved-to [500 == 401 OR 500 == 403] result [Failed]

--------
11:09:41 [D] [ARRGAInvalid] : Endpoint [https://www.olx.in/api/relevance/recommendations?user=12345&ad_id=12345&category_id=12345&lang=12345]
11:09:41 [D] [ARRGAInvalid] : Method ["GET"]
11:09:41 [D] [ARRGAInvalid] : Authorization []
11:09:41 [D] [ARRGAInvalid] : Request headers [[Accept:"application/json", Content-Type:"application/json"]]
11:09:41 [D] [ARRGAInvalid] : Request []
11:09:41 [D] [ARRGAInvalid] : Status code [500]
11:09:41 [D] [ARRGAInvalid] : Response headers [[]]
11:09:41 [D] [ARRGAInvalid] : Response [I/O error on GET request for "https://www.olx.in/api/relevance/recommendations": Read timed out; nested exception is java.net.SocketTimeoutException: Read timed out]
11:09:41 [D] [ARRGAInvalid] : Response time [15032]
11:09:41 [D] [ARRGAInvalid] : Response size [164]
11:09:41 [E] [ARRGAInvalid] : Assertion [@StatusCode == 401 OR @StatusCode == 403] resolved-to [500 == 401 OR 500 == 403] result [Failed]

-------

11:10:09 [D] [AUMGAInvalid] : Endpoint [https://www.olx.in/api/users/120114317/meta?lang=12345]
11:10:09 [D] [AUMGAInvalid] : Method ["GET"]
11:10:09 [D] [AUMGAInvalid] : Authorization []
11:10:09 [D] [AUMGAInvalid] : Request headers [[Accept:"application/json", Content-Type:"application/json"]]
11:10:09 [D] [AUMGAInvalid] : Request []
11:10:09 [D] [AUMGAInvalid] : Status code [500]
11:10:09 [D] [AUMGAInvalid] : Response headers [[]]
11:10:09 [D] [AUMGAInvalid] : Response [I/O error on GET request for "https://www.olx.in/api/users/120114317/meta": Read timed out; nested exception is java.net.SocketTimeoutException: Read timed out]
11:10:09 [D] [AUMGAInvalid] : Response time [15101]
11:10:09 [D] [AUMGAInvalid] : Response size [159]
11:10:09 [E] [AUMGAInvalid] : Assertion [@StatusCode == 401 OR @StatusCode == 403] resolved-to [500 == 401 OR 500 == 403] result [Failed]

--------
11:09:57 [D] [GISGAInvalid] : Endpoint [https://www.olx.in/gsi/iframe/select?client_id=12345&ux_mode=12345&ui_mode=12345&as=12345&channel_id=12345&origin=12345]
11:09:57 [D] [GISGAInvalid] : Method ["GET"]
11:09:57 [D] [GISGAInvalid] : Authorization []
11:09:57 [D] [GISGAInvalid] : Request headers [[Accept:"application/json", Content-Type:"application/json"]]
11:09:57 [D] [GISGAInvalid] : Request []
11:09:57 [D] [GISGAInvalid] : Status code [500]
11:09:57 [D] [GISGAInvalid] : Response headers [[]]
11:09:57 [D] [GISGAInvalid] : Response [I/O error on GET request for "https://www.olx.in/gsi/iframe/select": Read timed out; nested exception is java.net.SocketTimeoutException: Read timed out]
11:09:57 [D] [GISGAInvalid] : Response time [15047]
11:09:57 [D] [GISGAInvalid] : Response size [152]
11:09:57 [E] [GISGAInvalid] : Assertion [@StatusCode == 401 OR @StatusCode == 403] resolved-to [500 == 401 OR 500 == 403] result [Failed]

---------

10:03:13 [D] [AVIPCPAInvalid] : Endpoint [https://dev.api.uhandisi.net/api/v2/instalment/payment/callback?tenant_id=12345]
10:03:13 [D] [AVIPCPAInvalid] : Method ["POST"]
10:03:13 [D] [AVIPCPAInvalid] : Authorization []
10:03:13 [D] [AVIPCPAInvalid] : Request headers [[Accept:"application/json", Content-Type:"application/json"]]
10:03:13 [D] [AVIPCPAInvalid] : Request [{ }]
10:03:13 [D] [AVIPCPAInvalid] : Status code [500]
10:03:13 [D] [AVIPCPAInvalid] : Response headers [[]]
10:03:13 [D] [AVIPCPAInvalid] : Response [I/O error on POST request for "https://dev.api.uhandisi.net/api/v2/instalment/payment/callback": Read timed out; nested exception is java.net.SocketTimeoutException: Read timed out]
10:03:13 [D] [AVIPCPAInvalid] : Response time [15073]
10:03:13 [D] [AVIPCPAInvalid] : Response size [180]
10:03:13 [E] [AVIPCPAInvalid] : Assertion [@StatusCode == 401 OR @StatusCode == 403] resolved-to [500 == 401 OR 500 == 403] result [Failed]

------------
10:03:00 [D] [AVBPCPAInvalid] : Endpoint [https://dev.api.uhandisi.net/api/v2/billing/payment/callback?tenant_id=12345]
10:03:00 [D] [AVBPCPAInvalid] : Method ["POST"]
10:03:00 [D] [AVBPCPAInvalid] : Authorization []
10:03:00 [D] [AVBPCPAInvalid] : Request headers [[Accept:"application/json", Content-Type:"application/json"]]
10:03:00 [D] [AVBPCPAInvalid] : Request [{ }]
10:03:00 [D] [AVBPCPAInvalid] : Status code [500]
10:03:00 [D] [AVBPCPAInvalid] : Response headers [[]]
10:03:00 [D] [AVBPCPAInvalid] : Response [I/O error on POST request for "https://dev.api.uhandisi.net/api/v2/billing/payment/callback": Read timed out; nested exception is java.net.SocketTimeoutException: Read timed out]
10:03:00 [D] [AVBPCPAInvalid] : Response time [15077]
10:03:00 [D] [AVBPCPAInvalid] : Response size [177]
10:03:00 [E] [AVBPCPAInvalid] : Assertion [@StatusCode == 401 OR @StatusCode == 403] resolved-to [500 == 401 OR 500 == 403] result [Failed]

**Comment by intesar** [comment]
03:19:35 [D] [AVSGAInvalid] : Endpoint [https://testing-api.conexoo.com/api/v1/states]
03:19:35 [D] [AVSGAInvalid] : Method ["GET"]
03:19:35 [D] [AVSGAInvalid] : Authorization []
03:19:35 [D] [AVSGAInvalid] : Request headers [[Accept:"application/json", Content-Type:"application/json"]]
03:19:35 [D] [AVSGAInvalid] : Request []
03:19:35 [D] [AVSGAInvalid] : Status code [200]
03:19:35 [D] [AVSGAInvalid] : Response headers [[Date:"Tue, 02 Aug 2022 15:19:35 GMT", Content-Type:"application/json", Transfer-Encoding:"chunked", Connection:"keep-alive", vary:"Accept-Encoding", Cache-Control:"no-cache", pragma:"no-cache", expires:"Tue, 02 Aug 2022 15:19:34 GMT", x-ratelimit-limit:"60", x-ratelimit-remaining:"52", access-control-allow-origin:"*", strict-transport-security:"max-age=15768000;", CF-Cache-Status:"DYNAMIC", Expect-CT:"max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"", Report-To:"{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=au4VKvItFxcEjurLefOxiXa2%2FNBUGXnqeQYxdC49vNiaho1g2CNeuoeYu45%2FYvwKRrySW6HwMBdb%2FnJ34iBCjRjIdQ4PxoL3Usc49o58G6TDe%2BElIsHh2yI4HYG088jZWBqdp0OGzBh9eQ%3D%3D"}],"group":"cf-nel","max_age":604800}", NEL:"{"success_fraction":0,"report_to":"cf-nel","max_age":604800}", Server:"cloudflare", CF-RAY:"7347cae42eedb791-AMS", alt-svc:"h3=":443"; ma=86400, h3-29=":443"; ma=86400"]]
03:19:35 [D] [AVSGAInvalid] : Response [{
  "success" : true,
  "message" : "messages.states",
  "data" : [ {
    "id" : 1,
    "name" : "Ghazni",
    "iso2" : null,
    "country_id" : 1,
    "created_at" : "2022-08-02T12:01:23.000000Z",
    "updated_at" : "2022-08-02T12:01:23.000000Z",
    "country" : {
      "id" : 1,
      "iso2" : "af",
      "iso3" : "afg",

**Comment by intesar** [comment]
03:19:56 [D] [AVOSPAInvalid] : Endpoint [https://testing-api.conexoo.com/api/v1/order/status]
03:19:56 [D] [AVOSPAInvalid] : Method ["PUT"]
03:19:56 [D] [AVOSPAInvalid] : Authorization []
03:19:56 [D] [AVOSPAInvalid] : Request headers [[Accept:"application/json", Content-Type:"application/json"]]
03:19:56 [D] [AVOSPAInvalid] : Request [{
  "status" : null,
  "url" : null,
  "comment" : null
}]
03:19:56 [D] [AVOSPAInvalid] : Status code [404]
03:19:56 [D] [AVOSPAInvalid] : Response headers [[Date:"Tue, 02 Aug 2022 15:19:56 GMT", Content-Type:"application/json", Transfer-Encoding:"chunked", Connection:"keep-alive", vary:"Accept-Encoding", Cache-Control:"no-cache, private", access-control-allow-origin:"*", strict-transport-security:"max-age=15768000;", CF-Cache-Status:"DYNAMIC", Expect-CT:"max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"", Report-To:"{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=5lM0DoQnJt7Op%2F8kj3MHPgKriaqDcgGbyfEJjNCsWQVEUaTTh028H2zjpjlysO4abw%2BO0NegdTvlrQ4nVDIKKTLNpZt8uD4c6l5V%2FQ1DkDOln%2FoES2Q1RIrZUF8JmhyeDscfv0sGNFtQnQ%3D%3D"}],"group":"cf-nel","max_age":604800}", NEL:"{"success_fraction":0,"report_to":"cf-nel","max_age":604800}", Server:"cloudflare", CF-RAY:"7347cb740c980100-AMS", alt-svc:"h3=":443"; ma=86400, h3-29=":443"; ma=86400"]]
03:19:56 [D] [AVOSPAInvalid] : Response [{
  "success" : false,
  "message" : ""
}]
03:19:56 [D] [AVOSPAInvalid] : Response time [149]
03:19:56 [D] [AVOSPAInvalid] : Response size [30]
03:19:56 [E] [AVOSPAInvalid] : Assertion [@StatusCode == 401 OR @StatusCode == 403] resolved-to [404 == 401 OR 404 == 403] result [Failed]

**Comment by intesar** [comment]
03:19:57 [D] [AVCGAInvalid] : Endpoint [https://testing-api.conexoo.com/api/v1/cities]
03:19:57 [D] [AVCGAInvalid] : Method ["GET"]
03:19:57 [D] [AVCGAInvalid] : Authorization []
03:19:57 [D] [AVCGAInvalid] : Request headers [[Accept:"application/json", Content-Type:"application/json"]]
03:19:57 [D] [AVCGAInvalid] : Request []
03:19:57 [D] [AVCGAInvalid] : Status code [500]
03:19:57 [D] [AVCGAInvalid] : Response headers [[]]
03:19:57 [D] [AVCGAInvalid] : Response [I/O error on GET request for "https://testing-api.conexoo.com/api/v1/cities": Read timed out; nested exception is java.net.SocketTimeoutException: Read timed out]
03:19:57 [D] [AVCGAInvalid] : Response time [15078]
03:19:57 [D] [AVCGAInvalid] : Response size [161]
03:19:57 [E] [AVCGAInvalid] : Assertion [@StatusCode == 401 OR @StatusCode == 403] resolved-to [500 == 401 OR 500 == 403] result [Failed]

**Comment by habeebvulla** [comment]
Please give me access to this project and share the link. I will look into it. Thank you

**Comment by habeebvulla** [comment]
status code 500 is not falls into AI category
