### ISSUE TITLE
[Bug]: Why did we generate a UUID in the path?

### ISSUE THREAD

**Issue by intesar** [apisec-inc/Support#124]
### Severity

Medium

### What happened?

03:19:44 [D] [AVLLIDAInvalid] : Endpoint [https://testing-api.conexoo.com/api/v1/language/96c9d477-aef4-46ab-bbfc-86611554a7de]
03:19:44 [D] [AVLLIDAInvalid] : Method ["DELETE"]
03:19:44 [D] [AVLLIDAInvalid] : Authorization []
03:19:44 [D] [AVLLIDAInvalid] : Request headers [[Accept:"application/json", Content-Type:"application/json"]]
03:19:44 [D] [AVLLIDAInvalid] : Request []
03:19:44 [D] [AVLLIDAInvalid] : Status code [500]
03:19:44 [D] [AVLLIDAInvalid] : Response headers [[Date:"Tue, 02 Aug 2022 15:19:44 GMT", Content-Type:"application/json", Transfer-Encoding:"chunked", Connection:"keep-alive", Cache-Control:"private, must-revalidate", x-ratelimit-limit:"60", x-ratelimit-remaining:"42", pragma:"no-cache", expires:"-1", access-control-allow-origin:"*", strict-transport-security:"max-age=15768000;", CF-Cache-Status:"DYNAMIC", Expect-CT:"max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"", Report-To:"{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=w5NTtkdpgieXof2%2BMW5za%2FBZD%2BRPOW7FUgmhxJ8w3edFdh%2F6ugdfclj5btz6ICe3qpNYlkeEO2%2BjjOcrzEiQYjCe5wY8VSLtIUmcb5qxeG5DPDVZ8nf0rflFwcXrlKpOgwBdSlSQtSOpRg%3D%3D"}],"group":"cf-nel","max_age":604800}", NEL:"{"success_fraction":0,"report_to":"cf-nel","max_age":604800}", Server:"cloudflare", CF-RAY:"7347cb23fefb1e75-AMS", alt-svc:"h3=":443"; ma=86400, h3-29=":443"; ma=86400"]]
03:19:44 [D] [AVLLIDAInvalid] : Response [{
  "message" : "SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type bigint: \"96c9d477-aef4-46ab-bbfc-86611554a7de\"\nCONTEXT:  unnamed portal parameter $1 = '...' (SQL: delete from \"languages\" where (\"id\" = 96c9d477-aef4-46ab-bbfc-86611554a7de))",
  "exception" : "Illuminate\\Database\\QueryException",

    "parameters" : {
      "locale" : {
        "name" : "locale",
        "in" : "query",
        "description" : "Field locale translations, select (es) Spanish, (en) English, (de) German, (pt) Portuguese, (fr) French",
        "required" : false,
        "schema" : {
          "type" : "string"
        },
        "examples" : {
          "en" : {
            "summary" : "English",
            "value" : "en"
          },
          "es" : {
            "summary" : "Spanish",
            "value" : "es"
          },
          "de" : {
            "summary" : "German",
            "value" : "de"
          },
          "pt" : {
            "summary" : "Portuguese",
            "value" : "pt"
          },
          "fr" : {
            "summary" : "French",
            "value" : "fr"
          }
        }
      },
      "per_page" : {
        "name" : "per_page",
        "in" : "query",
        "description" : "How many records you want to get per page",
        "required" : false,
        "schema" : {
          "type" : "integer"
        },
        "example" : "20"
      },

**Comment by Mohammed-Luqman-Shareef** [comment]
@intesar Can You pls share the Spec.

**Comment by atef-aa** [comment]
@Mohammed-Luqman-Shareef - I believe this is an existing functionality that we need to validate, please let me know otherwise.

**Comment by Mohammed-Luqman-Shareef** [comment]
Fixed it.  It will be replaced by a random value.
For delete endpoints IDs are not mapped to variables, because the variable value is used as common value for all the playbooks and if the same id is used in delete playbook, this value can't be used anymore.  To avoid this issue for Delete playbook variable is not mapped in the playbooks while generating them.

**Comment by Rahman-1234** [comment]
verified in prod
