### ISSUE TITLE
[Bug]: Postman Integration Issues

### ISSUE THREAD

**Issue by intesar** [apisec-inc/Support#125]
### Severity

Medium

### What happened?

- [x] Show total Collections found on the top
- [ ] How does the scale works? Will it handle 1000 collections?
- [x] #132

**Comment by atef-aa** [comment]
@Abedeen1 - please look into this ticket.

**Comment by Abedeen1** [comment]
@Mohammed-Luqman-Shareef Sir,

Could you please provide directions on " Collections can have the same name across other workspaces. Registering a collection from one workspace disables selecting the same name collection from other workspaces"

**Comment by Mohammed-Luqman-Shareef** [comment]
@Abedeen1 As discussed in the call today, while registering the API prefix the workspace name to differentiate.  Take couple of Postman collections with similar api names in different workspaces.  If you dont get any such example already, you can edit the collection and rename the APIs to reproduce the scenario.

@atef-aa can you pls help get Postman collections with such scenario.

**Comment by Abedeen1** [comment]
> @Abedeen1 As discussed in the call today, while registering the API prefix the workspace name to differentiate. Take couple of Postman collections with similar api names in different workspaces. If you dont get any such example already, you can edit the collection and rename the APIs to reproduce the scenario.
> 
> @atef-aa can you pls help get Postman collections with such scenario.

@Mohammed-Luqman-Shareef Sir,

Changes implemented as mentioned above.

**Comment by MaimoonaFatima** [comment]
verified in dev, working fine

**Comment by atef-aa** [comment]
@AkaramAli - what about the scale scenario in the description.. Has it been validated for 1000 collections?

**Comment by AkaramAli** [comment]
@atef-aa , There is another ticket on similar lines https://github.com/apisec-inc/QR/issues/15.
Regarding scaling - We tested the performance for 100 + APIs/Collections  it takes ~ 2 seconds .

**Comment by atef-aa** [comment]
Great, thanks for the update @AkaramAli!
