### ISSUE TITLE
[Bug]: ADoS didn't pick this param

### ISSUE THREAD

**Issue by intesar** [apisec-inc/Support#127]
### Severity

Medium

### What happened?

"/api/v1/roles" : {
      "get" : {
        "parameters" : [ {
          "description" : "Number of results to return",
          "in" : "query",
          "name" : "$limit",
          "required" : false,
          "schema" : {
            "type" : "integer"
          }
        }

- [ ] $limit
- [ ] numberOfResults
- [ ] max
- [ ] maxMessages (Starting max or limit or size should be considered Iguress)

**Comment by atef-aa** [comment]
@Mohammed-Luqman-Shareef - Please assign this to a developer to investigate

**Comment by Mohammed-Luqman-Shareef** [comment]
Added these fields for ADoS.

A new AI module will be developed to identify the ADoS parameters.
