### ISSUE TITLE
[Bug]: Project lists - provide more space for the name column

### ISSUE THREAD

**Issue by intesar** [apisec-inc/Support#128]
### Severity

Medium

### What happened?

Checkout the screenshots

<img width="1409" alt="Screen Shot 2022-08-15 at 3 30 34 PM" src="https://user-images.githubusercontent.com/990419/184731998-7723afac-71eb-4aea-ac6f-bff11a923ad7.png">

**Comment by atef-aa** [comment]
@MuqeedA - Assigning this ticket to you.

**Comment by shahidabdul** [comment]
![image](https://user-images.githubusercontent.com/87168421/185043639-dbb1f9e8-72b4-4176-8e75-c50a5519a131.png)

**Comment by Rahman-1234** [comment]
Verified in dev, API name has enough space

**Comment by muqeetkhan20** [comment]
@shahidabdul 
closing ticket
We can go for another iteration, space can be still reduced after owner name. 
![image](https://user-images.githubusercontent.com/68276700/186404851-1c028890-6f01-4967-b3ec-6470695e05db.png)

**Comment by atef-aa** [comment]
While reducing the space between Owners and Created Date columns, we need to consider people who have long names. Maybe a little be of space reduction but not a lot.
