### ISSUE TITLE
[Bug]: Long variable value not able to be saved

### ISSUE THREAD

**Issue by dave-apisec** [apisec-inc/Support#129]
### Severity

Blocker

### What happened?

Working on a project where a long encoded value needs to be inserted into the path.

I ran into this issue when modifying "Variables" as well as when adding it to a path directly in "Payloads" product areas.

Reproduction steps:
1. Navigate to an API Project, to the Configurations > Environments > Variables area
2. Create a new variable and provide a valid "Name".
3. Provide this as the variable value: `ss56791e26d54f9ba64e867c0539e6fe:oxJPZm6wv1Wmm1_EMQAfBRSbHaPCu2WXbZmz495cwmaGDH3L-4a7sGriDNVAendFM2Z7jszns1pLwbONbMN_ibyRd2qks7tIJklutKxmQbjOnroHiJrQJQJweo2iCfRyL_Hny9GTax5eHFEi503fLUTjGYzV8SC8qP3eJ3z-XDjaPW6A82xZN_n4B_VoDpJaY4CH694vawkG7FbpYvI6IFJ5jDyv-OnDWLooYEwoVZc32nZiTmy3JTrZENIJfQFZtjOzAZm-kDjTXWXcVUKsHRI4z37iJRBEA6dOUzK27K71p1bsPppohNSSzQ816lkJAmUuiCKBM8VB1svbrJbHUQ`
4. Select either "Scope" (it doesn't matter)
5. Click "Create" 

This is the error message I get: 
![Untitled](https://user-images.githubusercontent.com/104801249/185257402-bc1c9e35-ad56-4b40-80f4-1ef3e4d4a8ce.png)

Feel free to reach out for any additional info. Thanks!

**Comment by dave-apisec** [comment]
cc: @intesar

**Comment by atef-aa** [comment]
@Mohammed-Luqman-Shareef:  The number of characters Dave used above is 375.  We can make it 512, or we can increase it more.  Please assign this to a developer.

The following needs to be update:
- The field length on the UI
- Validate the field-size that it is getting updated in the backend
- The wording for the error message needs to be improved. 
   - Actual: Resource name or key already exists.
   - Expected: The maximum length for this field is 512 (for example, or whatever num we're setting it to).

**Comment by AkaramAli** [comment]
Environment -> Variable -> value field length increased and we are able to save the string provided in the ticket . Backend changes pushed and available in dev .
@Mohammed-Luqman-Shareef  - Could you assign some one from UI team to take care of UI changes .

![image](https://user-images.githubusercontent.com/89961027/185907032-b9d4b9b3-aa50-401b-a434-cf96b0b65be8.png)

**Comment by atef-aa** [comment]
The value should be displayed in a single line and with whatever characters can be fit, and end it with ellipses (3 dots). There should be an at least 2 spaces before the Scope and ellipses.  Please let me know if you have questions.

**Comment by shamiulla-apisec** [comment]
@atef-aa :
When the column is accommodated with 25 characters then it looks like below:

<img width="755" alt="image" src="https://user-images.githubusercontent.com/87168081/186078212-df873f54-5b67-4f11-89d8-c899b2dd6314.png">

When the column is accommodated with 5 characters to maintain the consistency with other values of the same column then it looks like below:

<img width="770" alt="image" src="https://user-images.githubusercontent.com/87168081/186078535-953ad497-0646-4f91-b6b1-6b4c9d904953.png">

**Comment by muqeetkhan20** [comment]
trimming is also fixed, but it will be available in prod in next refresh.
closing this ticket

**Comment by shamiulla-apisec** [comment]
@muqeetkhan20 : As requested to increase the text to accommodate the empty space so improved its visibility from 5 characters to 25 characters.
