### ISSUE TITLE
[Bug]: Invalid Assertion Error

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#130]
### Severity

Medium

### What happened?

The following syntax throws an error when the condition appears first:
@ResponseHeaders.Access-Control-Allow-Credentials !=~ (vulnerable)
![image](https://user-images.githubusercontent.com/47815523/185389212-182cea9b-7280-46a0-a81a-ccb8e48aa5bb.png)

Due to the invalid assertion error, all playbooks are failing and resulting in increased vulnerabilities that are false positives.

However, the same works fine when it appears as a secondary condition:
@ResponseHeaders.Access-Control-Allow-Credentials == NULL OR @ResponseHeaders.Access-Control-Allow-Credentials !=~ (vulnerable)
![image](https://user-images.githubusercontent.com/47815523/185390089-e58423a0-4abe-4ad1-a5fe-4b27459b8388.png)

Steps to reproduce:
1. Activate & Execute CORS Config Regex Reflection category in the NetBanking API
2. Observe the invalid assertion error as mentioned above
3. Replace the existing assertion with the following in any playbook:
- '@ResponseHeaders.Access-Control-Allow-Credentials == NULL OR @ResponseHeaders.Access-Control-Allow-Credentials !=~ (vulnerable)'
- Execute the playbook, and observe that the assertion is accepted, and the Invalid assertion error is no longer displayed.

**Comment by Rahman-1234** [comment]
verified in prod
