### ISSUE TITLE
[Bug]: Playbooks not being generated for the given OAS URL

### ISSUE THREAD

**Issue by intesar** [apisec-inc/Support#131]
### Severity

Medium

### What happened?

Here is the API
https://bpsapi.addon.com.np/v2/api-docs

<img width="1524" alt="Screen Shot 2022-08-19 at 9 13 43 AM" src="https://user-images.githubusercontent.com/990419/185662100-773405b7-b850-4c31-96bd-98ac88609959.png">

**Comment by atef-aa** [comment]
@SyedsImran - Please check the logs for this.  I ran the URL in the browser and did return the swagger API.

**Comment by abdul-hai-apisec** [comment]
@Mohammed-Luqman-Shareef - Its a huge spec with 25k lines, We are getting Out-of-Memory error while generating playbooks, specifically while formatting the JSON to String.
![image](https://user-images.githubusercontent.com/83706991/186128788-7e05b997-29f6-47a5-8518-bc692171a4cd.png)

**Comment by atef-aa** [comment]
@abdul-hai-apisec Thanks for the update. This will close and go in the backlog for now.
