### ISSUE TITLE
[Bug]: Restrict users from running a scan on an offline scanner

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#133]
### Severity

Medium

### What happened?

Restrict users from running a scan on an offline scanner to avoid time-out errors.
![image](https://user-images.githubusercontent.com/47815523/187058325-3a51a39c-b013-4700-94f4-eca6c74237a8.png)

Current Behavior:
![image](https://user-images.githubusercontent.com/47815523/187058256-6161fc26-41ce-4665-8a21-37605a89bd71.png)

Expected Behavior:
The Submit button should be disabled to avoid running scans resulting in scan time-out.

**Comment by Rahman-1234** [comment]
verified working in prod
