### ISSUE TITLE
[Bug]: Invalid Assertion evaluation for 'null'

### ISSUE THREAD

**Issue by SuddenDevelopment** [apisec-inc/Support#134]
### Severity

Blocker

### What happened?

Project = SecurityCategories

corsNullOrigin_dail endpoint should fail against cors Config Null Origin category

see the assertion eval
Assertion [@ResponseHeaders.Access-Control-Allow-Origin != null] resolved-to [null != null] result [Passed]

**Updated: August 31**

Here are some more examples of @Empty and @Null issues

03:25:43 [I] [   AAPSDE2] : Assertion [@Response.$..ssn == @Empty] resolved-to [null == @Empty] result [Passed]
03:25:43 [I] [   AAPSDE2] : Assertion [@Response.$..email == @Empty] resolved-to [null == @Empty] result [Passed]
03:25:43 [I] [   AAPSDE2] : Assertion [@Response.$..long == @Empty] resolved-to [null == @Empty] result [Passed]
03:25:43 [I] [   AAPSDE2] : Assertion [@Response.$..mobile == @Empty] resolved-to [null == @Empty] result [Passed]
03:25:43 [E] [   AAPSDE2] : Invalid assertion [@Response.$..coordinates== @Empty] errors [{}]. e.g. valid [<Operand1> <Operation> <Operand2>] i.e. @Request.name == @Response.name
03:25:43 [I] [   AAPSDE2] : Assertion [@Response.$..lat == @Empty] resolved-to [null == @Empty] result [Passed]
03:25:43 [I] [   AAPSDE2] : Assertion [@Response.$..telephone == @Empty] resolved-to [null == @Empty] result [Passed]
03:25:43 [I] [   AAPSDE2] : Assertion [@Response.$..phone == @Empty] resolved-to [null == @Empty] result [Passed]

**Comment by SuddenDevelopment** [comment]
it's confusing the null type with null string

**Comment by Mohammed-Luqman-Shareef** [comment]
I'm looking into it.

**Comment by Mohammed-Luqman-Shareef** [comment]
Fixed.  Can be tested by creating a new scanner.  All the scanners will be refreshed with latest code with next regular prod refresh.

**Comment by atef-aa** [comment]
Added @Empty and @Null issues with examples in the description.

**Comment by SuddenDevelopment** [comment]
verified in prod thank you
