### ISSUE TITLE
[Bug]: Invalid Assertion for Regex match

### ISSUE THREAD

**Issue by SuddenDevelopment** [apisec-inc/Support#135]
### Severity

Blocker

### What happened?

project = Security Categories

category = cors Config regex reflection

@ResponseHeaders.Access-Control-Allow-Origin !=~ (vulnerable) should fail on the regexReflection_fail endpoint

it's not matching regex (vulnerable) to `vulnerable.something.com`

happy to walk someone through it, we have a good way to test it

**Comment by Mohammed-Luqman-Shareef** [comment]
@SuddenDevelopment Lets discuss over a call. You can walk me through it.

**Comment by SuddenDevelopment** [comment]
resolved: It was not evaluating as true for a partial match.

need to make it a complete match to eval as true: (.*)(searchforme)(.*)
