### ISSUE TITLE
[Bug]: Multiple reports sent on triggering a scan

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#136]
### Severity

Blocker

### What happened?

A client has reported receiving multiple reports when triggering a scan via Jenkins Integration.
I tried creating a new project and verified the issue is reproducible in the newly created project.

![image](https://user-images.githubusercontent.com/47815523/187345402-9f468bf6-dd6c-4fe3-9efc-d154c40df6ec.png)

Emailed all the details to @Mohammed-Luqman-Shareef 

Steps to reproduce:
1. Log into the customer tenant
2. Navigate to configurations, Integrations, CI/CD
3. Run the shell script 

Expected Behavior:
1. Only a single report should be emailed at the end of the scan

Current Behavior:
1. Multiple reports are sent to the client that is spamming the Inbox of the entire team.

**Comment by fersy02** [comment]
@atef-aa - Appreciate it if you have any updates on this ticket.

**Comment by abdul-hai-apisec** [comment]
@fersy02 - We are analyzing the issue, and trying to reproduce the same in the development environment.

**Comment by fersy02** [comment]
Thanks for the update @abdul-hai-apisec 

Since the issue is specific to this tenant and not reproducible in other tenants of Prod, it might not be reproducible in Dev too. In fact, when I first registered the new project, this issue was not reproducible. It could be the configurations that are resulting in sending multiple emails. Let us know if you need any help in debugging the issue.

**Comment by fersy02** [comment]
@Mohammed-Luqman-Shareef @abdul-hai-apisec 
Any updates on this ticket?
The client is chasing us for an immediate resolution. Please prioritize it.

**Comment by abdul-hai-apisec** [comment]
The fix did not resolve this issue yet. We are continuously working on it but as there are no  errors in the logs and also the issue is not reproducible in any other organization/environment. We have to wait till the prod refresh to validate if our fix works.

@fersy02, Is it possible to clone this on our development environment to reduce the validation cycle.

**Comment by fersy02** [comment]
@abdul-hai-apisec, let's give it a try. 
@Afra-APIsec will send you the details required to register and configure the project.

**Comment by Afra-APIsec** [comment]
@fersy02 @abdul-hai-apisec -Sure, Sending the details via email.

**Comment by atef-aa** [comment]
This is being worked on and under investigation.

**Comment by abdul-hai-apisec** [comment]
The issue is now resolved in production. Only one email report is triggered now after running the scan.
![image](https://user-images.githubusercontent.com/83706991/192962425-b2e7d3b7-4d53-452b-8fbd-6125dda26838.png)

**Comment by muqeetkhan20** [comment]
@fersy02 can you please confirm? we have to close the ticket.

**Comment by fersy02** [comment]
@muqeetkhan20, I have invoked a scan, requested a summary report, and received it only once. However, as requested in the consecutive scan, I haven't received a pen-test report. I will retry and update the ticket shortly.

**Comment by fersy02** [comment]
Closing this ticket as we are now receiving a single report.
