### ISSUE TITLE
[Bug]: Jenkins Script fails for a Project name with empty spaces

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#137]
### Severity

Medium

### What happened?

Jenkins script is auto-generated and displays the project name without double quotes. A client has reported the following error:
{"requestId":"None","requestTime":"2022-08-30T03:59:41.352+0000","errors":true,"messages":[{"type":"ERROR","key":null,"value":"Scan not found"}],"data":null,"totalPages":0,"totalElements":0}

When I realized the project name had spaces, I enclosed the project name in double quotes and recommended the same to the client. To avoid such errors in the future, please generate the project name with double quotes in the Jenkins script or at least add a note in the help text.

![image](https://user-images.githubusercontent.com/47815523/187347748-9c174789-8ffc-4ddb-b32c-bd9a08bbd0d5.png)

**Comment by AkaramAli** [comment]
I am looking into it .

**Comment by AkaramAli** [comment]
@fersy02  - Documentation updated and changes pushed  . Should be available in next prod refresh .

cc @MuqeedA

**Comment by asifadn9** [comment]
Verified in dev and Prod, working fine.
