### ISSUE TITLE
[Bug]: Service Unavailable Error Upon User Login

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#139]
### Severity

Blocker

### What happened?

One of our clients has reported that he cannot log into the tenant with his existing credentials and receiving a **Service Unavailable** error. 
![image](https://user-images.githubusercontent.com/47815523/187831157-c3f4609d-fbe7-43fc-b8bd-57401c8636a8.png)

The User status is active. 
![image](https://user-images.githubusercontent.com/47815523/187832136-76ae019c-5966-4f59-857c-6389236b0eb7.png)

Troubleshooting Steps:
1. Tried disabling and reenabling the user and 
2. Reset the password 

The client is still facing the same error. Please look into this on priority. 

Steps to reproduce: 
1. Visit https://cloud.fxlabs.io/#/login
2. Enter the username as mentioned in the email
3. Enter a junk password

Expected Result: Invalid username/password

Actual Result: Service Unavailable.

The issue is reproducible using the Google Chrome browser.

Details available with @Mohammed-Luqman-Shareef

**Comment by Mohammed-Luqman-Shareef** [comment]
There are two users in this org with the same email, one with all lower case and another one with camel case.
We will restrict creating multiple users with the same email in the system.  
For now, we need to disable one of them to make the other work.  

![image](https://user-images.githubusercontent.com/87166065/187845947-e8285fb1-e66b-4998-9b17-32fe75e07878.png)
![image](https://user-images.githubusercontent.com/87166065/187846012-f7f6c2d5-abe1-4321-b439-1f8c6fa3a7b3.png)

**Comment by fersy02** [comment]
Thanks for the update @Mohammed-Luqman-Shareef. I have deactivated the duplicate user account and still facing the same issue.

**Comment by Mohammed-Luqman-Shareef** [comment]
@fersy02 You can close this ticket now.

**Comment by fersy02** [comment]
Published a write-up in the troubleshooting section.
https://docs.apisec.ai/UserLoginServiceUnavailable.md
