### ISSUE TITLE
[Bug]: Restrict users from creating a user account with an existing email

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#140]
### Severity

Blocker

### What happened?

Currently, the email and organization name used to log into APIsec are case-sensitive. This behavior allows the creation of users with an existing email, provided the case is different. We recently encountered a Service Unavailable error on the login screen where a duplicate email exists.

Please ensure unique email addresses are accepted for account creation to prevent users from getting blocked from accessing their accounts.

Steps to reproduce:

1. Log into APIsec
2. Create a user account with an email such as feroz@apisec.ai
3. Once the user is created successfully, create another user account with the same email, but with a different case e.g., FEROZ@apisec.ai

Expected Result:
Display an error: Email already exists

Actual Result:
User is created successfully

**Comment by MaimoonaFatima** [comment]
Verified in dev, working fine.
