### ISSUE TITLE
IQT Review

### ISSUE THREAD

**Issue by atef-aa** [apisec-inc/Support#141]
Please review the items assigned to you and plan accordingly. Please let me know if you have any questions.

- [x] IQT needs to make sure the APIsec production installation was successful. They're planning to do their testing. I don't recommend that approach, instead, we provide them with a short sanity test guide and publish it in the knowledgebase section here [https://docs.apisec.ai/.](https://mailtrack.io/trace/link/2c14eae0627508853c403cc99161de9da0d46637?url=https%3A%2F%2Fdocs.apisec.ai%2F.&userId=3447470&signature=ea2bd823db93546e) Skip all the integration and focus on API registration, deploying scanner, scanning categories, setting credentials, FP, and vulnerabilities. [@Muqeet Khan](mailto:muqeet@apisec.ai) can you deliver this early next week? Max two pages are required.
- [x] Push NetBanking container to the Docker on-premises. Create a simple deployment instruction guide for IQT to follow and run NetBanking. Publish the guide in the Docs. [@Syed Imran](mailto:syedimran@apisec.ai) can you deliver this?

**Comment by SyedsImran** [comment]
Netbanking Application to be deployed in docker-swarm cluster is ready.

https://github.com/apisec-inc/On-Prem/tree/main/Netbanking

**Comment by SyedsImran** [comment]
Added Netbanking installation guide to docs repo.
https://github.com/apisec-inc/documentation/blob/main/docs/Netbanking.md

**Comment by muqeetkhan20** [comment]
@intesar @atef-aa here we go with the short test guide. 
https://docs.apisec.ai/Testguide/
