### ISSUE TITLE
[Bug]: Missing Assertions in the Wire logs of Developer Report

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#142]
### Severity

Blocker

### What happened?

A client has reported that the Developer report shared with their development teams to fix the vulnerabilities does not include assertions to set the expectations.
![image](https://user-images.githubusercontent.com/47815523/188352697-a22e4600-d3ab-4abc-b8a6-6af769800247.png)

This client cannot onboard all thousands of developers in APIsec to review the vulnerabilities, and they rely on the pdf reports. It is currently blocking them from sharing the details effectively. 

**Steps to reproduce**:
1. Log into APIsec
2. Click a project with open vulnerabilities
3. Navigate to Reports
4. Click **Email Report** and select Developer Report (pdf) to receive the report via email

**Expected Result**:
The Developer Report must contain wire logs with assertion details.

**Actual Result**:
Assertions are missing from the wire logs. Attached is a sample Netbanking Developer Report
[API_Developer_Report_APIsec_NBDemoForMIT_09052022.pdf](https://github.com/apisec-inc/Support/files/9486406/API_Developer_Report_APIsec_NBDemoForMIT_09052022.pdf)

**Comment by asifadn9** [comment]
Verified in dev , working fine.

**Comment by MaimoonaFatima** [comment]
verified in prod.
