### ISSUE TITLE
[Bug]: POST Migration Unable to login to APIsec via OKTA SSO 

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#144]
### Severity

Blocker

### What happened?

One of our clients who enabled OKTA SSO is experiencing login issues and cannot access their accounts.

@abdul-hai-apisec, please recommend how to unblock them.

**Comment by abdul-hai-apisec** [comment]
I have already raised a request with OKTA to update our production url.
_**Okta has received your support request! Case Number 01499266. ref:_00DA0KWYD._5004z1fvKOW:ref**_

Till the issue is resolved, you can provide them with guest user credentials to login to there organization.

**Comment by fersy02** [comment]
Thanks for the update @abdul-hai-apisec. We have already shared a couple of Service Accounts.

Is there an ETA from OKTA for updating the URL?

**Comment by abdul-hai-apisec** [comment]
@fersy02, We are following up closely with the OKTA support team, and they have notified the application team to expedite the request. We have not received any ETA yet. I will keep you posted as soon as i have more information.

**Comment by abdul-hai-apisec** [comment]
@fersy02, OKTA has published our APIsec app with the latest URL, Please check and let me know if the customers are still facing the issue.

_**The endpoints have been updated automatically for all application instances in Okta. Customers don’t need to make any actions.**_

**Comment by fersy02** [comment]
Thanks @abdul-hai-apisec 

I received confirmation that everything is working fine now.
