### ISSUE TITLE
[Bug]: Unable to refer header values in the path

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#145]
### Severity

Medium

### What happened?

One of the prospects API requires HMAC authentication in the query parameters:

![image](https://user-images.githubusercontent.com/47815523/188932758-0932f573-2d03-4339-ba0e-a6ee0996b6e5.png)

The script fails to compute and substitute the header values in the query parameters but works well in the request body:
![image](https://user-images.githubusercontent.com/47815523/188933998-dacae212-850b-450f-a0b6-d190c718a52c.png)

There must be a way to customize the sequence to support such a scenario.

**Comment by Mohammed-Luqman-Shareef** [comment]
Fixed

**Comment by muqeetkhan20** [comment]
@Mohammed-Luqman-Shareef could you please share the specs? Unable to reproduce in NB app.

@fersy02 if your team have tested this already; we can close this bug...

**Comment by fersy02** [comment]
We have already shipped this to the client.
