### ISSUE TITLE
[Bug]: Playbooks fail to generate with schema references to files & URLs

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#146]
### Severity

Medium

### What happened?

OpenAPI Specification containing references of files or URLs fails to discover endpoints. As a result, playbooks fail to generate.
If the schema contains references to external files or URLs, this shall be ignored, and the playbook generation should complete.

Shared the OAS with @Mohammed-Luqman-Shareef to reproduce this issue.

**Comment by zafar0506** [comment]
@fersy02  Could you please provide OpenAPI Specification containing references of files or URLs.

**Comment by fersy02** [comment]
@zafar0506, I have already shared the details with @Mohammed-Luqman-Shareef,  as stated in the description above.
Forwarding the email to you right away.

**Comment by fersy02** [comment]
Verified and shipped to the client.
