### ISSUE TITLE
[Bug]: All Scanners go offline frequently 

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#147]
### Severity

Blocker

### What happened?

We have been experiencing this issue or reported by the clients that all scanners stop working. The last time it happened was on Sep 07, 2022 around 12:00 PM(noon) IST.

Please investigate and add a story to rectify the problem and make them resilient to auto-recover.

**Comment by atef-aa** [comment]
@SyedsImran - please check what's causing this.

**Comment by atef-aa** [comment]
@fersy02 - Since opening this ticket, did we experience any more scanners going down?  How many clients have reported this? 

@SyedsImran - were you able to identify the reason for these going down?  These scanners shouldn't be going down and have the capability to reconnect themselves.

**Comment by fersy02** [comment]
Yes, we experienced the issue on September 12. @Abid60 was supposed to send an email and update this ticket.

**Comment by Afra-APIsec** [comment]
Experienced the issue once again at 3 pm. The scanners turned to Stop State.

**Comment by SyedsImran** [comment]
We have collaborated with engineering team yesterday, some of the scanners may be failing because of load on them.
So deployed the scanners with multiple replicas on heavily used scanners (Super1, Super2 & Super3).
We will observe they behaviour and if this fixes the issue, we  will implement the same for others as well.

**Comment by atef-aa** [comment]
@SyedsImran - Have you noticed any behavior on the scanners?

**Comment by Abid60** [comment]
Experienced the issue once again at 9 pm. The scanners turned to Stop State.

**Comment by intesar** [comment]
If we're not seeing this issue any more please close the ticket. @Abid60 @fersy02

**Comment by fersy02** [comment]
Let's monitor for 1 more week as we experienced timeout issues even with the Global Scanners.

**Comment by Abid60** [comment]
Scanners are not responsive

**Comment by atef-aa** [comment]
Scanners were back online.

**Comment by Afra-APIsec** [comment]
Scanners went down for 2 minutes, they are running now
