### ISSUE TITLE
[Bug]: Base URL *must* be a .com variation

### ISSUE THREAD

**Issue by Fl3xappeal** [apisec-inc/Support#149]
### Severity

Blocker

### What happened?

I have a valid base url that does not end in a .com, .org, .etc . I am unable to configure APISec scans because "invalid base URL" even though Postman/cURL works. 

My URL is something like http://example01:8080/<Swagger Endpoints here> . There is no .com.

**Comment by atef-aa** [comment]
@abdul-hai-apisec - please look into this.

**Comment by atef-aa** [comment]
@Fl3xappeal - On which application are you trying this, ethicalcheck.dev or cloud.apisec.ai?

**Comment by Fl3xappeal** [comment]
Cloud.apisec.ai

**Comment by atef-aa** [comment]
Okay. Also, can you please provide the exact URL?

**Comment by Fl3xappeal** [comment]
What is email so I can send screenshot and URL details? (I have already emailed to Feroz). 

I would rather not post publicly. 

The URL essentially is http://myhost:1337/ 

Interacting with it via cURL/Postman is http://myhost:1337/api/DoThis or http://myhost:1337/api/OrDoThis

**Comment by fersy02** [comment]
I've shared Screenshots with the Engineering team.

**Comment by atef-aa** [comment]
Update: these changes are being worked on, and soon will update this ticket once ready.

**Comment by MuqeedA** [comment]
Changes pushed to Prod.

**Comment by atef-aa** [comment]
@fersy02 - Is this okay to close?

**Comment by fersy02** [comment]
@atef-aa - It looks good to me, but I requested the client to confirm before we close this ticket.

**Comment by fersy02** [comment]
@atef-aa - I just received a confirmation that we are good to close.
