### ISSUE TITLE
[Bug]: Project registered with no endpoints

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#15]
### Severity

Blocker

### What happened?

Tried registering a project and found the following error in the activity logs:
Spec parsing error: java.lang.NullPointerException

The OAS shows no errors in the editor.swagger.io
[openapi.zip](https://github.com/apisec-inc/Support/files/8247413/openapi.zip)

**Comment by Abdullah-Akbar** [comment]
This is fixed.  We have 170 endpoints with 2029 playbooks now. Tested in dev environment.
![image](https://user-images.githubusercontent.com/89911730/158250016-dc2e9f75-fd01-4e12-9712-e816698b2581.png)
