### ISSUE TITLE
[Bug]: JIRA Integration fails to file vulnerabilities

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#150]
### Severity

Blocker

### What happened?

One of our clients has reported that upon sync vulnerabilities task, they get the following error:
![image](https://user-images.githubusercontent.com/47815523/189716530-30361ba4-7be4-4cbc-8e94-b18fa0677cbc.png)

Tested it locally and found the issue is persistent in new projects within the APIsec Organization.

Steps to reproduce:
1. Add JIRA credentials into an APIsec Netbanking project
2. Create a new project using Kanban, Team Managed project template
![image](https://user-images.githubusercontent.com/47815523/189718844-e9f18a02-8c0e-4d3b-8136-c84050917a85.png)
3. Add "Bug" as a supported Issue Type
![image](https://user-images.githubusercontent.com/47815523/189719611-142ea975-5343-48e6-9019-b3db6c49ed8e.png)
4. Run a new scan in the Master profile or sync existing vulnerabilities

Expected Result:
New tickets should be generated in JIRA

Actual Result:
A new scan is filing vulnerabilities with empty Issue Id & Issue Tracker
![image](https://user-images.githubusercontent.com/47815523/189720253-9545cf3e-e783-4ff1-8f4e-ba0f1a85b155.png)

Sync Vulnerabilities with Issue Tracker is throwing the following error:

ERROR
Index 0 out of bounds for length 0

**Comment by muqeetkhan20** [comment]
@Mohammed-Luqman-Shareef i have verified this. The issues are getting logged in Jira but the issue Ids are not generating and scan history numbers are showing zero.

This issue use to reproduce frequently in the year 2021. We use to resolve this by refreshing the scanners or VC-Git control plane and later we had a permanent fix.

I think we can try this out and it should fix this bug.

Thanks,

**Comment by fersy02** [comment]
@muqeetkhan20 - Tickets are failing to log in customer's environment, and I've observed the same error in one of the NetBanking projects in the APIsec organization. What's QA doing differently to make it work, or what's missing in the configuration steps mentioned above?

Please share the project names in APIsec and JIRA to review the configurations and ensure the documentation is up to date.

**Comment by muqeetkhan20** [comment]
@fersy02 nothing different, the process remains the same as what you have followed.
Tickets are logging in Jira though the issue Ids are not generating and throwing an error on clicking sync.

Can you try to login into Jira and verify the kanban board.

**Comment by atef-aa** [comment]
@Mohammed-Luqman-Shareef, here's an update on my findings:
 
**Scenario 1**
- I created a new kanban project as per this ticket description
- Validated credentials Successfully BUT the issues were **not** synced to JIRA after scanning (same behavior as @muqeetkhan20 findings)

**Scenario 2**
- Updated the JIRA settings to point to a previously-existing Jira Project Key
> Successfully saved the settings AND the issues were logged to that project

**Comment by atef-aa** [comment]
After the scanners restarted, the vulnerabilities were logged.  This is done on an existing project and a new project.  All vulnerability count matches with the dashboard count.

**Comment by YasmeenFatima** [comment]
Working fine in dev and prod..
