### ISSUE TITLE
[Bug]: Playbooks not creating for new category

### ISSUE THREAD

**Issue by SuddenDevelopment** [apisec-inc/Support#152]
### Severity

Blocker

### What happened?

I created a category "TLS Headers"

But I cant see any playbooks created with it. So Iwent to bulk create them. and got this error
<img width="1648" alt="Screen Shot 2022-09-13 at 11 14 23 AM" src="https://user-images.githubusercontent.com/138704/189942149-baae510b-93b3-4e5e-8748-8e9a6c0e98bb.png">
<img width="1604" alt="Screen Shot 2022-09-13 at 11 20 44 AM" src="https://user-images.githubusercontent.com/138704/189942165-dec5195e-bfae-466b-a628-fa509ac438c3.png">

**Comment by SuddenDevelopment** [comment]
I think this might be because the hosted API is down:
http://20.109.174.18:3000/v3/api-docs

**Comment by SyedsImran** [comment]
check with this url http://35.243.238.46:3000/v3/api-docs 

That one(http://20.109.174.18:3000/v3/api-docs) is no more because azure subscription issue.

**Comment by SuddenDevelopment** [comment]
api is now on 
http://security-categories.apisec.ai/
I remapped everything to that and it solved my issue.
