### ISSUE TITLE
[Bug]: Adding a new user task in inactive in one of the tenant 

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#153]
### Severity

Medium

### What happened?

An Administrator of one of the organizations is trying to add a new user to their org and found the task is inactive.
![InactiveNewUserTask](https://user-images.githubusercontent.com/47815523/190055390-3e67b3a3-f209-4010-8ae9-17db8bdde681.png)

I have checked it by logging into the tenant and found that the **+New User** and **+New User (bulk)** are inactive. However, I was able to add the user from the APIsec organization. 

Also, it doesn't allow adding a user with spaces in the name. Not a blocker, as once added, we can edit and update the name with spaces.

**Comment by MuqeedA** [comment]
Adding **new user feature** from APIsec is disabled for Okta-enabled tenants.

**Comment by fersy02** [comment]
@MuqeedA - The same should be disallowed from the APIsec organization.

**Comment by asifadn9** [comment]
verified, working fine.
