### ISSUE TITLE
[Bug]: Update CI/CD shell scripts in Integrations Configuration to pull the newest script

### ISSUE THREAD

**Issue by dave-apisec** [apisec-inc/Support#154]
### Severity

Medium

### What happened?

Jenkins Instructions pulls this script: https://raw.githubusercontent.com/apisec-inc/apisec-scripts/master/apisec_job_invoke_script.sh 

All of the rest pull this script, which doesn't work as expected:  https://raw.githubusercontent.com/intesar/FX-Scripts/master/fx_job_invoke_script.sh

Please update for consistency and for customers looking to integrate by selecting their CI/CD tool from the dropdown.

**Comment by intesar** [comment]
@atef-aa are you following up on this?

**Comment by MuqeedA** [comment]
Code changes pushed and should be available in prod in next refresh.

**Comment by asifadn9** [comment]
Verified in dev, working fine.

**Comment by asifadn9** [comment]
Verified in Prod, working fine.
