### ISSUE TITLE
[Bug]: only one custom header is accepted from customer headers

### ISSUE THREAD

**Issue by SuddenDevelopment** [apisec-inc/Support#155]
### Severity

Blocker

### What happened?

we had 2 custom headers:

only one was making it into playbooks.

once it was reduced to one header it worked fine.

we need to support multiple custom headers again

**Comment by Mohammed-Luqman-Shareef** [comment]
@SuddenDevelopment I am able to add multiple headers here.  Can you pls share the details like the headers string you added and which categories you applied it to and the endpoint etc.,

**Comment by atef-aa** [comment]
@Mohammed-Luqman-Shareef, 
Under CORS Config, there were 2 headers: 
>*:/**[Origin: vulnerable.{{@Host}}]
>*:/**[x-trigger:CORS]

When logging in from an account, the trigger:CORS was getting applied upon checking in the logs but not the origin:vulnerable.

And from another account, the origin:vulnerable was getting applied.

**Comment by Mohammed-Luqman-Shareef** [comment]
@SuddenDevelopment  Can you try this
*:/**[Origin: vulnerable.{{@Host}},x-trigger:CORS]

Since you have multiple headers for the same method and path combination, you don't need separate lines.  You can put all the header values comma separated in the same line between the [ ]

**Comment by SuddenDevelopment** [comment]
yes this appears to work, thanks
