### ISSUE TITLE
[Bug]: Spaces aren't allowed in Name field on Add User page

### ISSUE THREAD

**Issue by dave-apisec** [apisec-inc/Support#157]
### Severity

Medium

### What happened?

First and last name cannot be added separated by a space. 

If I remove the space, it works. If I edit the name after initially creating the user, it works.

![Screen Shot 2022-09-15 at 10 54 53 AM](https://user-images.githubusercontent.com/104801249/190476178-ce0d02c3-b384-4a71-bf42-3f5afbe41f2c.png)

**Comment by MaimoonaFatima** [comment]
Verified in dev, working fine.

**Comment by atef-aa** [comment]
@shahidabdul please provide an update on this fix.  It still persists in PROD.

**Comment by shahidabdul** [comment]
Its working in Developer Environment. After PROD refresh you will get it in PROD.

**Comment by MaimoonaFatima** [comment]
verified in prod
