### ISSUE TITLE
[Vulnerability]: authorization header fails to mask the token

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#16]
### Severity

High

### What happened?

The Authorization header is automatically masked in the wirelogs. However, it was found that the keyword is case-sensitive and the value is masked only when the Authorization starts with A and the rest is in small letters.
![image](https://user-images.githubusercontent.com/47815523/158462160-3ddccf2d-6d7a-4ead-bd65-fd147a9a157c.png)

The Authorization keyword should be case insensitive and the following scenarios shouldn't display the text clearly:
![image](https://user-images.githubusercontent.com/47815523/158461563-21035e66-d303-454d-94c3-23b546362c1e.png)

![image](https://user-images.githubusercontent.com/47815523/158461752-8e666761-b655-4177-a246-e195e72b8fad.png)

**Comment by muqeetkhan20** [comment]
@fersy02 looks like this is customer specific, unable to reproduce this bug in NB tenant.

**Comment by fersy02** [comment]
Able to reproduce it in the NetBanking tenant and project. This is a generic issue with a **Token** authentication type:
![image](https://user-images.githubusercontent.com/47815523/158535000-a18ccbc2-0da2-4326-8bf1-719fb779012e.png)

**Comment by AtifaFahmeen** [comment]
Authorization header is made case insensitive. As im unable to reproduce in Netbanking project, @fersy02 / @muqeetkhan20  can you please test the specific scenario and confirm.

**Comment by muqeetkhan20** [comment]
@AtifaFahmeen tested in dev environment, it's fixed now. You can move this ticket to done. QA will close this ticket only after verifying in prod.
