### ISSUE TITLE
[Bug]: Assertion propagation not working when playbook detects assertion change

### ISSUE THREAD

**Issue by humera987** [apisec-inc/Support#161]
### Severity

Medium

### What happened?

Facing issue with Assertion propagation
![Asserstion bug](https://user-images.githubusercontent.com/40787463/191429478-da2d0fb8-7029-4b73-901d-c8bb6bdc2a44.PNG)

Steps to reproduce:
1. After changing the assertion in a playbook
2. Click on the Save button.
3. Popup appears assertion change detected, click on apply button
Receiving an error message "Assertions not modified" please refer to the SS.

**Comment by AtifaFahmeen** [comment]
gitkraken://repolink/55a5885a5ab5d4cad992ffeab68f2f3aabdf6983/commit/5937a46bf6642719e71e1a768e2a602531fc427a?url=https%3A%2F%2Fgithub.com%2Fapisec-inc%2FFxt.git

The issue is fixed.

**Comment by humera987** [comment]
This issue is reproducible with Injection categories, Please look into it.

**Comment by muqeetkhan20** [comment]
@humera987 though it's impacting the changed assertion. It's not a blocker - just we need to disable the error window.
@AtifaFahmeen please look into this.

**Comment by YasmeenFatima** [comment]
@humera987, i've raised the ticket a week ago https://github.com/apisec-inc/Engineering/issues/359

**Comment by muqeetkhan20** [comment]
@humera987 we can close the support ticket and track the ticket of @apisec-inc/engineering board. thanks

**Comment by AtifaFahmeen** [comment]
This issue is fixed. refer to https://github.com/apisec-inc/Engineering/issues/359.
