### ISSUE TITLE
[Bug]: Categories Page displays an error 

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#162]
### Severity

Blocker

### What happened?

Experiencing the following error on the categories page in New and Existing projects:
![image](https://user-images.githubusercontent.com/47815523/191662679-099a1a5a-ff3c-4394-b4f9-2640dae80279.png)

Steps to reproduce:
1. Log into APIsec Web Console
2. Navigate to a project, Configurations, Categories

Expected Result:
The categories page should open without any errors.

Actual Result:
A list of Categories fails to load, and the following Error is displayed:
**Comparison method violates its general contract!**

**Comment by MuqeedA** [comment]
@Abdullah-Akbar , 
As discussed , the error message is populated from **/api/v1/projects/8a80948d7ed8500d017ee4de363521d4/autocodeconfig** response. Please assign a backend developer to check this error.

**Comment by MaimoonaFatima** [comment]
We are able to reproduce this bug.
Tenant name: APIsec
Project name: proj27
**Steps to reproduce:**
1. In security categories change vulnerability score for two categories
2. In a project go to categories page
3. Open the category in which u have changed the score
4. Click resync changes will reflect (both categories) 
5. Click save and rewrite playbooks (both categories)
6. The below message will popup
![image](https://user-images.githubusercontent.com/72252407/192574332-28f551d1-49ba-4a1b-b8c9-d3030f609f2a.png)

**Comment by atef-aa** [comment]
Any update on who's working on this?

**Comment by Abedeen1** [comment]
@atef-aa , researched on the issue. it may take time for me to fix. please asign to someone else.

**Comment by atef-aa** [comment]
This issue is happening intermittently. 
@Abedeen1 will provide is looking into it.

**Comment by Abedeen1** [comment]
@atef-aa Sir,

We are unable to reproduce the error, Could you please provide steps to reproduce it.

**Comment by atef-aa** [comment]
@Abdullah-Akbar is looking into this.

**Comment by Abdullah-Akbar** [comment]
I am not successful in reproducing it, still trying.

**Comment by muqeetkhan20** [comment]
@Abdullah-Akbar our automation suite reported this error soon after the prod refresh; even the manual testers reported the same error.  We found few steps to reproduce this error; give it a try.
1. Goto security categories -> select any of the category -> edit the value -> Rebuild and Launch
2. Goto project category page -> open the edited category -> click re-sync -> wait for the value to change -> click re-write playbooks -> click on project icon
3. The error popups :)
Automation:
![image](https://user-images.githubusercontent.com/68276700/197821294-c76d004e-5867-49f0-8780-0e38425eeda2.png)

Manual:
![image](https://user-images.githubusercontent.com/68276700/197824678-98866af0-a75f-4121-b64c-f9a1e2a629fc.png)

**Comment by Abdullah-Akbar** [comment]
Just tried in dev for broken auth. no success

**Comment by muqeetkhan20** [comment]
@Abdullah-Akbar please sync up with @MaimoonaFatima on the call. She may be able to reproduce.

**Comment by atef-aa** [comment]
Some more findings on this:
The accounts that are failing contain duplicate entries for Cors_Config category.  One entry is correct but the other entry is missing name.  Attachments below.

**More points when duplicate category exists **
- The inactive checkmark does not activate the button
- The browser console shows an error with requestId: "none" 
- For other accounts where there is not reproducible, the broken entry is not present
- The search functionality is broken

Someone will need to look in the logs when this error gets thrown.

**Broken entry**
<img width="1176" alt="Screen Shot 2022-10-28 at 22 03 32" src="https://user-images.githubusercontent.com/109250250/198796418-9ebe33e9-401f-4588-9a3a-05d54abaaed6.png">

**Active entry**
<img width="1130" alt="Screen Shot 2022-10-28 at 22 04 30" src="https://user-images.githubusercontent.com/109250250/198796424-a5cc4a59-3453-4d8f-97f8-a80bbc297019.png">

**Comment by atef-aa** [comment]
@MaimoonaFatima - please review these findings and update if you have more findings.

cc: @Afra-APIsec

**Comment by MaimoonaFatima** [comment]
@atef-aa I'm unable to reproduce the duplicate entries issue.

**Comment by SuddenDevelopment** [comment]
I have a similar issue in production environment project = 'test 2' categories search and sort is broken

**Comment by SuddenDevelopment** [comment]
![Screen Shot 2022-11-02 at 4 01 32 PM](https://user-images.githubusercontent.com/138704/199591497-ea341a79-0b9e-49d8-8b5e-888e69d1405e.png)

Note "xss" is in the search but it's not filtering by it

**Comment by MuqeedA** [comment]
> ![Screen Shot 2022-11-02 at 4 01 32 PM](https://user-images.githubusercontent.com/138704/199591497-ea341a79-0b9e-49d8-8b5e-888e69d1405e.png)
> 
> Note "xss" is in the search but it's not filtering by it

The display header has null. Please update the header value and try.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/87184027/199648467-33628ac2-a501-4b10-9fa0-d52d545a742c.png">

**Comment by muqeetkhan20** [comment]
@MuqeedA If the null value is throwing the error, then we need to resolve this by restricting the user not to insert null values.

**Comment by Abdullah-Akbar** [comment]
@atef-aa these bugs do not seem related to the original issue. Please separate out.

**Comment by atef-aa** [comment]
@Abdullah-Akbar  - I want it to separate it out, but based on team's observation this error message occurs when there is an empty category value.  I can still separate it add the reference here.

@muqeetkhan20
As per the behavior the name is a required field, and this is a duplicate record, where the first value is accurate.  It is shown in screenshot in my comment from Oct 28th.

**Comment by muqeetkhan20** [comment]
@atef-aa the original issue raised by @fersy02 is still not resolved. We are still experiencing it.
btw, @MuqeedA came up with another findings; I think that's a different issue again, we can create a separate ticket, QE couldn't reproduce it though.

Let this ticket remain with the original bug - category paged displays an error.
@Abdullah-Akbar is already looking into it I believe.

**Comment by atef-aa** [comment]
Here are the tickets created for the duplicate category and search functionality:
duplicate category: https://github.com/apisec-inc/Support/issues/201
search functionality: https://github.com/apisec-inc/Support/issues/202

**Comment by atef-aa** [comment]
@AkaramAli is investigating on this further.

**Comment by AkaramAli** [comment]
@atef-aa , There are multiple issues raised in this ticket , Currently I am looking into duplicate category: https://github.com/apisec-inc/Support/issues/201

**Comment by AkaramAli** [comment]
> Comparison method violates its general contract!

This is an intermittent issue and currently it is not reproducible .
 @Afra-APIsec has confirmed that this issue has been resolved in the reported tenants/projects as part of #201 fix .
@Afra-APIsec  - Please let us know any projects where duplicate categories/categories tab error are still present ,we will fix it from backend .
Otherwise , we can close this ticket .

**Comment by muqeetkhan20** [comment]
Team, just now the same error detected. 
![image](https://user-images.githubusercontent.com/68276700/202516592-d769be3f-d418-4cfc-acea-424ef1d299f9.png)

**Comment by AkaramAli** [comment]
@muqeetkhan20  ,Please share the project details ,
Can you please  also confirm if this is a intermittent issue ?

**Comment by muqeetkhan20** [comment]
@AkaramAli this issue was shown on the call to @Mohammed-Luqman-Shareef and @Abdullah-Akbar. It's very inconsistent and we won't be able to reproduce the steps.

Please discuss this issue with the leadership

**Comment by muqeetkhan20** [comment]
Closing this ticket now; we will raise a new ticket if reproducible.
