### ISSUE TITLE
[Bug]: Add key to Auth wire log obfuscation list

### ISSUE THREAD

**Issue by dave-apisec** [apisec-inc/Support#164]
### Severity

Blocker

### What happened?

Hey team, 

Please add this key to the list of auth keys which should be obfuscated in the wire logs. 

`Ocp-Apim-Subscription-Key:`

Thank you!

**Comment by asifadn9** [comment]
verified in dev, working fine.

**Comment by atef-aa** [comment]
@asifadn9 - is this already available in PROD?

**Comment by asifadn9** [comment]
@atef-aa - simultaneously checked in prod, it is not working.

**Comment by Abdullah-Akbar** [comment]
@atef-aa this will work only when scanners are refreshed in the prod env also.

**Comment by asifadn9** [comment]
verified in Prod, working fine.
