### ISSUE TITLE
[Bug]: change in numbers of playbook when the profile is switched

### ISSUE THREAD

**Issue by Abid60** [apisec-inc/Support#165]
### Severity

Medium

### What happened?

change in numbers of playbook when the profile is switched 
After running the scan, when I go to all scan's the playbook number is 1301, When I change the profile to Master_QA1 the play book number jumps to 3483. PFA....SS
![All_playbook](https://user-images.githubusercontent.com/53075600/192945378-624c56fe-7810-4aa0-9a7c-a803d8f2c8f5.png)
![masterQA_Playbook](https://user-images.githubusercontent.com/53075600/192945390-ec625108-f92a-4841-b136-df8cff5bcb8b.png)

Issue reported by customer, kindly look into it.

**Comment by muqeetkhan20** [comment]
on further investigation:

This issue is reproducible only when we run All the categories and select the profiles.
The playbook numbers have no issues with single category run and All profile selection.

**Comment by Abid60** [comment]
@Mohammed-Luqman-Shareef  any update on this issue?

**Comment by YasmeenFatima** [comment]
@jaleelsyed this issue is still reproducible.

**Comment by muqeetkhan20** [comment]
@jaleelsyed did you get a chance to look into it?
