### ISSUE TITLE
[Bug]: Sync Timeout Issue

### ISSUE THREAD

**Issue by Afra-APIsec** [apisec-inc/Support#166]
### Severity

Medium

### What happened?

A few of the Project syncs are ending in Time-out. 
![image](https://user-images.githubusercontent.com/39483585/192977162-c161c762-06a5-458e-be2d-3750a4c7ffd7.png)

**Comment by atef-aa** [comment]
@muqeetkhan20 - please have a tester assigned to this.

**Comment by muqeetkhan20** [comment]
@atef-aa these kind of issues will be inconsistent; rarely this happens due to performance. 
We will not be able to reproduce this. You can close this ticket after checking with @Afra-APIsec

**Comment by Afra-APIsec** [comment]
This issue was raised by the client BIND. The issue is still reproducible.
![image](https://user-images.githubusercontent.com/39483585/195012700-11024581-60d2-47df-9f06-e30266b95f6d.png)

**Comment by intesar** [comment]
@Afra-APIsec is this issue fixed?

**Comment by Afra-APIsec** [comment]
Closing the ticket as the sync is working fine now with the Spec file.
