### ISSUE TITLE
[Bug]: Count of playbooks is displayed differently on playbooks page

### ISSUE THREAD

**Issue by Afra-APIsec** [apisec-inc/Support#167]
### Severity

Medium

### What happened?

The count of playbooks is displayed differently on the playbooks page as seen in the images
![image](https://user-images.githubusercontent.com/39483585/193030596-1b7f7692-c58a-46e6-ab9b-5900306efab1.png)
![image](https://user-images.githubusercontent.com/39483585/193030851-4b14fdf6-a09f-4070-a20d-577abaef8f60.png)
![image](https://user-images.githubusercontent.com/39483585/193031057-d9a12c82-8d34-4ffd-98fd-e1771e464fc0.png)

**Comment by atef-aa** [comment]
@AtifaFahmeen - please provide an update. Is the fix already being deployed?  I just reviewed one of the projects and the count looks fine.

**Comment by Afra-APIsec** [comment]
This is not reproducible now. Got fixed in a project after regenerating playbooks. Closing the ticket.
