### ISSUE TITLE
[Report]:  Assertion OR syntax consistency with docs

### ISSUE THREAD

**Issue by SuddenDevelopment** [apisec-inc/Support#179]
### Severity

Low

### What happened?

in some recent work I was told to use "OR" instead of "||" and that worked fine.

but the assertions docs inline say that "||" is valid.

we either need to make "||" work or remove it from in line help.
![Screen Shot 2022-10-10 at 2 35 08 PM](https://user-images.githubusercontent.com/138704/194931670-cbead650-d5af-468e-8c1b-41099d08f737.png)

**Comment by Mohammed-Luqman-Shareef** [comment]
@MuqeedA Pls remove || from the help text.

**Comment by MaimoonaFatima** [comment]
Verified in stg.

**Comment by MaimoonaFatima** [comment]
verified in prod.
