### ISSUE TITLE
[Bug]: Invalid assertion in Broken Authentication Category

### ISSUE THREAD

**Issue by intesar** [apisec-inc/Support#181]
<img width="698" alt="Screen Shot 2022-10-15 at 4 53 23 PM" src="https://user-images.githubusercontent.com/990419/196012054-f8fbbbd1-e074-417f-9124-339521b19230.png">
<img width="733" alt="Screen Shot 2022-10-15 at 4 56 16 PM" src="https://user-images.githubusercontent.com/990419/196012055-d2ab37af-3fe8-4584-9ce5-535cf4a0f9b9.png">
### Severity

Blocker (No Workaround Available)

### What happened?

Broken Authentication category missing assertion for 403, resulting in several invalid reporting. Fix in the issue in the DB.

Go to the APIsec tenant, then security categories:
Current assertions:
Disallowed:@StatusCode == 401 OR @StatusCode == 404
Change to
- [ ] **Disallowed:@StatusCode == 401 OR @StatusCode == 403 OR @StatusCode == 404**

- [ ] The severity has been lowered to 7 instead of 9.1.

**Comment by Mohammed-Luqman-Shareef** [comment]
@muqeetkhan20  We can close this ticket now.
Going forward we can restrict the Security category updates, as discussed in email.
