### ISSUE TITLE
[Report]:  Queries on OpenJDK-13 and its dependency on the Scanner

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#184]
### Severity

Bug

### What happened?

One of our clients reported that OpenJDK-13 is required to deploy a scanner. Since OpenJDK-13 is outdated, the client would like to know if it can be replaced with the latest version and if it will impact the functionality of our scanners.

OpenJDK-13 was found on the VM where the scanner is deployed in the following location:
/var/lib/docker/overlay2/<number>/diff/usr/java/openjdk-13
![image](https://user-images.githubusercontent.com/47815523/196921882-b0c8c36f-be0c-49fc-8f36-52ba0ee0b174.png)

After discussing it with the DevOps Team, I reported the following:
Here's an update on the OpenJDK-13 library. 
As per the APIsec DevOps team, the APIsec scanner self-contains all the essential files within the docker, and it doesn't require anything outside the container.  However, the OpenJDK-13 seems required by the Docker container, and we shouldn't delete that either. 

Docker uses /var/lib/docker to store the images, containers, and local named volumes. Deleting this can result in data loss and possibly stop the engine from running. The overlay2 subdirectory specifically contains the various filesystem layers for images and containers.

Here's the analysis reported by the client:
**EC2 Configurations**:

I tested this with 2 pre-existing servers running Docker, 2 entirely new servers, and previous screenshot/original conversation was from our initial on-prem server. 5x servers total where sampled to identify root cause of OpenJDK.
All servers where running Linux RHEL
All *new/original* (x3) servers existed for sole purpose of APISec engine. Aside from our standard bootstrap, nothing else was downloaded except for APISec
Pre-existing where similar in bootstrap, however one was running a JuiceShop and another was running a DefectDojo instance.
Only 1 of the pre-existing had JDK pre-installed, that was DefectDojo.
All *new* servers (x2) were using latest version of Docker-podman. Original and pre-existing (x3) had Docker-ce.
All servers had a fresh update during testing.  
 
Experimentation Results:
1) When using a fresh EC2 I will ultimately have an overlay with OpenJDK populated. It doesn’t matter if I use Docker or Podman. I kept doing ‘locate openjdk’ and it would not appear until after I pulled images from Docker.IO for APISec engine.

2) HOWEVER, I took another server that already had OpenJDK, pulled the Docker.IO file, and did not have an Overlay path containing OpenJDK 13.

3) HOWEVER, in BOTH scenarios, running sudo docker exec <container> java -version would ALWAYS report Java version for APISec engine as 13.0.2.

**Conclusion**:
It seems if I don’t have Java installed it will pull from docker the OpenJDK 13. However, if I already have Java then my overlay/docker file ignores it and uses my existing Java; but regardless the circumstance, docker exec reports the container as using Java version 13.0.2

Screenshot for Server with an existing Java instance, but still using openjdk 13.0.2 in docker container  
![image](https://user-images.githubusercontent.com/47815523/196928900-261be033-3139-466d-944e-3c100b8c70e5.png)

Previous screenshot, original APISec engine, did not have any previous Java, but was reporting OpenJDK in overlay/engine Container.
![image](https://user-images.githubusercontent.com/47815523/196929020-ea7cd227-df95-49a0-afc0-b5bea5dfc53a.png)

The client hasn't deployed anything on the VM, where the scanner is deployed yet “which” or “java -version” commands doesn't result in any details. “locate” identifies openjdk in the overlay of both EC2 servers. However, the java -version command returns the OpenJDK 13.0.2 – the concerned out-of-date component.

Question for APIsec?
Do we have any research that shows docker requiring and downloading OpenJDK and not the APIsec Scanner?

**Comment by Abdullah-Akbar** [comment]
[Docker ](https://www.docker.com/)containers offers OS-level abstraction and provides containerization i.e.  packaging an application’s code - with dependencies, libraries, and configuration files into a standalone executable unit.

 Meaning the only pre-requisite to install and use our APIsec scanner in any server would be 
1. Docker Engine Installation - https://docs.docker.com/engine/install/
2. Whitelisting of cloud.apisec.ai IP for outbound requests

**Comment by SyedsImran** [comment]
/var/lib/docker/overlay2/c0f3dee3675f55fe5cd88280769d76f21f0081234d1dbd852ea26e1f6cfe1837/merged/usr/java/openjdk-13
this openjdk-13 entry comes in that location from scanners we deployed in the docker installed VM, docker keeps all the files and other stuffs of the deployed container at the /var/lib/docker location inside the locally docker installed VM.
Not because java installed locally in the VM.


We will get as many entries like these for as many scanners we deployed in the VM, as our scanner uses openjdk version "13.0.2" 2020-01-14 for it's operations.

![image](https://user-images.githubusercontent.com/100760767/196947681-d0933541-5304-4b7d-b7ee-f9a0bbbd342a.png)

**Comment by muqeetkhan20** [comment]
@atef-aa  QE will not be able to test this; please follow up with the concern department and close the ticket.

**Comment by Abdullah-Akbar** [comment]
@muqeetkhan20 please verify whether the documentation and help text contains this [information](https://github.com/apisec-inc/Support/issues/184#issuecomment-1285435691) -

**Comment by intesar** [comment]
- [ ] Upgrade open-jdk in scanner to the latest version @Abdullah-Akbar

**Comment by atef-aa** [comment]
@Abdullah-Akbar - Please update the ETA for this.

**Comment by Abdullah-Akbar** [comment]
Solution approach is still under evaluation

**Comment by APIStacey** [comment]
HI @Abdullah-Akbar  - we really need the solution. Can you please give me an updates?

**Comment by Abdullah-Akbar** [comment]
We have upgraded the scanner to use Java version 17. This is planned to be part of tomorrow's release.

**Comment by atef-aa** [comment]
the release have been postponed to early next week.

**Comment by APIStacey** [comment]
Hey @atef-aa  - this issue shows as closed, no comment that it was deployed though. Cen we confirm that it was deployed and things should work on OpenJDK 13.02+

**Comment by Abdullah-Akbar** [comment]
All our scanners are currently operational on OpenJDK 17 .

**Comment by APIStacey** [comment]
I have let him know
