### ISSUE TITLE
[Report]: Avoid closing valid vulnerabilities due to server or authentication errors

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#185]
### Severity

Bug

### What happened?

During a training session, I noticed a valid vulnerability in the Incremental Ids L2 category closed because the server responded with a 500 status code. Ideally, it should have considered this as a false negative.

Here's the scan result:
![image](https://user-images.githubusercontent.com/47815523/197003133-eb01fcfb-2e46-4b6d-a1f0-eefd1d2878c8.png)

Here's the screenshot of a closed vulnerability:
![image](https://user-images.githubusercontent.com/47815523/197003279-1661b4b6-23b5-4c8f-8511-98b16ace1df1.png)

**Comment by atef-aa** [comment]
@MaimoonaFatima - When is this planned to be in prod?

**Comment by MaimoonaFatima** [comment]
@atef-aa It will be in prod tomorrow.

**Comment by atef-aa** [comment]
as prod deployment postponed to next week, this will be picked up then.

**Comment by muqeetkhan20** [comment]
I tried this scenario with broken authentication; it's not reproducible now.
Unable to test it for Incremental Ids L2, because NB app doesn't log any vulnerability.
