### ISSUE TITLE
[Report]: Category text improvements

### ISSUE THREAD

**Issue by intesar** [apisec-inc/Support#186]
### Severity

UX Improvement.

Do it as a DB Script @Mohammed-Luqman-Shareef @SuddenDevelopment 

### What happened?

- [x] Rename "Sensitive data exposure" to "Sensitive Data Exposure"
- [x] Rename "ADoS" to "ADoS (Resource Limit)"
- [x] Rename "XSS Injection" to "Stored XSS Injection" 
- [x] Rename "RateLimit_Authenticated" to "Rate-Limit (Authenticated)"
- [x] Rename "RateLimit_Auauthenticated" to "Rate-Limit (Unauthenticated)"
- [x] Rename "Authentication Scheme" to "Insecure Authentication Scheme"
- [x] Rename "TLS HSTS Headers" to "Missing TLS HSTS Headers"
- [x] Rename "PII" to "PII Data Exposure"
- [x] Remove assertion from cors "@ResponseHeaders.Access-Control-Allow-Origin != @NULL"

**Comment by intesar** [comment]
@Mohammed-Luqman-Shareef can we do a hot deploy for this ticket?

**Comment by Mohammed-Luqman-Shareef** [comment]
Sure.  This one needs only a DB script.  We can runt it from backend, no need of code deployment.
@AkaramAli, can you pls share the SQL script with DevOps and ask them to run it in Prod DB.  Once done, verify it through UI and update this ticket.

**Comment by SuddenDevelopment** [comment]
@Mohammed-Luqman-Shareef  I thought this was my task, did it... in the repo as V390

**Comment by Mohammed-Luqman-Shareef** [comment]
@SuddenDevelopment, Thanks for pushing it in repo.  Going forward you can take care of such category changes via flyway.  
Since there was an ask for hot deployment, I got them updated in DB.

**Comment by MaimoonaFatima** [comment]
@Mohammed-Luqman-Shareef 
1. Categories name not updated in stg env. 
2. Old names are still showing in most places(dev & prod)
Security categories page, scan history etc.
![image](https://user-images.githubusercontent.com/72252407/197496594-4c720f1d-8a2c-4c7d-9abf-b7034ff7e533.png)
![image](https://user-images.githubusercontent.com/72252407/197496848-33a036b9-1f75-466f-84a4-d0d268f6acbc.png)

**Comment by Mohammed-Luqman-Shareef** [comment]
@muqeetkhan20 Stg env will be refreshed only before the prod release.

**Comment by Mohammed-Luqman-Shareef** [comment]
Daily testing should continue in Dev env as usual.

**Comment by muqeetkhan20** [comment]
@Mohammed-Luqman-Shareef as discussed on the call; the new category names did not impact in many areas (scans, reports, security categories etc)

**Comment by SuddenDevelopment** [comment]
I previously updated the display_header_label which I thought SHOULD be the primary one uses for "display"
I'll update the "category" column as well in a new flywheel script. 

I DO NOT think we should update the "type" column which is used as a key. Anywhere the UI is using that where it needs to change should be a UI change

**Comment by SuddenDevelopment** [comment]
committed as flywheel script 399

**Comment by Mohammed-Luqman-Shareef** [comment]
@SuddenDevelopment , It seems this flyway script has broken some of the functionalities in UI.  
The updated categories are not shown in the drop down for scan now.
Can you pls revert it.

**Comment by AkaramAli** [comment]
@SuddenDevelopment  , We can not have a space in category field, the last script (V401__category_renaming_revert.sql) that you have pushed has a space in category of tls_headers type.
Because of this , TLS category is not shown in scan dropdown .

Please update the category column to to '**TLS_Headers** ' instead of '**TLS Headers**' .

**Comment by SuddenDevelopment** [comment]
I supposed all of the remaining changes Intesar asked for will need to be what field the UI looks at

**Comment by AkaramAli** [comment]
@atef-aa -This is completed and moved to QA .

**Comment by muqeetkhan20** [comment]
@AkaramAli in some areas the changed categories are not displaying; we have discussed this with @Mohammed-Luqman-Shareef 
@MaimoonaFatima could you please share the screenshots.

**Comment by MaimoonaFatima** [comment]
![image](https://user-images.githubusercontent.com/72252407/199659093-b3b98073-fef3-418e-aaae-3b58ce04b5d1.png)
![image](https://user-images.githubusercontent.com/72252407/199659125-1d61cf08-55ce-457c-b381-56d0e718fc15.png)
![image](https://user-images.githubusercontent.com/72252407/199659402-d2b67126-41e3-49f8-95f6-ae4f97c350ca.png)

**Comment by AkaramAli** [comment]
@muqeetkhan20 , if you go through the ticket , only Security Category Name/Label (display_header_label) has been updated , not the category column itself  ,so wherever in UI Category Label (display_header_label ) is used , Only that will render the updated values .

**Comment by SuddenDevelopment** [comment]
we discoevered that changing the "category" field causes issues in the UI. We cannot simply update that in the DB.

We can either go through all the changes required for that to work in the DB
OR
update the UI to only use the display_label
OR
assume it's ok for the display label to be different than the category field

I think we have taken this as far as we can for now due to the above limitations. Should make a decision on the above before closing the ticket.

**Comment by Mohammed-Luqman-Shareef** [comment]
Yes, the category column is referred from many places in the code.  Making changes to it directly in DB breaks few functionalities.
@AkaramAli is working on it to make it independent.  
Since the Original ask for changing the display header was accomplished, we can close this ticket.
