### ISSUE TITLE
[Report]: wildcard matching in incremental_ids

### ISSUE THREAD

**Issue by intesar** [apisec-inc/Support#187]
### Severity

Bug

### What happened?

Please support this:

- [x] @ResponseHeaders.X-*-Version == @null (@Mohammed-Luqman-Shareef can you look into this?)

(We can look into this later)
- [ ] Support wildcard comparison in assertions e.g. in incremental_ids we should support @Response.$..*id != @Numbers

**Comment by intesar** [comment]
@Mohammed-Luqman-Shareef - please ask someone to look into this enhancement.

**Comment by SuddenDevelopment** [comment]
what's the status on this? I need this for another one as well

**Comment by SuddenDevelopment** [comment]
I need to support

@ResponseHeaders.X-*-Version == @NULL

**Comment by jaleelsyed** [comment]
support added.
@ResponseHeaders.X-*-Version == @null

**Comment by GhouseApisec** [comment]
@SuddenDevelopment, Can you pls verify on this and close the ticket if it is working as expected.

**Comment by SuddenDevelopment** [comment]
@GhouseApisec  THANKS I was looking for this one. testing now.

**Comment by SuddenDevelopment** [comment]
works for me, thanks.
