### ISSUE TITLE
[Report]: Stored Injection assertion

### ISSUE THREAD

**Issue by intesar** [apisec-inc/Support#188]
### Severity

Bug

### What happened?

How can we support this in assertions?

// check if the response has injection text
@Response ~= @Injection

**Comment by intesar** [comment]
@SuddenDevelopment can you look into this?

**Comment by SuddenDevelopment** [comment]
I have created a "Reflected GET Injection" Category that is ready to be replicated. Luqman asked that I make a ticket for replicating this one instead of doing it myself.

**Comment by Mohammed-Luqman-Shareef** [comment]
@SuddenDevelopment, is the category in your lab env?
Can you pls provide access to @AkaramAli.  
@AkaramAli, create a flyway script to replicate it.

**Comment by SuddenDevelopment** [comment]
@Mohammed-Luqman-Shareef  I created a ticket for it here: https://github.com/apisec-inc/IM/issues/216

**Comment by SuddenDevelopment** [comment]
keep in mind this is for the GET only. I'm working on a separate one for POST because the category types are split that way

**Comment by Mohammed-Luqman-Shareef** [comment]
@AkaramAli created a flyway script and updated the ticket https://github.com/apisec-inc/IM/issues/216

@SuddenDevelopment, This ticket can be closed.
