### ISSUE TITLE
Show on Security Category page "Active By Default" Column. Remove the status column.

### ISSUE THREAD

**Issue by intesar** [apisec-inc/Support#189]

**Comment by Mohammed-Luqman-Shareef** [comment]
Apart from Active by default, user can activate or de activate categories from this page.  So we need status column as well, other wise there is no other way to know if a category is currently active or not.
I would suggest we have both the columns on the page.

**Comment by intesar** [comment]
@Mohammed-Luqman-Shareef sure keep both the columns

**Comment by MaimoonaFatima** [comment]
Verified in stg.

**Comment by muqeetkhan20** [comment]
@MuqeedA we need to remove the "Active By Default" column from the project category page.

**Comment by intesar** [comment]
@MuqeedA thanks
