### ISSUE TITLE
[Bug]: [Blocker] Tests are getting executed several times

### ISSUE THREAD

**Issue by intesar** [apisec-inc/Support#19]
### Severity

Blocker

### What happened?

Run Unsecured against Super_1, 2, and 3. You'll see tests are getting executed several times.

**Comment by intesar** [comment]
@Mohammed-Luqman-Shareef @Abdullah-Akbar @muqeetkhan20  This is blocking all tests. Please look into it first thing.

**Comment by muqeetkhan20** [comment]
@intesar this is fixed, we don't see any duplicate test results now.
We have tried unsecured for all the super scanners in prod.

**Comment by intesar** [comment]
thanks.
