### ISSUE TITLE
[Report]: Project registered with Postman Collection URL detect less endpoints

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#191]
### Severity

Bug

### What happened?

A prospect has reported that the postman collection he is trying to register has around 17 endpoints, but when registering the collection using the URL, the project shows only 5 endpoints.

I tried reproducing the issue using the URL. APIsec detected only 5 endpoints
![image](https://user-images.githubusercontent.com/47815523/197557195-680ab3f0-f839-4176-9054-c6ce8b36b50f.png)

Exported the file and registered the collection to discover all endpoints
![image](https://user-images.githubusercontent.com/47815523/197557571-9dc25b44-6f25-4902-8161-6a6e10e09ffa.png)

The behavior should be consistent, and errors must be reported if it fails to discover all endpoints.
Both projects, RS and RSPM are available in the APIsec Organization to collect the URL and file used for project registration.

**Comment by fersy02** [comment]
Please address this at the earliest as it is a customer-facing issue.

**Comment by AkaramAli** [comment]
I am looking into it .

**Comment by AkaramAli** [comment]
@fersy02  -
I have debugged this issue and noticed that Postman URL and the exported collection have different postman collection schema versions .

Postman URL collection  has v2.0.0  ,while Exported collection has v2.1.0 

@MuqeedA  @ImranShaik065 -
This seems to be Postman Convertor issue , not related to platform ,Can someone look into this ?

**Comment by intesar** [comment]
@ImranShaik065 are you looking into this?

**Comment by ImranShaik065** [comment]
@MuqeedA is already started working on this.

**Comment by atef-aa** [comment]
@MuqeedA - Please provide an update when this will be available.

**Comment by atef-aa** [comment]
This task will be picked up by mid of coming week.

**Comment by atef-aa** [comment]
This should be completed by Friday this week.

**Comment by MuqeedA** [comment]
@muqeetkhan20 
Postman service has been deployed in dev env for testing. Please test it and let me know if you find anything missing. Thanks.

**Comment by muqeetkhan20** [comment]
@MuqeedA can you please provide us the valid postman URL?

**Comment by YasmeenFatima** [comment]
Verified in dev
![image](https://user-images.githubusercontent.com/69448810/202630509-7b22fa6a-db25-4942-b4df-6946c5922781.png)

**Comment by YasmeenFatima** [comment]
Verified in prod.
@MuqeedA , But only 240 playbooks are generating. Where as in dev 318 playbooks are generating.
![image](https://user-images.githubusercontent.com/69448810/202725928-62381600-64d3-4238-ab60-a615561ecfb2.png)

**Comment by YasmeenFatima** [comment]
In dev, extra categories are there. That is the reason of mismatch in playbooks numbers compare to prod. 
Rest is all good.
