### ISSUE TITLE
[Report]: GItHub Actions APIsec name has a capital "S"

### ISSUE THREAD

**Issue by APIStacey** [apisec-inc/Support#192]
### Severity

Bug

### What happened?

GitHub Actions are capitalizing the "S" in APIsec.

![image](https://user-images.githubusercontent.com/115025465/197571343-eaa90da8-098e-48af-904a-31c8ac70fba9.png)

**Comment by intesar** [comment]
@abdul-hai-apisec

**Comment by muqeetkhan20** [comment]
Fixed
