### ISSUE TITLE
[UX Improvement]: Empty Orgs throw message that look like an error

### ISSUE THREAD

**Issue by APIStacey** [apisec-inc/Support#193]
### Severity

UX Improvement

### What happened?

I created a new tenant and was logging in for the first time. It shows this message that looks like an error. It would be better to have a message on the screen just saying no projects. The message as it is currently looks like a bug

![image](https://user-images.githubusercontent.com/115025465/197632705-ca3cec65-5574-4e99-b388-06e6e219be1e.png)

**Comment by MuqeedA** [comment]
@atef-aa ,
This is already fixed as part of this ticket: https://github.com/apisec-inc/Engineering/issues/388

**Comment by MaimoonaFatima** [comment]
Verified in prod.
