### ISSUE TITLE
[Report]: Review RBAC Map Lists only 1000 Endpoints for an API more than 1000 Endpoints

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#194]
### Severity

Blocker (No Workaround Available)

### What happened?

One of our clients has 2469 endpoints, and after running an RBAC Scan, the Review RBAC Map lists only 1000 endpoints. Unfortunately, there is no alternative for retrieving all endpoints, even by downloading the Excel file.

![image](https://user-images.githubusercontent.com/47815523/197850449-7bf8f043-d8a4-4fa1-8942-d668ae4b52e1.png)

Please look into this on priority as there is no alternative.

**Comment by MuqeedA** [comment]
The API `/api/v1/projects/<projectId>/endpoints` is returning 1000 endpoints only. Correction required in backend code.

**Comment by intesar** [comment]
@abdul-hai-apisec increase the max-limit to 2500 for this api endpoint

**Comment by muqeetkhan20** [comment]
Can anyone provide us the api returning 1000 endpoints; QE would not be able to test this through NB.

**Comment by atef-aa** [comment]
There are 2 asks in comments:
1. increase the max-limit to 2500 for this api endpoint
2. Correction required in backend code.

@MuqeedA - please provide an update

**Comment by abdul-hai-apisec** [comment]
@atef-aa , I have done the required changes already @ https://github.com/apisec-inc/Fxt/commit/fc3577564a3a9dc709b69a9afad551f447bfefb4

**Comment by atef-aa** [comment]
Thanks @abdul-hai-apisec.

@fersy02 please verify the changes and that you're not blocked.

**Comment by FidaUrRahman** [comment]
@fersy02 verified  using endpoint `/api/v1/projects/<projectId>/endpoints` , getting length of the reponse data as 2469 
But unfortunately unable to test by running RBAC scan because system getting busy, and playbooks not generating

**Comment by MaimoonaFatima** [comment]
Verified in prod, working fine
