### ISSUE TITLE
[Report]: Production UI issues with scanning and playbooks

### ISSUE THREAD

**Issue by SuddenDevelopment** [apisec-inc/Support#195]
### Severity

Blocker (No Workaround Available)

### What happened?

Write a brief report...
![Screen Shot 2022-10-25 at 3 13 50 PM](https://user-images.githubusercontent.com/138704/197861809-8a77a009-a0b2-4c3c-a200-c94e9beab1d7.png)
 2 issues:

 1. when creating playbooks, many categories are blank labels.
 2. When trying to scan, I'm ot able to get any private / active categories to show. I created a new one, it wont show. had a similar problem earlier and it looked like it was just a problem with that category

**Comment by Abdullah-Akbar** [comment]
@SuddenDevelopment I am not able to reproduce this. is this still occurring?

**Comment by YasmeenFatima** [comment]
This issue is not reproducible

**Comment by atef-aa** [comment]
This is working for Anthony now.
