### ISSUE TITLE
[Report]: GitHub Actions - Creating a workflow from the APIsec template run into issues

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#196]
### Severity

Bug

### What happened?

GitHub Actions allow a user to create a workflow using an existing template. Upon creating a workflow with the APIsec template, import an invalid version compared to one available in the Marketplace.

![image](https://user-images.githubusercontent.com/47815523/197956837-f6142192-839f-471b-b461-9a96e2c888bd.png)

Steps to reproduce:

1. Log in to the GitHub console 
2. Navigate to the desired repository, Actions
3. Click New Workflow 
4. Type apisec in the search workflows field and hit enter
5. Click Configure on the APIsec Scan Workflow

Expected Result:
The latest version should be copied into the script.

Actual Result:
An invalid version that fails to invoke the script.

Additionally, the following error is displayed:
![image](https://user-images.githubusercontent.com/47815523/197958540-e5419635-868e-4271-af18-db7d2f32c526.png)

Running Workflow fails with the following error:
![image](https://user-images.githubusercontent.com/47815523/197962642-10e4032c-d8cd-4800-aad2-776de6cf3301.png)

After replacing the SHA of the older version with the latest it works:
![image](https://user-images.githubusercontent.com/47815523/197963608-4aa13db6-eed1-4b1b-b340-fe3401c61f05.png)

**Comment by APIStacey** [comment]
Just to add - here is a video showing some details: https://www.screencast.com/t/7KGenoTeJ0j6

**Comment by abdul-hai-apisec** [comment]
https://github.com/actions/starter-workflows/pull/1798

**Comment by atef-aa** [comment]
@MaimoonaFatima - is this included in today's refresh?

**Comment by muqeetkhan20** [comment]
@atef-aa QE will pick the tickets which are QA tagged by @apisec-inc/engineering, it indicates they are ready to test.
@abdul-hai-apisec can you please update the status of this ticket?

**Comment by abdul-hai-apisec** [comment]
@atef-aa / @muqeetkhan20 , This fix doesnt depend on our prod refresh, instead it depends on the https://github.com/actions/starter-workflows/pull/1798 approval of pull request.
