### ISSUE TITLE
Project pagination is retaining the page but not updating the page position

### ISSUE THREAD

**Issue by atef-aa** [apisec-inc/Support#198]
### Severity

Bug

### What happened?

When a user navigates thru the project using the pagination, clicks on a project, then back to the homepage, the last pagination is retained (which is expected) **but** the pagination got reset to the first page position (which needs to be retained along with the page visited).

Steps to re-produce:

1. Login to an account with multiple projects > from the homepage, navigate to the next page (or any)
2. Open the project > Click on the logo

Actual
**Observe the pagination is reset to the first (1 - 10 of 65)**, while the user is on last visited page

Expected
The pagination need to sync with the last visited page

<img width="1391" alt="Screen Shot 2022-10-29 at 07 57 59" src="https://user-images.githubusercontent.com/109250250/198833128-06cff93f-bc32-4dbe-a6e2-5335ef082606.png">

**Comment by atef-aa** [comment]
This should be picked up today by @ImranShaik065

**Comment by atef-aa** [comment]
@ImranShaik065 thanks for fixing this. Can this be picked up by QA?

**Comment by ImranShaik065** [comment]
Yes

**Comment by YasmeenFatima** [comment]
Verified in dev..

**Comment by YasmeenFatima** [comment]
Verified in rpod..
