### ISSUE TITLE
[Bug]: Free Account

### ISSUE THREAD

**Issue by muqeetkhan20** [apisec-inc/Support#20]
### Severity

Blocker

### What happened?

- [x] Request more licenses link is broken in advance section.
- [x] Reports tab should be restricted similar to integration tab, we should not allow the free user to enter in the summary or coverage tabs by showing the popup window (upgrade license).

**Comment by muqeetkhan20** [comment]
#item 2 needs to be fixed, right?

**Comment by MuqeedA** [comment]
> #item 2 needs to be fixed, right?

Both items are completed.

**Comment by shahidabdul** [comment]
#item 2 fixed as per the requirement.
