### ISSUE TITLE
[Report]: Closed vulnerabilities appear in the Vulnerabilities tab on the Dashboard and adds inconsistency in the Customer Usage Report

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#200]
### Severity

Blocker (No Workaround Available)

### What happened?

There are two issues that could be interlinked. 

1. The vulnerability tab on the dashboard lists all vulnerabilities, including the closed vulnerabilities. The expectation is to display only open vulnerabilities.
2. The statistics sent in the customer usage report are not accurate. Here are the details:

One of our client has only 119 open vulnerabilities
![image](https://user-images.githubusercontent.com/47815523/199264159-3fc4c90a-bfa2-4bf3-956f-170799c3c63a.png)

Yet the vulnerabilities count displays 322 
![image](https://user-images.githubusercontent.com/47815523/199264564-656e0fe5-8702-43b2-ae43-cb26c4bf711f.png)

and the customer usage report has inaccurate statistics:
![image](https://user-images.githubusercontent.com/47815523/199264894-6a3faac6-5ead-4f2d-9994-7d5e4c2bf6a4.png)

**Comment by atef-aa** [comment]
@jaleelsyed - please look into this.

**Comment by intesar** [comment]
@Mohammed-Luqman-Shareef please assign this to someone. It should be a straightforward fix.

**Comment by intesar** [comment]
@jaleelsyed - thanks for fixing it.

Looks like it's fixed and pending refresh.

**Comment by YasmeenFatima** [comment]
Working fine, Verified in dev..

**Comment by YasmeenFatima** [comment]
Verified in prod
