### ISSUE TITLE
[Report]: Duplicate categories appear for some accounts

### ISSUE THREAD

**Issue by atef-aa** [apisec-inc/Support#201]
### Severity

Bug

### What happened?

When a user navigates to a project > configurations > categories
For some accounts there are duplicate entries for CORS_CONFIG and some other categories

**This is the duplicate entry**

![](https://user-images.githubusercontent.com/109250250/198796418-9ebe33e9-401f-4588-9a3a-05d54abaaed6.png)

**This is the correct entry**
![](https://user-images.githubusercontent.com/109250250/198796424-a5cc4a59-3453-4d8f-97f8-a80bbc297019.png)

**Comment by atef-aa** [comment]
@MuqeedA also have found some 

![](https://user-images.githubusercontent.com/138704/199591497-ea341a79-0b9e-49d8-8b5e-888e69d1405e.png)

The display header has null. Please update the header value and try.


![](https://user-images.githubusercontent.com/87184027/199648467-33628ac2-a501-4b10-9fa0-d52d545a742c.png)

**Comment by AkaramAli** [comment]
@atef-aa  , This issue is specific to a tenant/project , Please provide access to the tenant/project to investigate further .

**Comment by atef-aa** [comment]
@AkaramAli - messaged you the details.  If you need more info, connect with @Afra-APIsec.

**Comment by atef-aa** [comment]
@AkaramAli started investigating this issue.

**Comment by Mohammed-Luqman-Shareef** [comment]
@AkaramAli,  Delete the duplicates from backend.  Ask DevOps to run query in DB.  I sent you an email with details,

**Comment by AkaramAli** [comment]
Duplicate entries were deleted from backend .
This issue is resolved now !

![image](https://user-images.githubusercontent.com/89961027/201584909-ba039cc4-1a35-452f-9e33-a5fc9c68ae01.png)

@Afra-APIsec , Kindly delete and regenerate the playbooks for CORS and TLS categories .

**Comment by atef-aa** [comment]
@Afra-APIsec - additionally, please check if the issue reported in #162 is now working or not.
