### ISSUE TITLE
[Report]: The search functionality is broken on Category page for some accounts

### ISSUE THREAD

**Issue by atef-aa** [apisec-inc/Support#202]
### Severity

Bug

### What happened?

When a user navigates to a project > configurations > categories
The search functionality is not working and not filtering the results.  
This search functionality appears to be broken when duplicate records appear, which is outlined in #201

**Comment by AkaramAli** [comment]
This issue is fixed as part of #201 .

**Comment by muqeetkhan20** [comment]
@atef-aa the duplicate categories were already deleted from the backend; we don't want to test it again by creating duplicate categories. Search is all good; closing the ticket.
