### ISSUE TITLE
[Report]:  User not Authorized when editing a private category

### ISSUE THREAD

**Issue by SuddenDevelopment** [apisec-inc/Support#203]
### Severity

Bug

### What happened?

I'm not able to edit a private category in prod.

I get a user not authorized error

![image](https://user-images.githubusercontent.com/138704/200647740-93bba8e1-aea7-430f-9ba8-280a2f7a90e3.png)

**Comment by atef-aa** [comment]
@SuddenDevelopment - I am not able to reproduce.  Added tags and assertions couple of times and was able to edit.  Is this happening to a specific client?

**Comment by intesar** [comment]
@sarasheed add role ENTERPRISE_ADMIN to Anthony in APIsec tenant.
