### ISSUE TITLE
[Report]: dateBefore and dateAfter Comparisons are swapped

### ISSUE THREAD

**Issue by SuddenDevelopment** [apisec-inc/Support#205]
### Severity

Bug

### What happened?

dateBefore and dateAfter both appear to work 

[@Cert-ExpiresOn dateBefore @NextWeek] resolved-to [Mon Jan 16 16:19:27 UTC 2023 dateBefore Wed Nov 16 22:44:43 UTC 2022]

but they are swapped.

dateAfter should be >
dateBefore should be <

Please update and update categories that are affected

**Comment by atef-aa** [comment]
@jaleelsyed - please pick this item when you complete higher priority items.
