### ISSUE TITLE
[Report]: Vulnerability Dashboard still shows Archived or Deleted Vulnerabilities

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#206]
### Severity

Blocker (No Workaround Available)

### What happened?

Archived or deleted vulnerabilities should immediately disappear from the Vulnerabilities dashboard. However, it has been found that these changes are not reflecting immediately and creating confusion among our customers. Please address this ASAP.

Steps to reproduce:
1. Archive vulnerabilities from an existing project
2. Navigate to the Vulnerabilities dashboard

Expected Result:
All archived vulnerabilities should disappear immediately

Actual Result:
Archived or deleted vulnerabilities still appears in the list

**Comment by atef-aa** [comment]
I tried deleting and archiving with netbanking and it got disappeared immediately.  please share the orgs which this is happening in an email.

**Comment by MaimoonaFatima** [comment]
This issue is not reproducible.

**Comment by atef-aa** [comment]
@jaleelsyed - please investigate this further.  It's happening to a specific tenant. Details sent in chat.

**Comment by jaleelsyed** [comment]
@atef-aa Issue was fixed last week. 
Pending prod refresh.

**Comment by muqeetkhan20** [comment]
@jaleelsyed let's add the QA label to avoid the confusions.

**Comment by YasmeenFatima** [comment]
Verified in prod
