### ISSUE TITLE
[Bug]: CORS vulnerabilities are not getting logged on dashboard

### ISSUE THREAD

**Issue by Afra-APIsec** [apisec-inc/Support#207]
### Severity

Bug

### What happened?

Executed scan by selecting Cors_Config Category in Master profile.

Expected behavior:
Failed playbooks should log vulnerabilities on the dashboard.

Current behavior:
Vulnerabilities didn't get logged for Cors_Config Category.

![image](https://user-images.githubusercontent.com/39483585/201152736-fd987a8d-5461-4993-b12f-9c5e15f43744.png)
![image](https://user-images.githubusercontent.com/39483585/201152882-ac93fc12-f874-4b17-af2c-893d16099a45.png)

**Comment by FidaUrRahman** [comment]
@Afra-APIsec , not reproducible with netbanking API
![image](https://user-images.githubusercontent.com/87167471/201586489-ed193033-4f69-45f7-8aa4-85aec2777633.png)

**Comment by AkaramAli** [comment]
@Afra-APIsec , Tried with Net banking spec  in prod in APIsec tenant , Vuls are being logged .
Please share the steps/spec to reproduce this .
