### ISSUE TITLE
[Bug]: HttpAuthenticationScheme Playbook fails even though the RequestHeader starts with Bearer

### ISSUE THREAD

**Issue by Afra-APIsec** [apisec-inc/Support#208]
### Severity

Bug

### What happened?

HttpAuthenticationScheme Playbook fails even though the RequestHeader starts with Bearer.

Workaround implemented: 
 Switching the 'unmaskToken' to true in the playbook passes the playbook.

**Comment by Mohammed-Luqman-Shareef** [comment]
@AtifaFahmeen,
    It seems the assertion validation is happening after the masking.  In case of masking, mask only the actual token/auth string and keep the initial Bearer / Basic as is.

**Comment by FidaUrRahman** [comment]
Verified working in dev , will be available in next prod refresh

**Comment by MaimoonaFatima** [comment]
Verified in prod.
