### ISSUE TITLE
[Bug]: Sensitive Data Exposure and Sensitive Data Exposure L2 both categories generating GET method endpoints and logging duplicate vulnerabilities on dashboard on same endpoint

### ISSUE THREAD

**Issue by Afra-APIsec** [apisec-inc/Support#209]
### Severity

Bug

### What happened?

Current Behavior: Sensitive Data Exposure and Sensitive Data Exposure L2 both categories are generating GET method endpoints and logging duplicate vulnerabilities on the dashboard on the same endpoint.

Expected Behavior: Same endpoints should not get generated in both categories as the same test is being performed in both categories.

**Comment by muqeetkhan20** [comment]
@fersy02 good finding; we never had a test case comparing both the categories, thought customer may run any one of them.
If the duplicates have to be avoided then we will include this test case in our sanity report.

**Comment by Mohammed-Luqman-Shareef** [comment]
L1 should generate GET playbooks and L2 Post playbooks.
With the latest PII category these two are deprecated and they are not activated by default now.  We can ignore them.

**Comment by muqeetkhan20** [comment]
@Mohammed-Luqman-Shareef closing this ticket.
