### ISSUE TITLE
[Bug]: Trello account details disappear after navigating away 

### ISSUE THREAD

**Issue by atef-aa** [apisec-inc/Support#210]
### Severity

Bug

### What happened?

When adding Trello account and navigating away the details account details disappear.

**Steps to reproduce**

Under Issue Tracker > add a Trello account details > Save
Navigate away (or refresh the page) > Return to Issue Tracker again > Observe the 'Issue Tracker Credentials' drop down is empty. 'Issue List' field is empty and others.

Note: This is not happening when Jira is used.

**Comment by MuqeedA** [comment]
Code changes pushed.

**Comment by YasmeenFatima** [comment]
Verified in dev..

**Comment by YasmeenFatima** [comment]
verified in prod..
