### ISSUE TITLE
[Report]: Java Exception Thrown Upon Adding a new Endpoint

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#211]
### Severity

Blocker (No Workaround Available)

### What happened?

Experiencing the following error upon adding an endpoint in a newly created project:
![image](https://user-images.githubusercontent.com/47815523/203219328-0e554824-f268-4e9b-bcee-81077b747080.png)

Steps to reproduce:

1. Register a project without an API spec file.
2. Navigate to endpoints, click add endpoints
3. Select an HTTP method, enter the endpoint path and click Save

Expected Result:
1. The endpoint should add immediately

Actual Result:
Observing error

**Comment by MaimoonaFatima** [comment]
This error is reproducible. 
This is not in our sanity sheet, will add this test case as well.

**Comment by MaimoonaFatima** [comment]
Verified in Dev.

**Comment by MaimoonaFatima** [comment]
Verified in stg working fine.

**Comment by MaimoonaFatima** [comment]
Verified in prod.
