### ISSUE TITLE
[Report]: Reload Spec with file throws an error in older projects

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#212]
### Severity

Blocker (No Workaround Available)

### What happened?

A client has reported that they cannot reload a specification using a file as it is throwing the following error:
**Transaction silently rolled back because it has been marked as rollback-only**

When I tried to register an API using the same file, it worked, and also, reloading a spec is working well. However, if we try to reload the specification file in an older project, it throws an error. I noticed the following change in the newly registered projects:
The status property is set to "UI" which used to be null.
![image](https://user-images.githubusercontent.com/47815523/205083991-6bd37a62-9923-4bbe-93d5-6935b7fda75b.png).

Upon trying to reload a spec in an older project where the status is: **null**, we get the following error:
![image](https://user-images.githubusercontent.com/47815523/205084481-1c530116-b6f4-4abc-8619-8f2bcc329aa6.png)

This is a P0, impacting all the clients trying to reload a specification with a file, and there is no workaround known to us today.

**Comment by Afra-APIsec** [comment]
This is reproducible in multiple tenants.

**Comment by Abdullah-Akbar** [comment]
@Afra-APIsec this has been rectified. Please try now.

**Comment by Afra-APIsec** [comment]
Thank you for the quick response @Abdullah-Akbar. This issue is fixed now.
