### ISSUE TITLE
[Report]: Replace mention of "Excel or xlsx" with CSV in UI 

### ISSUE THREAD

**Issue by intesar** [apisec-inc/Support#213]
### Severity

UX Improvement

### What happened?

Write a brief report...

**Comment by MuqeedA** [comment]
**Completed:** 
Project List page (Landing page after login)
1. Download All Vulnerabilities
2. Download All Endpoints
3. Download All APIs data

**Pending items:**
1. Project dashboard - download vulnerabilities
2. Project dashboard - download all vulnerabilities
3. Reports - Trends data
4. Endpoints - Download endpoints
5. Dashboard - Download all APIs data

**Comment by YasmeenFatima** [comment]
Verified in prod.

**Comment by YasmeenFatima** [comment]
Download as excel is still there in ABAC 1 category 
![image](https://user-images.githubusercontent.com/69448810/210227043-25c04177-905d-4e29-b372-3505a0a35c3e.png)

**Comment by YasmeenFatima** [comment]
In reports, coverage tab ss
![image](https://user-images.githubusercontent.com/69448810/210339665-f3122a1a-3f38-4288-9354-f6389b0fa394.png)

**Comment by Abdullah-Akbar** [comment]
Find in Files results
![image](https://user-images.githubusercontent.com/89911730/210339958-c8425e4b-749a-4c75-b4f7-ebe847b9d4ea.png)

**Comment by ImranShaik065** [comment]
Thanks, will update the text.
