### ISSUE TITLE
[Report]: RBAC improvements

### ISSUE THREAD

**Issue by intesar** [apisec-inc/Support#214]
### Severity

UX Improvement

### What happened?

- [x] Red icons are missing in vulnerability details, wirelogs.
- [x] Explain the problem well: e.g., ROLE_ADMIN has unauthorized access to GET:/users. Add the appropriate message to the vulnerability details headline.
- [x] Manage RBAC Modal window - Add "Apply Changes" button; when clicked it should apply changes and automatically generate new playbooks
- [x] Add a section "How RBAC Works" to the RBAC description with 

"How does the RBAC category works?

APIsec creates an RBAC map of the role and endpoint permission model on the first RBAC scan. Reviewing the RBAC map and adjusting permissions per the API security requirements is highly recommended but not mandatory.

When you add new roles in APIsec, RBAC will baselines the new permissions in the RBAC map.

Future RBAC scans will continue to validate and enforce the RBAC permission model and report vulnerabilities if it detects any changes in the authorization model.
"

**Comment by intesar** [comment]
@MuqeedA - please prioritize this.

**Comment by shamiulla-apisec** [comment]
@intesar : I will work on this.

**Comment by atef-aa** [comment]
This is planned to complete by this week.

**Comment by MaimoonaFatima** [comment]
Verified in prod.
