### ISSUE TITLE
[Report]: Login to the APIsec Portal throws Service Unavailable error

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#215]
### Severity

Blocker (No Workaround Available)

### What happened?

We have experienced this issue in the past with a different customer. I'm sharing details with @AtifaFahmeen for fixing this error for one of our client's accounts whose credentials exist in two different tenants. Although one of the accounts is inactive, the user is still experiencing a Service Unavailable error.

**Comment by AtifaFahmeen** [comment]
The issue is resolved. @fersy02 Kindly confirm

**Comment by muqeetkhan20** [comment]
@fersy02 can you please close this ticket?

**Comment by fersy02** [comment]
The issue is fixed and the user is able to login.
