### ISSUE TITLE
[Report]: Update Slack Integration Documentation and Links

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#216]
### Severity

Bug

### What happened?

The Slack Integration requires a slack token, and the Slack credentials page is redirected to the [Legacy Tokens](https://api.slack.com/legacy/custom-integrations/legacy-tokens) page that is no longer supported
![image](https://user-images.githubusercontent.com/47815523/205341943-baac68d1-d70c-4239-a3c1-5347efca5b91.png)

**Comment by MaimoonaFatima** [comment]
Verified in stg.

**Comment by MaimoonaFatima** [comment]
Verified in prod.
