### ISSUE TITLE
[Report]: Test authentication button broken

### ISSUE THREAD

**Issue by SuddenDevelopment** [apisec-inc/Support#218]
### Severity

Bug

### What happened?

after entering the token curl script for authentication, I went to test it and it failes,

but it works in the scan. Thiss button just appears to be broken for anything but basic auth

![Screenshot 2022-12-16 at 2 25 41 PM](https://user-images.githubusercontent.com/138704/208174054-4fe28684-b3e7-4535-8242-2a7bbe81074c.png)

**Comment by SuddenDevelopment** [comment]
here's the script put into the header1:
`Authorization: Bearer {{@CmdCache | curl -s -d '{"username":"admin","password":"secret"}' -H "Content-Type: application/json" -H "Accept: application/json" -X POST https://ip/user/login | jq --raw-output ".info.token" }}`

**Comment by GhouseApisec** [comment]
@mmuqtaar, Can you pls update on this.

**Comment by Abdullah-Akbar** [comment]
@SuddenDevelopment 
1. Could you try with valid URL and creds?
2.  You will need to remove the '-s ' option to view the error message(s) as mentioned in the help text.
![image](https://user-images.githubusercontent.com/89911730/210465068-4f2dacf6-cd47-48af-84ea-26c06153a74a.png)

**Comment by SuddenDevelopment** [comment]
@Abdullah-Akbar 
they are valid, they worked in the scans
