### ISSUE TITLE
[Report]:  Comparison method violates its general contract!

### ISSUE THREAD

**Issue by SuddenDevelopment** [apisec-inc/Support#219]
### Severity

Bug

### What happened?

I keep getting this error from normal use of the product, I'm only enabling categories.

steps to reproduce.
- create a project
- go into categories 1 by 1 an enable a few
- error will appear when you go back to the list after a few

"Comparison method violates its general contract!"

![Screenshot 2022-12-19 at 11 05 49 AM](https://user-images.githubusercontent.com/138704/208468871-1283e450-2ba5-4d8d-8187-ce0d757278a2.png)

**Comment by AkaramAli** [comment]
We have identified the root cause of this issue and pushed a possible fix , It should be available in prod this week ( Possibly Thursday).

**Comment by muqeetkhan20** [comment]
thank you @AkaramAli - after long times we have finally identified the root cause; this should be a win.
Please apply QE label if it's fixed; we will try to test in next release.

**Comment by MaimoonaFatima** [comment]
Verified in prod.
