### ISSUE TITLE
[Bug]: Log4j category files false-positives

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#220]
### Severity

Blocker (No Workaround Available)

### What happened?

A few of our clients have reported issues with the Log4j category. All playbooks are failing and filing vulnerabilities that are false positives. Also, the assertion is missing in the wire logs to debug the issue.

![image](https://user-images.githubusercontent.com/47815523/210567340-4ca88773-1777-4d0a-84f0-df8500c4585a.png)

The issue is reproducible with the Net Banking API. This needs to be fixed as soon as possible, as we expect this will be observed by other clients too.

**Comment by fersy02** [comment]
@intesar @atef-aa - I hope this is being prioritized. Almost all our customers are highly concerned about this vulnerability getting reported in the daily scans.

**Comment by Mohammed-Luqman-Shareef** [comment]
@fersy02,
   We are working on it.  Will be fixed in a day or 2.  Will update here.

**Comment by muqeetkhan20** [comment]
@Mohammed-Luqman-Shareef QE has already reported this issue a week ago. Along with log 4j, few other categories like cors and tls missing the assertion.

https://github.com/apisec-inc/Engineering/issues/476

**Comment by MaimoonaFatima** [comment]
All test results are passing now because the safe server is returning null, spoke to @Mohammed-Luqman-Shareef . This will be fixed again.

**Comment by MaimoonaFatima** [comment]
Verified in prod.
