### ISSUE TITLE
[Cosmetic]: Project Reports Tab displays Vulnerability Trend with Unsorted Dates 

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#221]
### Severity

UX Improvement

### What happened?

The Vulnerability Trend Graph displays information on vulnerabilities in an unsorted date format that confuses our clients. Here are a few examples:

![image](https://user-images.githubusercontent.com/47815523/210943038-eaee0246-8fae-4c95-bbae-bd88e80d1dd6.png)

Another example:
![image](https://user-images.githubusercontent.com/47815523/210943141-84bffb2f-48f3-49d1-977c-d5283247579a.png)

The issue is reproducible in all tenants. 

Steps to reproduce:

1. Navigate to a project, reports
2. Scroll down to find the Vulnerability Trend graph

Expected Result:
The graph should display dates in a descending format.

Actual Result:
Currently, it is neither ascending nor descending.

**Comment by atef-aa** [comment]
@MuqeedA please look into this issue.

**Comment by muqeetkhan20** [comment]
@shamiulla-apisec if this is fixed, please add the QE label.

**Comment by Mohammed-Luqman-Shareef** [comment]
@shamiulla-apisec, pls share the endpoint 
@mmuqtaar apply sorting in the jap query.

**Comment by shamiulla-apisec** [comment]
@mmuqtaar : https://developer.apisec.ai/api/v1/projects/8aa0808884c0ecee0184c1d416bb09c6/vulgraph-snapshot?envId=8aa0808884c0ecee0184c1d416bc09c8

**Comment by GhouseApisec** [comment]
@mmuqtaar, could you pls check and update.

**Comment by GhouseApisec** [comment]
@mmuqtaar, Could you pls update whether sorting in the jap query is done.

**Comment by mmuqtaar** [comment]
@GhouseApisec there is already sorting on JPA query.even I'm not able to reproduce this in my local environment & dev

**Comment by shamiulla-apisec** [comment]
@mmuqtaar : Please have a look at the screenshot below, the data that is coming from the backend. Clearly can observe there is sequence missing in the date format. See below:

![image](https://user-images.githubusercontent.com/87168081/213185383-a2409f70-f9a1-42b5-b329-678bb025c7e2.png)

See the sequence in Playbooks trends dates:
![image](https://user-images.githubusercontent.com/87168081/213186350-dc7b769d-11c9-4090-bdb2-541611b0877b.png)

See the sequence missing in Vul Trends:
![image](https://user-images.githubusercontent.com/87168081/213186953-61205bf0-85a2-4b12-b582-7285b791745b.png)

So our observation is the unformatted data is coming from backend. Hope you understand.

@Mohammed-Luqman-Shareef Please check the above screenshots for reference.

**Comment by mmuqtaar** [comment]
@shamiulla-apisec Can you please check now

**Comment by YasmeenFatima** [comment]
Verified..

**Comment by YasmeenFatima** [comment]
Verified in prod..
