### ISSUE TITLE
[Bug]: Download All Vulnerabilities from the Vulnerabilities tab fails to download the file intermittently

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#222]
### Severity

Bug

### What happened?

One of our clients has reported a failure trying to download all Vulnerabilities file from the Vulnerabilities Tab on the Dashboard. The issue is intermittent and reproducible in multiple tenants where hundreds of vulnerabilities exist.

![image](https://user-images.githubusercontent.com/47815523/211270000-bb71258f-d682-413d-ba15-f40d1c98e6a6.png)

Once clicked on the Download All Vulnerabilities option, the file fails to download, and the option is greyed out unless the browser is refreshed.

**Comment by YasmeenFatima** [comment]
@ImranShaik065 , Download All vulnerabilities file is just showing the below message but file is not downloading
![image](https://user-images.githubusercontent.com/69448810/211796326-f9ee5351-2db7-4bca-8294-5e0accb1f225.png)

**Comment by YasmeenFatima** [comment]
Verified, working fine.

**Comment by Abid60** [comment]
issue is still reproducible

**Comment by AkaramAli** [comment]
> issue is still reproducible
@Abid60 , can you provide access to tenant ?

**Comment by AkaramAli** [comment]
@fersy02 - Kindly provide access to the tenant where this issue is still reproducible .

**Comment by Abid60** [comment]
@AkaramAli  - Successfully added to sunwest tenant kindly login as Sunwest//akram@apisec.ai

**Comment by AkaramAli** [comment]
@Abid60  , As discussed , I have checked , This issue is not reproducible in the tenant , Please check and close this ticket .

**Comment by fersy02** [comment]
The team has confirmed that we are no longer observing the issue.  @muqeetkhan20, you may close this ticket.
