### ISSUE TITLE
[Bug]: Search field stops working when we click on sort options of Categories Tab

### ISSUE THREAD

**Issue by Afra-APIsec** [apisec-inc/Support#223]
### Severity

Bug

### What happened?

When we sort categories by Status or Last Modified, the Search field stops working 

![image](https://user-images.githubusercontent.com/39483585/211500175-0eaa0217-58a4-4589-b75f-bb6f1ad12fec.png)

**Comment by fersy02** [comment]
We can live without sorting controls on the categories page as there are a lot of issues associated with them, but the search field is critical.

**Comment by shamiulla-apisec** [comment]
@muqeetkhan20 : Please verify this issue and update.

@fersy02 : Its fixed and will be available in next refresh.

**Comment by fersy02** [comment]
Thanks, @shamiulla-apisec.

**Comment by MaimoonaFatima** [comment]
Verified in prod.
