### ISSUE TITLE
[Bug]: All Scans & Scan Details page fails to display the count of closed vulnerabilities

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#224]
### Severity

Bug

### What happened?

Closed vulnerabilities fail to appear on the All scans and the detailed scans page:
![All Scans](https://user-images.githubusercontent.com/47815523/212057052-c3d35e77-d677-4406-9d7e-e84c1cc1dfb5.png)

![DetailScan](https://user-images.githubusercontent.com/47815523/212057479-4af0cfe2-b779-400e-9954-dfb7e56366cf.png)

Issue reproducible with the Netbanking API.

Steps to reproduce:
1. Run a Broken Authentication scan
2. Update the following assertion in the Broken Authentication category and regenerate playbooks:
```
Disallowed:@StatusCode == 401 OR @Response.errors == true
Allowed:@StatusCode == 200
```
3. Rerun the Broken Authentication scan

Actual Result:
Closed vulnerabilities appear on the dashboard but fail to reflect on the All scans page and the detailed scan page.

Expected Result:
Closed vulnerabilities should appear on the All scans page and the detailed scan page

**Comment by MuqeedA** [comment]
@Mohammed-Luqman-Shareef ,

- `/api/v1/runs/project/8aa0809185a051c00185a47bf1ba33b9?page=0&pageSize=25&sort=createdDate&sortType=DESC` -  is called on scan list page and it returns `task.issuesClosed = 0` 
- `/api/v1/runs/8aa0809085a96a7d0185a98b851e037e` - This API is called on scan details page and it is also returning `task.issuesClosed = 0`

**Comment by YasmeenFatima** [comment]
Verified in stg, working fine

**Comment by YasmeenFatima** [comment]
Verified in prod
