### ISSUE TITLE
[Bug]: Avoid redirection to the Playbooks page upon clicking save changes on any category details page

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#225]
### Severity

Bug

### What happened?

Upon modifying a category and clicking the Save Changes button redirects the user to the playbooks page, which is not an intended behavior. As the user might have to modify other categories before regenerating playbooks. However, Save and Regenerate playbooks may redirect the user and is working as expected.

**Comment by YasmeenFatima** [comment]
It is redirecting to the playbook page and also I'm getting below error inconsistently.
![image](https://user-images.githubusercontent.com/69448810/212895656-c5483e9e-5011-489a-92b1-bbb689ef8b1a.png)
![image](https://user-images.githubusercontent.com/69448810/212895590-ada6c66e-9a63-47f7-965e-1fad280152f6.png)

**Comment by MaimoonaFatima** [comment]
It is working fine.
