### ISSUE TITLE
[Bug]: RBAC includes disabled authentications and logs false positives

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#226]
### Severity

Blocker (No Workaround Available)

### What happened?

The initial RBAC scan includes inactive authentications and generates allowed and disallowed playbooks with inactive roles.

Steps to reproduce:

1. Register the net banking API with Default and ROLE_USER credentials
![image](https://user-images.githubusercontent.com/47815523/213675346-5468332e-88db-43fa-92ee-c9c1daff6c43.png)
2. Configure authentication and deactivate ROLE_PM and ROLE_ADMIN
![image](https://user-images.githubusercontent.com/47815523/213675508-9fa7329e-8bf2-45b1-800e-5e1aac1ef161.png)
3. Run an RBAC Scan 

Expected Result
Playbooks regenerated in the RBAC category should include only the active ROLE_* credentials.

Actual Result
Disallowed playbooks are generated with inactive roles.

**Comment by Mohammed-Luqman-Shareef** [comment]
Looking into it.

**Comment by MaimoonaFatima** [comment]
@fersy02 
We follow the below steps and it works as expected:
Steps:
1. Register the project
2. Set the RBAC roles to inactive
3. Regenerate the playbooks from the categories page
4. Scan RBAC

Result: Inactive roles doesn't appear in the playbooks as expected.
Looks like the playbooks regeneration (step 3) is missing in your flow.

**Comment by fersy02** [comment]
@Mohammed-Luqman-Shareef @muqeetkhan20 - It looks like there are gaps in the QA tests. When automap is set to true, there is no need to regenerate playbooks in a newly registered project. Please guide them.

**Comment by MaimoonaFatima** [comment]
@Mohammed-Luqman-Shareef, the inactive roles issue is fixed.

Found the other issue:
After the initial scan playbooks regenerated in the RBAC category does not generates the disallowed playbooks. we are unable to open the playbooks from the wire logs of scan history details page.

**Comment by Mohammed-Luqman-Shareef** [comment]
@MaimoonaFatima, This is as per design.   
RBAC works this way.  For the first time it creates playbooks for all disallowed.  After the first scan it identifies the actual results and creates the RBAC map.  Then it deletes all the playbooks and generates the playbooks as per the map.  So the allowed and disallowed playbooks will be as per the map.  You can close this ticket
