### ISSUE TITLE
[Bug]: Missing Assertion in Incremental Ids and Sensitive Data Exposure category leads to false positives 

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#228]
### Severity

Bug

### What happened?

The Sensitive Data Exposure and Incremental Ids are no longer active by default. However, we have been running them in multiple tenants for a long time. We have recently observed that the following assertions fail to render in the wirelogs, causing them to fail and file false positives.

Incremental Ids L1 and L2: 
- '@Response.$..id != @Numbers' (If Id field is missing in the Response body)

![image](https://user-images.githubusercontent.com/47815523/214585714-af184b2a-474b-483c-98b2-b563bc14cfa1.png)
![image](https://user-images.githubusercontent.com/47815523/214585246-e3341873-4f52-46e9-83e7-247ad04f1671.png)

Sensitive Data Exposure L1 and L2:
- '@Response.$..email == @Empty'
- '@Response.$..ssn == @Empty'

![image](https://user-images.githubusercontent.com/47815523/214586735-30bf7a67-794d-411c-8f7b-b32044cd60af.png)
![image](https://user-images.githubusercontent.com/47815523/214586978-ded5af4d-50de-4dc5-b0b5-00e3b6f6cc5e.png)

The issue is reproducible in the Netbanking API. The aforementioned categories should be activated as they are inactive by default.

**Comment by MaimoonaFatima** [comment]
We don't test inactive categories. Please let us know if these categories should be a part of our sanity?

**Comment by Mohammed-Luqman-Shareef** [comment]
These categories were active before PII category was introduced.  We made it inactive by default after enabling PII.
If any customer still uses this category, we need to include it in testing.   Need not be part of sanity testing, but in the regular detailed testing.

**Comment by fersy02** [comment]
@atef-aa @jaleelsyed  - Do you have any updates on this ticket?

**Comment by MaimoonaFatima** [comment]
Verified in prod.
