### ISSUE TITLE
Avoid timeout errors when running a scan

### ISSUE THREAD

**Issue by Abid60** [apisec-inc/Support#229]
### Severity

Bug

### What happened?

Scans are gettting timeout in one of the tenant, kindly look into it
![image](https://user-images.githubusercontent.com/53075600/220111444-cb7f8412-286d-4e42-b7c0-9a36da6d76e4.png)

**Comment by Mohammed-Luqman-Shareef** [comment]
Looking into it.

**Comment by Abedeen1** [comment]
Completed, Could you please verify.

**Comment by Abid60** [comment]
@Abedeen1  - still still reproducible, please find below ss.

https://user-images.githubusercontent.com/53075600/224658224-be8aaf54-011a-4005-a870-88c21aa2b488.png

**Comment by Abid60** [comment]
@Abedeen1  - Issue sill reproducible, please find below SS.

![image](https://user-images.githubusercontent.com/53075600/224658823-68267cba-9c9d-435d-82ca-bc6ff59abc47.png)

**Comment by fersy02** [comment]
#https://github.com/apisec-inc/Support/issues/229
