### ISSUE TITLE
[Vulnerability]: NoSQL Injection throwing false negatives

### ISSUE THREAD

**Issue by muqeetkhan20** [apisec-inc/Support#23]
### Severity

Medium

### What happened?

Injections values are valid but resulting as False Negatives with status code 200

**Comment by muqeetkhan20** [comment]
@Mohammed-Luqman-Shareef the false negative is arising due to 400 bad request in both dev and prod.
![image](https://user-images.githubusercontent.com/68276700/162730732-dcdaafb1-69f7-4852-b2b1-8acdd61dc7f4.png)

**Comment by Mohammed-Luqman-Shareef** [comment]
Data fixed.

**Comment by muqeetkhan20** [comment]
@Mohammed-Luqman-Shareef we are still reproducing 400 status code false negatives in both dev and prod.

**Comment by muqeetkhan20** [comment]
discussed with @Mohammed-Luqman-Shareef , it's  a data issue - closing the ticket
