### ISSUE TITLE
[Report]: Error while sending reports via emails

### ISSUE THREAD

**Issue by milan-cvejic** [apisec-inc/Support#230]
### Severity

Blocker (No Workaround Available)

### What happened?

When trying to send penetration report to email, email is not sent.

Request is sent to 
`
 https://cloud.apisec.ai/api/v1/reports/project/8a8081fd6a450126016a45e822ad17f7/pentest?fileType=PDF
`
 with the following response:

`{
  "requestId": "None",
  "requestTime": "2023-03-07T08:05:43.251+0000",
  "errors": true,
  "messages": [
    {
      "type": "ERROR",
      "key": "",
      "value": "all shards failed"
    }
  ],
  "data": null,
  "totalPages": 0,
  "totalElements": 0
}`

**Comment by Abdullah-Akbar** [comment]
@milan-cvejic can you try now? I just tested this .

**Comment by milan-cvejic** [comment]
@Abdullah-Akbar still the same error

**Comment by Abdullah-Akbar** [comment]
The request query parameter is "reportFileType" not "fileType". 
Refer: https://cloud.apisec.ai/swagger-ui.html#/reports-controller/getProjectReportUsingGET

**Comment by milan-cvejic** [comment]
@Abdullah-Akbar We are using web UI to export those reports. We are not executing those API calls programatically.

**Comment by Abdullah-Akbar** [comment]
oh ok, can you please attach a screenshot or a recording?

**Comment by milan-cvejic** [comment]
https://user-images.githubusercontent.com/64774929/223386381-dcfb46c9-09be-4e06-88c1-97a6bb3410b5.mov

@Abdullah-Akbar @MuqeedA here is screen recording

**Comment by milan-cvejic** [comment]
Any update on this?

**Comment by Abedeen1** [comment]
Sorry for the inconvenience, Today is public holiday in India, We are waiting to  get logs from System.

**Comment by Abedeen1** [comment]
@apisec-inc/devops  are needed to neutralise
![image](https://user-images.githubusercontent.com/87793504/223702190-048a47f9-2b87-483d-a2ad-6c4cf70ae864.png)

**Comment by Abedeen1** [comment]
please verify.

**Comment by milan-cvejic** [comment]
@Abedeen1 still doesn't work

**Comment by Abedeen1** [comment]
@milan-cvejic , if you wish to have hot-fix, please escalate to @Mohammed-Luqman-Shareef

**Comment by Abedeen1** [comment]
@milan-cvejic , prod migration is done, could you please verify now

**Comment by Abedeen1** [comment]
@Abdullah-Akbar 

Error gone, pdf report is not generating.

**Comment by Abedeen1** [comment]
@Abdullah-Akbar / @apisec-inc/devops   Received report logs @ Report service, but email not sent.
![Screenshot from 2023-03-10 18-10-22](https://user-images.githubusercontent.com/87793504/224318556-a7b43962-58a2-468a-8472-16a2ba734a42.png)

**Comment by Abdullah-Akbar** [comment]
The report is getting received in the email albeit with a long delay.

**Comment by fersy02** [comment]
CC: @APIStacey

**Comment by Abedeen1** [comment]
@fersy02 , We are in process of Analysing the Event. Will Optimise the Performance of the Report.

**Comment by Abedeen1** [comment]
@Mohammed-Luqman-Shareef ,
please find the log for PENTEST Report
https://console.cloud.google.com/logs/query;query=%228a8081fd6a450126016a45e822ad17f7%22;timeRange=2023-03-17T08:49:00.672Z%2F2023-03-17T11:23:02.673Z;summaryFields=textPayload:false:32:beginning;cursorTimestamp=2023-03-17T10:21:08.584796231Z?authuser=1&project=fx-labs

**Comment by Abedeen1** [comment]
@Mohammed-Luqman-Shareef , It is taking 30 minutes to Generate Pentest Report.

please let me know, if you wish to further tune it.

**Comment by Abedeen1** [comment]
Log https://console.cloud.google.com/logs/query;query=%228a8081fd6a450126016a45e822ad17f7%22;timeRange=2023-03-20T11:48:09.000Z%2F2023-03-20T12:20:01.000Z;summaryFields=textPayload:false:32:beginning;cursorTimestamp=2023-03-20T12:17:57.435781450Z?authuser=1&project=fx-labs

**Comment by Abedeen1** [comment]
@milan-cvejic , Can we close this ticket.?

**Comment by APIStacey** [comment]
Closing this ticket as it has been solved. If it is still an issue, please open via the newly communicated support process.
