### ISSUE TITLE
[Bug]: Scanner not working on AWS Fargate

### ISSUE THREAD

**Issue by intesar** [apisec-inc/Support#26]
### Severity

Blocker

### What happened?

Please deploy and certify the Apisec scanner on AWS Fargate.

**Comment by mohdrashid1** [comment]
Sure will do that need access of AWS Cloud

**Comment by intesar** [comment]
@mohdrashid1 try to update by EOD today.

**Comment by mohdrashid1** [comment]
@intesar InshaAllah will completed it soon

**Comment by syedimranapisecai** [comment]
@intesar bhai

@sarasheed  just checked deployment of scanner from prod (cloud.fxlabs.io) server to AWS cloud, it  got created and scanner is working perfectly.  

Scanner got created on aws ec2 instance, but not on AWS fargate.

I believe we didn't use AWS fargate previously for scanner deployment?

Do we need to test scanner deployment with AWS Fargate?

**Comment by sarasheed** [comment]
![image](https://user-images.githubusercontent.com/30456479/159867519-5d640cb8-ba13-49ec-aa3a-ba590ddcaf87.png)

**Comment by fersy02** [comment]
As discussed in today's meeting, we haven't certified scanner deployment on a serverless architecture such as AWS Fargate. Please certify and share the documentation steps.

**Comment by syedimranapisecai** [comment]
Deployed a scanner in AWS using Far Gate, it's running successfully and playbooks are also getting scanned on that scanner.

Will prepare steps for it.

**Comment by mohdrashid1** [comment]
Documentation Steps are Ready

**Comment by mohdrashid1** [comment]
Documentation Steps are Ready

Please check and update us if any changes required

[Deploy AWS Fargate.pdf](https://github.com/apisec-inc/Support/files/8359723/Deploy.AWS.Fargate.pdf)

**Comment by intesar** [comment]
@mohdrashid1 nice write-up. Please convert this into a knowledge post.

**Comment by mohdrashid1** [comment]
@intesar sure i will do it

**Comment by muqeetkhan20** [comment]
AWS fargate deployed and tested in dev environment. 
scanned all the categories in one go. 
performance wise it's good.

**Comment by Abdullah-Akbar** [comment]
https://apisec-inc.github.io/releases/apisec-AWS-Fargate/

**Comment by sarasheed** [comment]
Done.
