### ISSUE TITLE
[Bug]: Do not restrict the spaces (in special characters) for project name 

### ISSUE THREAD

**Issue by muqeetkhan20** [apisec-inc/Support#27]
### Severity

Blocker

### What happened?

While registering or editing the project from any source like Register API, Register from Gateway, Free Pentest - please allow the spaces. For special characters input, let's give a right message in the dialog window.

**Comment by Abedeen1** [comment]
@muqeetkhan20 

Could you please review the validation @ https://regexr.com/6ig0k
