### ISSUE TITLE
[Bug]: Payloads not updating for ABAC_3

### ISSUE THREAD

**Issue by muqeetkhan20** [apisec-inc/Support#28]
### Severity

Non-Blocker

### What happened?

Payloads are not updating for ABAC_3

**Comment by Mohammed-Luqman-Shareef** [comment]
@muqeetkhan20 This issue was discussed couple of months back.  ABAC3 needs major enhancements to make it fully automatic.   
ABAC3 enhancement is on Hold and the ticket was moved to backlogs. 
As of now it is used rarely where users go and edit the payload whereever needed.

**Comment by muqeetkhan20** [comment]
Moved this ticket to backlog....
