### ISSUE TITLE
[Bug]: Avoid generating injection playbooks for empty payloads and payloads without string fields.

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#30]
### Severity

Non-Blocker

### What happened?

Avoid generating an injection playbook that doesn't contain an injection in the request body due to an empty payload or payload without a string field. The current behavior creates noise and increases the number of error playbooks. It also gives the impression that onboarding requires enormous effort and time.

Currently, all injection categories follow this trend, and it should apply to all injection categories.

**Comment by muqeetkhan20** [comment]
@fersy02 verified in dev. We have few put method playbooks with string fields in the payloads but with NO injection values. Don't you wish to avoid these playbooks? few examples over here...

ApiV1PrimaryAccountWithdrawAmountIdPutBodyParamLinuxCommandInjection
ApiV1PrimaryAccountDepositAmountIdPutBodyParamLinuxCommandInjection
ApiV1PrimaryAccountPrimaryAccountPutBodyParamLinuxCommandInjection
ApiV1PrimaryAccountPrimaryAccountPutBodyParamLog4jInjection
ApiV1PrimaryAccountWithdrawAmountIdPutBodyParamLog4jInjection
ApiV1PrimaryAccountDepositAmountIdPutBodyParamLog4jInjection
ApiV1PrimaryAccountPrimaryAccountPostBodyParamLog4jInjection

**Comment by Mohammed-Luqman-Shareef** [comment]
These playbooks don't have injections and are not generated.  
@muqeetkhan20 Please delete and create playbooks in that category and verify.

**Comment by muqeetkhan20** [comment]
@Mohammed-Luqman-Shareef tested with the new project, all looks good...thanks
