### ISSUE TITLE
[Feature]: Provision to add a Reviewed Tag and Comments into a vulnerability

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#31]
### Please describe your problem?

Most of our clients would like to review and add comments to a vulnerability in APIsec to save time and effort. This is especially required when we are dealing with a lot of projects or vulnerabilities in a project.

### How important is this feature?

Very Important

### Describe the solution you'd like?

When we click a vulnerability in the dashboard for more details. We have a field for comments, it must be editable and introduce a tag to mark them as reviewed.

**Comment by Abedeen1** [comment]
@fersy02 ,

Tag, Comments are as per profile / simply on playbook?

**Comment by Abedeen1** [comment]
@fersy02 ,

Tag, Comments are as per profile / simply on playbook?

**Comment by Abedeen1** [comment]
@Mohammed-Luqman-Shareef 


Tag, Comments are as per profile / simply on playbook?

**Comment by Abedeen1** [comment]
@fersy02 ,
Code is ready,
![image](https://user-images.githubusercontent.com/87793504/161493389-d0033c52-2b94-4a8d-8c0b-59f3e70b38ec.png)

After click on review
![image](https://user-images.githubusercontent.com/87793504/161493483-175c7d8d-6669-4f67-ab51-30c3dfeb7fda.png)

After click on ok
![image](https://user-images.githubusercontent.com/87793504/161493886-7c2b39bf-4d3a-4edc-a432-52d3aa11989c.png)

**Comment by Abedeen1** [comment]
@Mohammed-Luqman-Shareef ,

Can we move the code to Repository.

**Comment by Abedeen1** [comment]
Confirmation dialog :
![image](https://user-images.githubusercontent.com/87793504/161759106-98376f10-c2ef-4717-8698-2701ac596438.png)

**Comment by muqeetkhan20** [comment]
@Abedeen1 experiencing a bug "resource key already exist". please look into it.

**Comment by Abedeen1** [comment]
@muqeetkhan20 , Could you please share steps to reproduce the error.

**Comment by Abedeen1** [comment]
Fixed, Please varify.

**Comment by muqeetkhan20** [comment]
@Abedeen1 can we sync the comments with the issue trackers? We can start with Jira at least.

**Comment by Abedeen1** [comment]
Can we sync now

**Comment by muqeetkhan20** [comment]
@Mohammed-Luqman-Shareef I have discussed this with @Abedeen1 on bi-directional.
We have the comment field in all the issue trackers like Jira, Github etc. If we can sync our comments with the issue tracker tools that would be great. 

@Abedeen1 do you have any update on this?

**Comment by Abdullah-Akbar** [comment]
@muqeetkhan20 @Abedeen1 
Our issue tracker integration is uni-directional by design.  Changes done to tickets in issue trackers will not be reflected in APIsec.

**Comment by muqeetkhan20** [comment]
@Abdullah-Akbar agreed, can we put efforts to change it to bi-directional? or skip for now?

**Comment by jaleelsyed** [comment]
Let's not over engineer on this feature, we have couple of other issue trackers as well which might not have commenting feature, let's try to maintain the uniformity across issue trackers.
And address the customer reported issues.

**Comment by muqeetkhan20** [comment]
Customers are using only Jira as of now. Let's discuss this on our team call.

**Comment by Abdullah-Akbar** [comment]
> @Abdullah-Akbar agreed, can we put efforts to change it to bi-directional? or skip for now?

not a valid requirement. it should be uni-directional only.

**Comment by muqeetkhan20** [comment]
@Abdullah-Akbar thanks for the clarification. Appreciate it....

Will close the ticket....
