### ISSUE TITLE
[Bug]: Unsecured playbooks are missing against a few playbooks during project registration

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#32]
### Severity

Non-Blocker

### What happened?

Recently started observing this issue, upon project registration a few unsecured playbooks are failing to generate. When we regenerate the missing playbooks are added.

**Comment by Abdullah-Akbar** [comment]
@muqeetkhan20 I have tested this 3 times in K8s env. It is working fine with the fix. Pls verify.

**Comment by muqeetkhan20** [comment]
yes, its fixed now
