### ISSUE TITLE
[Support]: Document OAS Generation libraries

### ISSUE THREAD

**Issue by intesar** [apisec-inc/Support#33]
### Severity

Blocker

### What happened?

As previously stated, you will offer information on how to use open source tools to assist developers in generating API specifications. Our bank mostly utilizes [ASP.NET](http://asp.net/) (Core & C#), Java, and a few Pythons. Kindly share with us the tool and instructions for generating the specification, so that once we have the specification file, you can walk us through the APIsec portal access and work flow.

@Abdullah-Akbar Can you please do a basic write-up on this? Additionally, we can convert this into a blog post or add to our documentation for future references. Please revert at the earliest.

**Comment by Abdullah-Akbar** [comment]
Yes, we are preparing a short article listing libraries and other resources which can help in generating OpenAPI specification documentation for existing API implementations.

**Comment by Abdullah-Akbar** [comment]
@intesar V1 of the article is available [here](https://docs.google.com/document/d/1D4uF_TZnqkTnWoNSGMYW8wTGJHAe2lw847Zz1tQ39gk/). Hope it suffices for our requirement.

**Comment by Abdullah-Akbar** [comment]
Blog published: [Generating OpenAPI Specification (OAS) documentation for your REST APIs](https://www.apisec.ai/blog/generating-openapi-specification-oas-documentation-for-your-rest-apis)
