### ISSUE TITLE
[Bug]: APIsec Summary Report

### ISSUE THREAD

**Issue by muqeetkhan20** [apisec-inc/Support#34]
### Severity

Non-Blocker

### What happened?

- [x] OWASP coverage table is not updating the values.
- [x] Unable to download pdf, if downloaded the check mark icon is missing when we click the download pdf button.
- [x] Change criticality to severity.
- [x] Pdf report is showing N, it should be N/A

**Comment by muqeetkhan20** [comment]
@MuqeedA tested in dev. all the above issues are fixed.
The another issue is with the ABAC generated tests count in incorrect. please verify.

**Comment by Mohammed-Luqman-Shareef** [comment]
@AtifaFahmeen, the incorrect playbook count in the reports is because it is not counting the Init and Cleanup playbooks (tyep ABSTRACT).  Can you please update the queries wherever needed?

**Comment by muqeetkhan20** [comment]
We have created a new ticket for the count mismatch...Hence, closing this ticket.
https://github.com/apisec-inc/Engineering/issues/204
