### ISSUE TITLE
[Feature]: API to get vulnerabilities logged by a particular scan

### ISSUE THREAD

**Issue by Abdullah-Akbar** [apisec-inc/Support#35]
### Please describe your problem?

We are triggering scans using the CI-CD integration. We need an API to get the new vulnerabilities logged by a particular scan. We are particularly interested in the severity level of the vulnerabilities logged by the scan.

### How important is this feature?

Very Important

### Describe the solution you'd like?

An API to help us detect vulnerabilities logged as part of a particular scan.

**Comment by fersy02** [comment]
Additional information requested by the client: 
Return a list of issues in a json array including the following parameters: 
- Endpoint path
- Security category name
- Playbook name
- Severity of the issue 
- CVSS Score

**Comment by Abdullah-Akbar** [comment]
@muqeetkhan20  API implemented and available in dev environment.
Sample usage: api/v1/projects/4028811572fba5720172fba96573000c/run/4028811572febb8a0172fec8daa801ab/auto-suggestions/active?page=0&pageSize=10

**Comment by muqeetkhan20** [comment]
@Abdullah-Akbar It's throwing white label error...
![image](https://user-images.githubusercontent.com/68276700/161520062-26aa6807-b348-49a2-b51f-531cfb69c0c0.png)

**Comment by muqeetkhan20** [comment]
@Abdullah-Akbar tested in dev after the path spelling correction. all good
