### ISSUE TITLE
[Bug]: Platform UI improvements

### ISSUE THREAD

**Issue by intesar** [apisec-inc/Support#49]
### Severity

Blocker

### What happened?

- [x] Replace "Help & Support" footer link with https://github.com/apisec-inc/Support/issues
- [x] Project Registration button "Register & Activate Coverage" change to "Register" for simplicity and consistency
- [x] Advanced Project Registration button "Validate & Register" change to "Register" for simplicity and consistency
- [x] Rename "Open Vulnerabilities Details" on Project dashboard to "Open Vulnerabilities"
- [x] New user create button change to "Create"
- [x] Replace blue color for Project/dashboard second-row tiles with a muted color
- [x] Open Vulnerabilities section on Project/dashboard show user-friendly name for category column- **Backend**
- [x] Playbooks list view show user-friendly name for category column- **Backend**
- [x] Change the text in the report code "Check out our latest releases and exciting new features at https://apisec-inc.github.io/releases/" to "Check out our latest releases and exciting new features for the month of [February] at https://apisec-inc.github.io/releases/." @Abdullah-Akbar

**Comment by Abdullah-Akbar** [comment]
![image](https://user-images.githubusercontent.com/89911730/161656132-fb3c9a43-7a1d-4081-a8d4-5395049d6d3d.png)

**Comment by intesar** [comment]
> ![image](https://user-images.githubusercontent.com/89911730/161656132-fb3c9a43-7a1d-4081-a8d4-5395049d6d3d.png)

I don't think we need to keep square brackets around the month name i.e. [March] should just "March"

**Comment by Abdullah-Akbar** [comment]
![image](https://user-images.githubusercontent.com/89911730/161874836-3ad415da-5d8d-491e-8a35-3dd10b1b6b14.png)

**Comment by intesar** [comment]
> ![image](https://user-images.githubusercontent.com/89911730/161874836-3ad415da-5d8d-491e-8a35-3dd10b1b6b14.png)

The releases link looks very generic. Is it possible to make the month a link?

**Comment by Abdullah-Akbar** [comment]
> The releases link looks very generic. Is it possible to make the month a link?

The mailer is currently plain text by design. For hyperlinks, we will need to change its entire format to HTML.

**Comment by muqeetkhan20** [comment]
Verified all the UI improvements, the backend is pending...

**Comment by Abdullah-Akbar** [comment]
backend changes available in dev env.

**Comment by muqeetkhan20** [comment]
tested in prod, all looks good
