### ISSUE TITLE
[Bug]: Rate-limit assertions are invalid

### ISSUE THREAD

**Issue by intesar** [apisec-inc/Support#53]
### Severity

Blocker

### What happened?

Checkout this

This should not have been a failed result:
06:54:39 [E] [ASGRAuthenticated] : Assertion [@ResponseHeaders.X-RateLimit-Limit != @Empty AND @ResponseHeaders.X-RateLimit-Limit != null] resolved-to [null != @Empty AND null != null] result [Failed]

**Comment by muqeetkhan20** [comment]
@intesar this bug was raised by @MaimoonaFatima a month ago on our QA call, we logged it in our backlog and unfortunately we didn't get chance to discuss with engineering due to k8s on-prem priorities - fyi

**Comment by Mohammed-Luqman-Shareef** [comment]
Why  should **null != null**  pass ?
[null != @empty AND null != null] result [Failed]

**Comment by intesar** [comment]
> @ResponseHeaders.X-RateLimit-Limit != @empty AND @ResponseHeaders.X-RateLimit-Limit != null

The assertion should be. It should fail in case of missing X-RateLimit-Limit header.
@ResponseHeaders.X-RateLimit-Limit != @Empty OR @ResponseHeaders.X-RateLimit-Limit != null

We should just not look for this header instead expand the lookup for even more names like

Commonly used header field names are:

X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset;
X-Rate-Limit-Limit, X-Rate-Limit-Remaining, X-Rate-Limit-Reset.

There are variants too, where the window is specified in the header field name, eg:
x-ratelimit-limit-minute, x-ratelimit-limit-hour, x-ratelimit-limit-day
x-ratelimit-remaining-minute, x-ratelimit-remaining-hour, x-ratelimit-remaining-day

Here are some interoperability issues:
X-RateLimit-Remaining references different values, depending on the implementation:

seconds remaining to the window expiration
different headers, with the same semantic, are used by different implementers:

X-RateLimit-Limit and X-Rate-Limit-Limit
X-RateLimit-Remaining and X-Rate-Limit-Remaining
X-RateLimit-Reset and X-Rate-Limit-Reset

Here are the references
https://www.ietf.org/archive/id/draft-polli-ratelimit-headers-02.html

- [ ] Notice they all start with "x-rate*". Instead we should look for these headers and in case of none we fail it.

**Comment by Mohammed-Luqman-Shareef** [comment]
Added feature to evaluate the assertion with wild char '*' for all the header names.
Now you can have an assertion as 
@ResponseHeaders.keyword* == value
@ResponseHeaders.*keyword == value
@ResponseHeaders.*keyword* == value

The Evaluation if finds the Header with matching name returns the values all such headers within square brackets [ ].
The change will be available in the next release.
After the release
    For RateLimit Categories the assertions will be updated as 
        - '@ResponseHeaders.X-RateLimit* != @Empty AND @ResponseHeaders.X-RateLimit* != null'
    This applies automatically to the new APIs registered going forward.
    For existing APIs the assertions can be updated via the categories page.

**Comment by muqeetkhan20** [comment]
@Mohammed-Luqman-Shareef this is giving a failed result again...no new values found in ResponseHeaders

**Comment by Mohammed-Luqman-Shareef** [comment]
You need an API which returns these headers to test this one.
The change here is now we are supporting '*' wild card for partial header name search and updated the assertions in these two categories to check for any header starting with X-RateLimit.

**Comment by muqeetkhan20** [comment]
@Mohammed-Luqman-Shareef Would you be able to provide such API for testing purpose?

**Comment by muqeetkhan20** [comment]
@Mohammed-Luqman-Shareef we are unable to test this scenario through NB app. Should we close this ticket or it's possible to provide any such API?

**Comment by Mohammed-Luqman-Shareef** [comment]
Lets close this ticket now.
