### ISSUE TITLE
[Feature]: DELETE Endpoints in the RBAC Scan to use Random UUIDs instead of variables

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#63]
### Please describe your problem?

Recently, we experienced an incident that deleted pre-existing customer records during the POV.
When running a Role-based Access Control (RBAC) scan, the API uses test data from the variables. APIsec generates a numeric id: 12345. if this is updated to a pre-existing id then it might be deleted from the database as we execute RBAC with multiple roles.

### How important is this feature?

Very Important

### Describe the solution you'd like?

The delete endpoints should use Random data instead of variables.
e.g. /api/v1/users/{id} 

Expected 
Path: /api/v1/users/{{@RandomUUID}} instead of {{@Var.id}}

**Comment by intesar** [comment]
@Mohammed-Luqman-Shareef Skip variables like {{@Var.id}} for DELETE operations for all categories except ABAC.

**Comment by muqeetkhan20** [comment]
tested in dev env, looks good

**Comment by muqeetkhan20** [comment]
tested in prod, looks good
