### ISSUE TITLE
[Bug]: Open Vulnerability Graph on the Dashboard doesn't load automaticatically

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#64]
### Severity

Medium

### What happened?

On the dashboard, we have an Open Vulnerabilities graph that fails to load automatically and requires refreshing the page.
![image](https://user-images.githubusercontent.com/47815523/164032247-484b7c6f-a081-4619-a708-f87ec2e386ce.png)

After Refreshing the page:
![image](https://user-images.githubusercontent.com/47815523/164032382-aec62216-ec17-4105-838a-c0b4d9e66a49.png)

**Comment by muqeetkhan20** [comment]
This bug is not reproducible. I tried multiple times...

![image](https://user-images.githubusercontent.com/68276700/164120924-6bbaa413-092a-4356-8180-97333e85530d.png)

**Comment by MuqeedA** [comment]
@fersy02 , Can you please provide access to this tenant. Thanks.

**Comment by fersy02** [comment]
I just tried in the new incognito browser and observed the following in the Alkami tenant:
![image](https://user-images.githubusercontent.com/47815523/164169436-8f057f5a-f998-4a99-a670-c875ce764c57.png)

**Comment by fersy02** [comment]
After refreshing the browser:
![image](https://user-images.githubusercontent.com/47815523/164169648-9966ca0f-3a54-4351-bb3b-0b579d513182.png)

**Comment by fersy02** [comment]
Added both muqeet@apisec.ai and muqeed@apisec.ai.

**Comment by muqeetkhan20** [comment]
I have verified in Alkami tenant, worked fine for me...the below results without any refresh,
![image](https://user-images.githubusercontent.com/68276700/164186893-aa7a35dd-b28d-4e2d-8e7b-1f71a76418a3.png)

**Comment by fersy02** [comment]
Can you please try this in the Yourbind2 tenant?
![image](https://user-images.githubusercontent.com/47815523/164189819-07139d09-c8d4-4f3d-8b5c-623b11a663e0.png)

**Comment by muqeetkhan20** [comment]
loaded the page without any refresh..

![image](https://user-images.githubusercontent.com/68276700/164206444-0114a696-ba5d-412e-92e2-43e36c5896dd.png)

**Comment by fersy02** [comment]
The issue seems intermittent for a few vulnerabilities, and if the number of vulnerabilities is more, the pie chart doesn't work even after refresh.
