### ISSUE TITLE
[Feature]: Please increase VAmPI token lifetime

### ISSUE THREAD

**Issue by hAPI-hacker** [apisec-inc/Support#65]
### Please describe your problem?

I believe the current token timeout is set too low. Since we plan on using VAmPI for demos/workshops, it would help out if the token lifetime could be set to something much longer.

### How important is this feature?

Very Important

### Describe the solution you'd like?

Please increase the token life to a day. Instructions for customizing token timeout can be found at the bottom of (https://github.com/erev0s/VAmPI).

**Comment by sarasheed** [comment]
Increased token validity to 86400 sec (24hr).
