### ISSUE TITLE
[Bug]: Incomplete Command displayed on the CI/CD Jenkins page

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#66]
### Severity

Medium

### What happened?

Since we changed the UI, the Jenkins command has changed and missing some critical details:
![image](https://user-images.githubusercontent.com/47815523/164390471-d297c464-7a45-4a45-a067-4b1b7d2337d0.png)

Expected:
wget https://raw.githubusercontent.com/apisec-inc/apisec-scripts/master/apisec_job_invoke_script.sh?token=AVOLEQ4FVVPJJ3DPAME4JELBS56SI -O apisec_job_invoke_script.sh;bash apisec_job_invoke_script.sh --username {Username} --password {Password} --project Hayaat --profile Master --scanner Super_1 --emailReport true --reportType RUN_SUMMARY  

Current:
wget https://raw.githubusercontent.com/apisec-inc/apisec-scripts/master/apisec_job_invoke_script.sh?token=AVOLEQ4FVVPJJ3DPAME4JELBS56SI -O apisec_job_invoke_script.sh;bash apisec_job_invoke_script.sh --username {Username} --password {Password}

**Comment by shahidabdul** [comment]
this issue fixed
