### ISSUE TITLE
[Bug]: Download Project/All Projects Vulnerabilities Fail with an Error

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#67]
### Severity

Blocker

### What happened?

A customer has reported that they are not able to download the vulnerabilities list in the XLSX format from the Dashboard. Tried this functionality in the APIsec tenant with the NetBanking project and experienced the same error:

![image](https://user-images.githubusercontent.com/47815523/167649565-103bb046-be9c-40de-a708-c00ca0d06fba.png)

**Comment by muqeetkhan20** [comment]
QA team have identified this bug at the time of dev sanity. Reported to @apisec-inc/engineering and it should be fixed at the earliest.

**Comment by shahidabdul** [comment]
getting null data from the backend
https://developer.apisec.ai/api/v1/projects/8a7481f97f5fff3e017f638c11040a46/auto-suggestions-download/active?envId=8a7481f97f5fff3e017f638c11070a48&severity=all&category=All

**Comment by muqeetkhan20** [comment]
If we have many projects, then all projects report is failing, for few projects we are good.
I am closing the ticket.

**Comment by mmuqtaar** [comment]
@Abedeen1
