### ISSUE TITLE
[Bug]: UI: Unable to register the project without API

### ISSUE THREAD

**Issue by muqeetkhan20** [apisec-inc/Support#68]
### Severity

Major

### What happened?

![image](https://user-images.githubusercontent.com/68276700/167676856-f1d4e0ca-2401-4d49-bb73-591728c77b3d.png)

**Comment by Mohammed-Luqman-Shareef** [comment]
You can't register an API without providing the spec.  
@MuqeedA Disable the register button if neither the spec url nor the file is provided.  Or give a proper error msg.

**Comment by muqeetkhan20** [comment]
@Mohammed-Luqman-Shareef this feature was in place, we were allowing the customers to register the project without API. Did we get a request to restrict the registration without API? I don't even see the OAS editor in details page. Do we have a ticket for this?

**Comment by Mohammed-Luqman-Shareef** [comment]
If it is intended feature and we want customers to use it then let's fix the bug.
@mmuqtaar can you add and empty/null check before spec validation.

**Comment by muqeetkhan20** [comment]
yes, it's intended feature.
