### ISSUE TITLE
[Bug]: Footer links not working (404 error)

### ISSUE THREAD

**Issue by muqeetkhan20** [apisec-inc/Support#69]
### Severity

Medium

### What happened?

Training videos link not working (https://www.apisec.ai/training-videos)
Documentation link is not working (https://www.apisec.ai/documentation)

**Acceptance Criteria:**

Please point to the new documentation link: https://apisec-inc.github.io/documentation/

**Comment by amer-apisec** [comment]
1.Documentation link is still throwing 404 error.
2.In Training videos link Media and Webinars post throwing 404 error.

**Comment by ImranShaik065** [comment]
@amer-apisec webinars post is not considered as footer link.

**Comment by amer-apisec** [comment]
@ImranShaik065 if any person wants to look into webinars he would face 404 error.

**Comment by amer-apisec** [comment]
verified in dev env working fine.
