### ISSUE TITLE
[Bug]: Playbook generation failing due to payload size

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#71]
### Severity

Blocker

### What happened?

Payload size restricts generating playbooks in all categories. If the payload size is too large, a project is registered, and only the Unsecured category playbooks are generated initially. When a user tries to create playbooks in multiple categories, the user is informed to select fewer categories. 

![image](https://user-images.githubusercontent.com/47815523/168001044-5b836e0d-ecf7-4b7a-8ef7-ccdfe976362b.png)

This is still not valid in a few scenarios as the user has to select only a single category to generate playbooks.
Additionally, we have come across an API that is failing to generate playbooks even with a single category.

**Comment by Mohammed-Luqman-Shareef** [comment]
@fersy02 can you pls share the spec which fails for single category due to payload size.

**Comment by fersy02** [comment]
@Mohammed-Luqman-Shareef, I had a call and shared the OAS on May 12. I will send an email right away.
