### ISSUE TITLE
[Bug]: Unable to create new playbook if you edit category name, throws an error

### ISSUE THREAD

**Issue by muqeetkhan20** [apisec-inc/Support#72]
### Severity

Medium

### What happened?

- [x] While creating or cloning a new playbook, if you edit category name to some new name (Custom1), it's throwing an error. 
- [x] The new playbook display name should be "custom", but it has a different name HTTP header.

**Comment by muqeetkhan20** [comment]
We will discuss...

**Comment by muqeetkhan20** [comment]
@Mohammed-Luqman-Shareef as per our discussion, are we going to fix this?

**Comment by Mohammed-Luqman-Shareef** [comment]
#1. @muqeetkhan20 When you edit a playbook you can't randomly give any name to the category.  A Category with that name should exist in the Security Categories.  For any new playbook which doesn't fall under any existing categories you can specify as "Custom".
#2 is fixed.

**Comment by MaimoonaFatima** [comment]
We have tried to give the  category a random name and its allowing us to save.
![image](https://user-images.githubusercontent.com/72252407/176611609-4b69a76e-868e-4764-8894-ef5d41e7411d.png)

**Comment by MaimoonaFatima** [comment]
Tested in Dev environment, working fine.
