### ISSUE TITLE
[Bug]: Unable to register an OAS via Apigee Gateway

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#73]
### Severity

Blocker

### What happened?

We are able to fetch the list of OpenAPI Specification from the Apigee edge gateway. After selecting and registering the API definition we get a confirmation but it fails to register the specification and there is no information in the Activities to debug.

![image](https://user-images.githubusercontent.com/47815523/168288469-ba44872f-2440-44ea-82af-8e9f9f860c54.png)

![image](https://user-images.githubusercontent.com/47815523/168288209-c6fe2b7f-089b-4517-9351-3dc39600e0b1.png)

![image](https://user-images.githubusercontent.com/47815523/168288627-665a3540-4d35-4294-a8d7-80d19a8d57d0.png)

**Comment by abdul-hai-apisec** [comment]
The spec is not having any issues...project name is containing the special character '-' due to which project creation failed.

I was able to create the project with that spec content manually with a different name.

**Comment by fersy02** [comment]
Can we accept special characters in the project name?
Secondly, we need informative error messages and logs on the activities page to debug such issues in the future.

**Comment by Abdullah-Akbar** [comment]
reg. special chars in the project name, let me check the impact.
The error messaging is being improved.

**Comment by muqeetkhan20** [comment]
@Abdullah-Akbar did we allow special characters in the project name?

**Comment by Abdullah-Akbar** [comment]
> @Abdullah-Akbar did we allow special characters in the project name?

No we did not. APIsec does not allow special characters in the project name. For API gateway imports however, special chars in the project name will be replaced with a single space.

**Comment by MaimoonaFatima** [comment]
The messaging is improved now.
![image](https://user-images.githubusercontent.com/72252407/168802233-40ecc3fd-44bb-480d-bd39-e588947a488f.png)

**Comment by Abdullah-Akbar** [comment]
In case the spec name contains special characters, they will be replaced automatically with empty space character. [@MuqeedA is working on this]

**Comment by Abdullah-Akbar** [comment]
> When registering via API gateways, in case the spec name contains special characters, they will be replaced automatically with empty space character. [@MuqeedA is working on this]

@MaimoonaFatima this is available in dev env now.

**Comment by muqeetkhan20** [comment]
We are good now..
