### ISSUE TITLE
[Bug]: Unable to login when 2FA enabled

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#75]
### Severity

Medium

### What happened?

A client has reported that he cannot log in with the 2FA enabled. He is using Google Authenticator and has multiple accounts.
We tried to log in with Google Authenticator having a single account, and it works fine, but with multiple accounts in Google Authenticator, it throws an error. Currently, he can access his account after installing Google Authenticator on an alternate phone that has a single account in the Google Authenticator.

**Comment by Abdullah-Akbar** [comment]
What is the make/model of the handset and OS?

**Comment by fersy02** [comment]
The customer is using an iPhone.

**Comment by jaleelsyed** [comment]
Refer to point **My Google Authenticator codes don’t work.**

https://support.google.com/accounts/answer/185834?hl=en#zippy=

**Comment by fersy02** [comment]
Today, I received a similar complaint from a different client that he needs help logging in when 2FA is enabled. He is using Google Authenticator on an IOS device.

**Comment by FidaUrRahman** [comment]
Hi @fersy02 , @jaleelsyed  
QE findings are 
1 - 2FA code from Google authenticator , Microsoft authenticator and Twilio authy on Android device , it is working fine 
2 - 2FA code from Microsoft authenticator and Twilio authy on an IOS device , it is working fine
3 - 2FA code from Google authenticator on an IOS device , it is not working

**Comment by fersy02** [comment]
@Mohammed-Luqman-Shareef @atef-aa 
I have updated the documentation: https://docs.apisec.ai/2fa/
This can be closed, if there is no plan to support Google Authenticator on IOS.

**Comment by Mohammed-Luqman-Shareef** [comment]
@fersy02, the issue is with Google authenticator , not with APIsec platform.  That is why team has suggested the alternatives.

**Comment by Mohammed-Luqman-Shareef** [comment]
@fersy02 Can you close this ticket.

**Comment by fersy02** [comment]
We are closing this as completed.
