### ISSUE TITLE
[Bug]: Reset Password Throwing Error

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#76]
### Severity

Blocker

### What happened?

Please look into this on priority

We are unable to reset the password using with or without the auto-generate password and email option. Here's the error:
![image](https://user-images.githubusercontent.com/47815523/169197671-d221b0aa-143b-4133-a055-3d69b1fbe6fd.png)

![image](https://user-images.githubusercontent.com/47815523/169198049-65954d14-7e1d-4093-926b-13de41532a0f.png)

**Comment by muqeetkhan20** [comment]
@fersy02 I was able to reset the password successfully. Please give a try again,

**Comment by muqeetkhan20** [comment]
I have also tried for the user "APIsec Support", you should receive a password.
![image](https://user-images.githubusercontent.com/68276700/169212068-6c89cb4a-0ea1-4e9d-914c-01d26c112765.png)

**Comment by fersy02** [comment]
A client has experienced the same issue trying to archive the existing vulnerabilities:
![image](https://user-images.githubusercontent.com/47815523/169272987-fe0bf98f-4f71-485e-945a-cb73dc7ab542.png)

**Comment by Abdullah-Akbar** [comment]
This was due to frequent CP restarts. I dont think it is an issue now.
