### ISSUE TITLE
[Bug]: Need help on profile deletion

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#77]
### Severity

Medium

### What happened?

One of the clients has reported that deleting a profile throws the following error:
![image](https://user-images.githubusercontent.com/47815523/169449355-2a7e859d-122c-41ae-827e-7f684b629710.png)

Although there are no active vulnerabilities, we can still not delete a profile.
![image](https://user-images.githubusercontent.com/47815523/169449046-b648c53b-adb7-4fc1-a160-d8dc5c58a860.png)

**Comment by Abdullah-Akbar** [comment]
After data cleanup, the new error message is 

![image](https://user-images.githubusercontent.com/89911730/169454301-3510e943-457d-4a7f-baaa-f20d3b979979.png)

**Comment by muqeetkhan20** [comment]
@fersy02 @Abdullah-Akbar tested on net banking app, unable to reproduce this bug.

**Comment by Abdullah-Akbar** [comment]
Presence of both Active and Closed bugs prevent deletion of profile. They should be archived before profile deletion.

**Comment by fersy02** [comment]
The problem is not with the presence and instead with the visibility of vulnerabilities. Additionally, without any active vulnerabilities the error message is misleading. Please check the attached screenshots.
