### ISSUE TITLE
[Bug] : Unable to open API's Vulnerability list portal on Safari browser

### ISSUE THREAD

**Issue by VineshAPISEC** [apisec-inc/Support#78]
### Severity

Medium

### What happened?

The url "http://cloud.fxlabs.io/ " isn't opening on Safari browser.Recieving blank page
<img width="1440" alt="Screenshot 2022-05-24 at 1 30 09 AM" src="https://user-images.githubusercontent.com/106115852/169899350-61a99977-f31d-409d-97f5-9592900913a4.png">

**Comment by MuqeedA** [comment]
@VineshAPISEC , We tried online safari browser and were able to open cloud.apisec.ai . 
What version of safari are you using?

**Comment by MuqeedA** [comment]
<img width="625" alt="image" src="https://user-images.githubusercontent.com/87184027/172998603-66e5bbda-d278-4e05-bb42-63b75e102f59.png">

we are able to open the cloud.fxlabs.io portal in online safari browser

**Comment by muqeetkhan20** [comment]
@VineshAPISEC QA doesn't have the operating system to verify the safari browser. 
Could you please verify and close the ticket if it's working?

**Comment by muqeetkhan20** [comment]
@aijajapisec please verify on online safari browser and close the ticket, for any assistance please coordinate with @MuqeedA

**Comment by MuqeedA** [comment]
@aijajapisec 
The Safari browser for Windows is outdated. You need to validate the APIsec portal in the latest Safari browser of Mac OS.  

Ref: https://support.apple.com/en-in/HT204416

**Comment by aijajapisec** [comment]
Hi @MuqeedA ,
@muqeetkhan20  1.Can you please help me to get  Mac OS , 2. I am not getting any online Safari browser
![image](https://user-images.githubusercontent.com/103985624/176598175-da91d86f-87cc-405f-8f16-605755eb971c.png)

**Comment by aijajapisec** [comment]
Hi @VineshAPISEC 
cc: @muqeetkhan20 

This is working fine , I have verified it on online Safari browser , It can be close now.
use this link to verify this issue https://app.lambdatest.com/viewer/TES10160531401656915616479447

![image](https://user-images.githubusercontent.com/103985624/177094323-b00480e8-c1bc-4fe0-9bde-23ae81102f5d.png)


Thanks
Aijaj

**Comment by muqeetkhan20** [comment]
@aijajapisec please log few vulnerabilities and verify if the vulnerability list is visible.

**Comment by aijajapisec** [comment]
![image](https://user-images.githubusercontent.com/103985624/177103341-15df21bd-7d17-4c0c-b5e0-705112663a1d.png)

**Comment by muqeetkhan20** [comment]
Thanks @aijajapisec 
@VineshAPISEC we are closing this ticket.
