### ISSUE TITLE
[Bug]: Vulnerabilities not getting logged for Unsecured category

### ISSUE THREAD

**Issue by muqeetkhan20** [apisec-inc/Support#80]
### Severity

Blocker

### What happened?

Scan the unsecured endpoint, the vulnerabilities are not getting logged.

**Comment by Abdullah-Akbar** [comment]
Just tested this in prod. working fine after restart.
![image](https://user-images.githubusercontent.com/89911730/170329207-6699a2db-86f4-4aba-913e-999656191b11.png)

**Comment by muqeetkhan20** [comment]
@MuqeedA please fix the threat icon for FP.
![image](https://user-images.githubusercontent.com/68276700/170331067-61d63778-12c8-409b-941f-3c2eb435feaf.png)

**Comment by MuqeedA** [comment]
@muqeetkhan20 , FP icon issue fixed.
