### ISSUE TITLE
[Bug]: Slack Notification returns an invalid URL

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#81]
### Severity

Medium

### What happened?

Slack Notification returns an invalid report URL.

The below sample URL is returned in the slack notification that throws an error code: 404 (Not Found)
https://cloud.fxlabs.io/#/app/projects/{projectId}/jobs/{jobId}/runs/{runId}
![image](https://user-images.githubusercontent.com/47815523/170443211-0149589f-e1c6-4645-9f1f-cd186c8c5444.png)

It works fine after replacing jobs with profiles in the URL:
Sample Working URL: https://cloud.fxlabs.io/#/app/projects/{projectId}/profiles/{profileId}/runs/{runId}
Previously we fixed the URL received in the response of apisec_job_invoke_script.sh (CI/CD) script. We need to address the same in the Slack Notification.

**Comment by muqeetkhan20** [comment]
@fersy02 we have problems integrating with slack, could you please verify and close this ticket.
