### ISSUE TITLE
[Bug]: PowerShell script for CI/CD is throwing errors

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#83]
### Severity

Blocker

### What happened?

A client is running into issues with the PowerShell script for MS Azure Integration. Please look into it ASAP.

**Comment by AkaramAli** [comment]
@fersy02  - Please share the steps to reproduce and logs if any ?

**Comment by fersy02** [comment]
@AkaramAli, please connect with @Mohammed-Luqman-Shareef for more details.
I discussed this issue today and found out that the PowerShell script is not fully functional.
