### ISSUE TITLE
[Bug]: Unsecured Vulnerabilities are not getting logged

### ISSUE THREAD

**Issue by asifadn9** [apisec-inc/Support#85]
### Severity

Blocker

**Comment by Mohammed-Luqman-Shareef** [comment]
@jaleelsyed / @mohdrashid1 
 it seems it is not able to connect to AI module.  Pls check.

**Comment by intesar** [comment]
@SyedsImran @Mohammed-Luqman-Shareef - This is urgent. We just had an awkward sales call trying to demo the unsecured category.

**Comment by mohdrashid1** [comment]
@Mohammed-Luqman-Shareef  AI module is now working fine
