### ISSUE TITLE
[Bug]: HMAC script update

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#90]
### Severity

Medium

### What happened?

Correction in the following HMAC Script:
https://raw.githubusercontent.com/apisec-inc/apisec-scripts/master/pre-script.py

sign_request function requires four arguments, out of which 3rd and 4th arguments are automatically substituted during run-time 
As per the sample script, the method is the 3rd argument, and the URL is 4th.
![image](https://user-images.githubusercontent.com/47815523/174843636-c5222541-85f2-43bc-b655-56b3fc6b56e4.png)

There is a correction in the sample script. The 3rd and 4th arguments are URL and Method, not Method, URL.
Update the following function in the script:
def sign_request(appID,
                secret,    
                url,      
                method):

These are system-defined arguments, and their occurrence must be accurate.

**Comment by AkaramAli** [comment]
Sample example script updated .
