### ISSUE TITLE
[Bug]: HMAC Authentication URL doesn't support variables

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#91]
### Severity

Blocker

### What happened?

If there is an endpoint that requires a path parameter. A variable is created automatically and the playbook path contains the syntax of that variable. We have noticed that the endpoint path sent contains the variable syntax and the value due to this signature is incorrectly generated and the authentication fails.

HMAC Authentication requires a script to generate a token. The script requires a couple of arguments including the method and the path of the endpoint that are passed automatically from the playbook. The path may contain path and query params. The path and required query params will have variables associated in the playbook. When generating a signature these variables should be resolved and values should be sent instead of variable syntax as shown below:

Expected Value: 
https://cloud.fxlabs.io/api/project/8a80937c80de191720180fb417ec46f99/get-spec

Actual Value:
https://cloud.fxlabs.io/api/project/{{@Var.id}}/get-spec

Due to this inconsistency playbooks with path or query parameters are failing due to an invalid signature and the only workaround is to modify the playbook and hardcode values in the path and required query parameters.

**Comment by asifadn9** [comment]
verified in dev, looks good

**Comment by muqeetkhan20** [comment]
Our request to create scanner with HMAC script in prod was not completed.
We were unable to test in prod. Hence closing this ticket.

Though it's we tested in dev env and its working.
