### ISSUE TITLE
[Bug]: Fails to discover APIs from Mulesoft API Gateway

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#93]
### Severity

Blocker

### What happened?

The customer has reported that they could connect to the Anypoint platform and view or download the API definitions. 

Using the same credentials when they tried to integrate with the Mulesoft API Gateway, they couldn't find any errors in the APIsec platform. However, the APIs are not visible in the APIsec account. There is no way to troubleshoot, nor are any errors observable for debugging the issue.

Please look into it on priority. Ping @fersy02 for more details and credentials.

**Comment by Abedeen1** [comment]
HI @fersy02 ,

Could you please share the apigee user info.

Regards,
Abedeen.

**Comment by Mohammed-Luqman-Shareef** [comment]
@Abedeen1 ,  I just sent you the details

**Comment by Abedeen1** [comment]
@fersy02 ,

The User doesent have access to API Manager
![Screenshot from 2022-06-27 11-08-48](https://user-images.githubusercontent.com/87793504/175867387-1820e2af-1baa-4ab1-955e-f0170ab487ad.png)

**Comment by fersy02** [comment]
Requested client to grant access of the API Manager component. @Abedeen1 is this point documented?

**Comment by Abedeen1** [comment]
@Mohammed-Luqman-Shareef , Could you please provide step to document

**Comment by muqeetkhan20** [comment]
@Mohammed-Luqman-Shareef this is an access issue at the client side and not reproducible, should we close the ticket or wait for document?

**Comment by fersy02** [comment]
@Abedeen1 
As per the client:
There is a sub category under “API Manager” called “Business Group” this user have access to that, here is the direct link for Business Group once you logged in https://anypoint.mulesoft.com/apimanager/lpl-financial-87/#/organizations/06093e0c-dc19-4f05-9ffb-7c820ce5d1d3/environments/e177c845-75a2-4e58-a8e6-075cbcf1d5a9/apis

To get to Business group, after you’ve logged in, click on “Api manager” then go to the top right corner and click on CW, you will see the Business Group, CW is one of the business group and the page should already default to that when you logged in.

![image](https://user-images.githubusercontent.com/47815523/176348436-a91ae67b-9823-4514-b30d-c3799759206c.png)

**Comment by Abedeen1** [comment]
@Mohammed-Luqman-Shareef ,

Below 2 senarios are not considered during development of Mulesoft Integration

1. Business Group
2. Environment.

Can we go further on its Patch.

Regards,
Abedeen.

**Comment by fersy02** [comment]
@Abedeen1 @Mohammed-Luqman-Shareef @intesar 
Initially, we need to support Business Group in Mulesoft API Integration for one of our customers to onboard 300+ APIs. Currently, they have onboarded 150 APIs manually.

**Comment by Abedeen1** [comment]
@fersy02 , This ticket is ready in development.

**Comment by Rahman-1234** [comment]
@muqeetkhan20 , @Abedeen1 
Getting Error while creating new Mulesoft API gateway in dev , Please refer SS
![image](https://user-images.githubusercontent.com/87167471/177267471-580a882d-ca91-4d52-824c-86c069b1e2b3.png)

**Comment by Abedeen1** [comment]
@Rahman-1234 , we are looking into it.

**Comment by Abedeen1** [comment]
@Rahman-1234 ,

We are able to register all the Mulesoft Api in developer env. for the user Fida-MS 

![Screenshot from 2022-07-05 12-30-06](https://user-images.githubusercontent.com/87793504/177268831-00a7e1b6-681f-477a-bdbb-bf1378341057.png)

Regards,
Abedeen.
