### ISSUE TITLE
[Bug]: On-premises Scanner Error

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#94]
### Severity

Blocker

### What happened?

One of our clients has reported an inconsistency with the On-premises scanner deployed in the AWS Cloud.
The scanner has deployed successfully. `sudo docker ps` lists the docker instance in the VM.
The VM has all outbound protocols, and ports opened.
Able to Ping, the cloud.fxlabs.io host from the VM.

The scanner appears running in the Private scanners tab, but upon checking the status, it throws a "Service Unavailable" error.

The client has also reported that the scanner had worked earlier, and suddenly it stopped functioning. Redeployed the scanner, but that didn't work.

**Comment by SyedsImran** [comment]
Just deployed a scanner as a docker container in AWS Ubuntu VM.
Scanner is able to connect to our prod VM( cloud.fxlabs.io) 
![image](https://user-images.githubusercontent.com/100760767/176247751-01f8938c-58fb-4afc-9847-961f7deea514.png)

Status of it is showing as running and "OK" on the UI page.
![image](https://user-images.githubusercontent.com/100760767/176247917-a5559e3b-0454-4a34-95aa-b8d279f6f828.png)

Also run few scans on it, scanner is processing the playbooks as expected.
![image](https://user-images.githubusercontent.com/100760767/176248447-bb69497c-2d2c-411a-ab51-894844def999.png)

**Comment by muqeetkhan20** [comment]
@fersy02 we are unable to verify, due to tenant specific. Should we close the ticket?

**Comment by fersy02** [comment]
@muqeetkhan20, I haven't received a confirmation from the client yet, but we could close this ticket, and if required, we shall reopen this ticket or file a new one. Thanks!
