### ISSUE TITLE
[Bug]: Previous and Next Scan buttons throwing an Error

### ISSUE THREAD

**Issue by fersy02** [apisec-inc/Support#95]
### Severity

Medium

### What happened?

On the scan details page, we have Previous & Next <> buttons to navigate to other scans. Upon clicking the next button(>) from the last scan or the previous button(<) from the first scan, it throws an error instead of notifying the user.

![image](https://user-images.githubusercontent.com/47815523/176370974-43af2681-e72c-4f21-a3ba-a18e279b0162.png)

Ideally, the next button(>) on the last scan and the previous button(<) on the first scan should be disabled or greyed out.

**Comment by muqeetkhan20** [comment]
@fersy02 we have already raised this bug 2 weeks ago, engineering should fix this sooner. 
https://github.com/apisec-inc/Engineering/issues/234

We can close this support ticket to avoid the duplicate.

**Comment by fersy02** [comment]
Sure, @muqeetkhan20. Please go ahead.
