### ISSUE TITLE
[Bug]: Expired Login wasn't automatically redirecting to Logout page

### ISSUE THREAD

**Issue by intesar** [apisec-inc/Support#99]
### Severity

Blocker

### What happened?

1. Went to the cloud.fxlabs.io
2. My login was expired so the UI showed me an error message saying, /login-status received 500 
3. When I canceled the error dialog it was showing the same blank page and didn't redirect to the login page
4. I had to go to the top-right menu and click the logout icon, then it showed the login page

This is a blocker. The user has no other obvious way of accessing the application. When the user receives an error on /login-status, we should redirect the user to the login page with the proper login expired message.

**Comment by muqeetkhan20** [comment]
@intesar this behaviour is inconsistent, few of our team members got to experience this issue but not always.
